PE-3517: display a placeholder message for when USD quote is unavailable
ardriveapp/ardrive-web pull request #1040
Opened 2023-04-21 17:23 UTC by matibat

2023-04-21 17:28 UTC, matibat reviewed
Self-review checkpoint

2023-04-21 17:28 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +      // TODO: snapshot creation is not backed off by Turbo
TODO: Check if we have a ticket for it

2023-04-21 17:48 UTC, thiagocarvalhodev commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +    late double? usdUploadCost;
We're implementing the same logic three times. Consider adding the try catch inside the `_arweave.getArUsdConversionRate` or a helper method returning null in case of error.

2023-04-21 17:49 UTC, thiagocarvalhodev requested changes
Please abstract the `try catch` block into a new function or the same one.

2023-04-21 18:51 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +    late double? usdUploadCost;
Implemented a helper method

2023-04-24 13:39 UTC, thiagocarvalhodev requested changes
Tests are failing.

2023-04-24 17:57 UTC, thiagocarvalhodev approved these changes
LGTM!

2023-04-24 17:58 UTC, merged