PE-3786: Compute snapshot out of cached metadata
ardriveapp/ardrive-web pull request #1109
Opened 2023-05-19 15:24 UTC by matibat

[ Work in progress ]

2023-05-19 19:59 UTC, matibat reviewed
We're missing clearing the cache when the user logs out

2023-05-19 19:59 UTC, matibat commented on lib/services/arweave/arweave_service.dart
> +
```suggestion
```

2023-05-19 19:59 UTC, matibat commented on lib/utils/metadata_cache.dart
Logging here is too vague and ambiguous. Let's be more concise

2023-05-19 19:59 UTC, matibat commented on test/utils/metadata_cache_test.dart
The `remove` and `clear` methods aren't being rested

2023-05-19 20:13 UTC, matibat commented on test/utils/metadata_cache_test.dart
f05e7d8f869b2288b59ce44f3ac3f2dba65ccce7

2023-05-19 20:16 UTC, matibat commented on lib/utils/metadata_cache.dart
08486f9f48307f675b7c8b185a560ed55630b4e1

2023-05-19 21:37 UTC, matibat commented
Tests are broken because of the "clear cache on logout" functionality - issues with async contexts mostly

2023-05-22 14:26 UTC, matibat reviewed
Nits

2023-05-22 15:20 UTC, matibat commented on test/utils/metadata_cache_test.dart
> +    test('will accept up to 10 entries', () async {
dc42872cffbf1af727a513181cef2b9424944ac2

2023-05-22 15:21 UTC, matibat commented on test/utils/metadata_cache_test.dart
> +  assert(mockData.length == count);
1e0d7dbf8617b7b4e3a136fac4b6602cf0c318af

2023-05-22 15:24 UTC, matibat reviewed
Self-review checkpoint

2023-05-22 15:24 UTC, matibat commented on lib/authentication/ardrive_auth.dart
> +  Future<MetadataCache> get metadataCache async {
Make it private if possible

2023-05-22 15:25 UTC, matibat commented on lib/authentication/ardrive_auth.dart
> +  Future<MetadataCache> get metadataCache async {
1b16e8092aaeeed767451443a43e42c9f4d69c49

2023-05-22 20:37 UTC, thiagocarvalhodev approved these changes
LGTM! I'd only want to replace the `w` with `e` method from the logger.

2023-05-22 20:37 UTC, thiagocarvalhodev commented on lib/services/arweave/arweave_service.dart
> +      logger.w(
Use logger.e (error) for this.

```darrt
logger.e('An error occurred when getting the unique user drive entities.', e, stacktrace);

2023-05-22 20:37 UTC, thiagocarvalhodev commented on lib/services/arweave/arweave_service.dart
> +      logger.w(
The same comment for the other logs on catch blocks.

2023-05-25 16:38 UTC, matibat commented on lib/services/arweave/arweave_service.dart
> +      logger.w(
d657c23426684098fff804be36cafa139212edf1

2023-06-01 18:41 UTC, thiagocarvalhodev requested changes

2023-06-01 18:41 UTC, thiagocarvalhodev commented on lib/authentication/ardrive_auth.dart
> +      (await _metadataCache).clear();
We should remove the logic of the database and cache from auth. I understand you added it because we're already doing it, but we'll need to remove it in the future. I added a tech debt
https://ardrive.atlassian.net/browse/PE-3940

2023-06-01 18:41 UTC, thiagocarvalhodev commented on lib/utils/metadata_cache.dart
> +    if (await isFull) {
Consider removing this as we'll call the `isFull` two times for every `put` call, and in this case we're just using for logging. Add this log on the first isFull

2023-06-01 19:21 UTC, matibat commented on lib/authentication/ardrive_auth.dart
> +      (await _metadataCache).clear();
Yeah. I wasn't sure where to get a hook for the logout event. If you have a suggestion for that I'm happy to apply it, if not then the tech_debt is fine. Thanks! 🙏

2023-06-01 19:23 UTC, matibat commented on lib/utils/metadata_cache.dart
> +    if (await isFull) {
So as soon as we know the cache is full, and won't be able to take more items, then we log the statement just once :)

2023-06-02 16:34 UTC, karlprieb submitted a review, later dismissed

2023-06-12 16:28 UTC, merged