PE-3954: refactor(snapshot_item_to_be_created.dart): replace asyncMap with StreamController to batch calls
ardriveapp/ardrive-web pull request #1143
Opened 2023-06-13 18:23 UTC by jdaev

--- Releases ---
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/1no0bu37kutpg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/0tju1g4mas970

2023-06-14 16:23 UTC, matibat commented
The code seems good to me. Before approving I wanna ensure that we're preserving the order of the TXs, so I'll give it a try

2023-06-14 16:47 UTC, matibat requested changes
There was a missing requirement in the ticket: preserve the same order as GQL.

2023-06-19 19:04 UTC, karlprieb submitted a review, later dismissed

2023-06-19 19:12 UTC, matibat submitted a review, later dismissed
Tests are now passing. Thanks! <3

2023-06-21 20:01 UTC, matibat approved these changes

2023-06-21 20:02 UTC, merged