PE-3985: [WIP] Create new pin modal
ardriveapp/ardrive-web pull request #1249
Opened 2023-07-20 18:08 UTC by matibat

2023-07-27 19:11 UTC, matibat reviewed
Self-review checkpoint.

2023-07-27 19:11 UTC, matibat commented on lib/blocs/pin_file/pin_file_state.dart
> +          idValidation: IdValidationResult.validEntityId,
It's not affecting the logic RN, but let's not assume it's a "valid entity id" when it can be a transaction id

2023-07-27 19:11 UTC, matibat commented on lib/components/new_button/new_button.dart
> +            icon: ArDriveIcons.arconnectIcon1(size: defaultIconSize),
TODO: put the icon

2023-07-27 19:11 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +          // FIXME: give some feedback on error
Tech debt: error modal

2023-07-27 19:11 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +                if (customErrorMessage != null)
Tech debt: design for these messages

2023-07-27 19:11 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +                      if (validation == IdValidationResult.invalid) {
What about required? Same for the name field

2023-07-27 19:11 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +                      if (validation == IdValidationResult.invalid) {
Also, it's sad that I can't set a custom error from the state

2023-07-27 19:11 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +              isEnable: state is PinFileFieldsValid &&
Nit and out of scope

2023-07-27 19:11 UTC, matibat commented on lib/services/config/app_config.dart
> +    this.enablePins = false,
Maybe it's because this line that the dev tools are marking it as disabled by default, even that I've set the JSON config?

2023-07-27 19:11 UTC, matibat commented on lib/utils/debouncer.dart
Yet unused, should I remove it?

2023-07-27 19:11 UTC, matibat commented on test/blocs/pin_file_bloc_test.dart
> +
```suggestion
```

2023-07-27 20:52 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/file_id_resolver.dart
> +    final uri = Uri.https(
Use the Uri.parse instead of Uri.https:

```dart
Uri.parse('${configService.config.defaultArweaveGatewayUrl!}/$dataTxId')
```

2023-07-28 13:38 UTC, thiagocarvalhodev requested changes
Looking pretty good! Some refactors are not required, but we need:
- Update the translations
- Add error feedback
- Update the pin icon

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/file_id_resolver.dart
> +    late FileEntity? fileEntity;
You can remove the `late` keyword as this property can be null

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +          emit(PinFileFieldsValidationError(
Consider implementing a private method of each `emit` method. It will improve the readability

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +          logger.d('Unexpected state $state');
What's the feedback to the user if we reach this point? Consider adding a generic error state, then show a generic message.

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +    on<FieldsChanged>((event, emit) async {
I suggest implementing a private method for each event handle. You can see an example on the `login_bloc.dart`

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +            null, // TODO: key
Do we have a ticket to handle private drives?

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +  Future<bool> doesNameConflicts(String name) async {
Consider changing this method to be private

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +      // TODO: do somethin'
If we can't check if an entity with the same doesn't exists, we should show a feedback error to the user. Let's add it as a tech debt.

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +  NameValidationResult validateName(String value) {
I really liked your approach to handling the name validation. We have other methods that does the same thing. 
Please create a new ticket to replace the already implemented methods with this one.

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +  IdValidationResult validateId(String value) {
The same for my previous comment.

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/types.dart
> +class FileInfo {
`FileInfo` is pretty generic. Consider changing the name of this class

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/components/pin_file_dialog.dart
> +          // FIXME: give some feedback on error
We must show at least generic feedback to the user here.

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/components/pin_file_dialog.dart
> +                      if (validation == IdValidationResult.invalid) {
>Also, it's sad that I can't set a custom error from the state

Can you explain it?

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/services/config/config_fetcher.dart
> +    final enablePins = localStore.getBool('enablePins');
`enablePins` is defined on the env config file. We don't need to update it here.

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/utils/debouncer.dart
Yes!

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/utils/debouncer.dart
> +class Debouncer {
🚀

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/services/config/app_config.dart
> +    this.enablePins = false,
If the `enablePins` is provided, it will use the value passed to this constructor

2023-07-28 13:38 UTC, thiagocarvalhodev commented on lib/components/pin_file_dialog.dart
> +                if (customErrorMessage != null)
Do we have the designs? If not, please reach Alison for provide those

2023-07-28 15:53 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +                if (customErrorMessage != null)
What I mean here is: I can't set a "custom validation error" to the text field, so instead, I had to put a text at the bottom as if it were an error message, but it's actually a simple Text element

2023-07-28 15:54 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +                if (customErrorMessage != null)
BTW we decided to put this into the scope of "Add Error Handling and Feedback to the User"

2023-07-28 15:56 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +                      if (validation == IdValidationResult.invalid) {
See this comment: https://github.com/ardriveapp/ardrive-web/pull/1249#discussion_r1277724976

TL/DR - The ArDriveTextField component doesn't have a "validationErrorMessage" property, so we can't display one. We can just run an input validation.

2023-07-28 15:58 UTC, matibat commented on lib/blocs/pin_file/pin_file_bloc.dart
> +          emit(PinFileFieldsValidationError(
Sorry, I didn't get it. What would that private method do?

2023-07-28 16:03 UTC, matibat commented on lib/blocs/pin_file/pin_file_bloc.dart
> +  NameValidationResult validateName(String value) {
I actually copy/pasted them, and refactored them to be pure & de-coupled methods. The other methods are coupled to the UI because they depend on the context for localizations. What I did instead is to return an enum, so the UI can decide what to display based on the enum value.

So yes, it would be great to replace them with this more generic one :)

2023-07-28 16:05 UTC, matibat commented on lib/services/config/config_fetcher.dart
> +    final enablePins = localStore.getBool('enablePins');
So then this is the line that sets the value to false even when it is set to true in the config. Thanks!

2023-07-28 16:08 UTC, matibat commented on lib/utils/debouncer.dart
ddc789415d2430d6bfd40c456f272b5cb816c11b

2023-07-28 16:10 UTC, matibat commented on lib/services/config/config_fetcher.dart
> +    final enablePins = localStore.getBool('enablePins');
bf56f33f8e8fb845a32499893a40f01d3e9f8004

2023-07-28 16:16 UTC, matibat commented on lib/blocs/pin_file/pin_file_bloc.dart
> +  Future<bool> doesNameConflicts(String name) async {
0a0fd8bb0b5c981b378d5fb69adc27d795bbef3c

2023-07-28 16:19 UTC, matibat commented on lib/blocs/pin_file/pin_file_bloc.dart
> +  }
76113eb4ac649b5fbfffddac4dbfa589120d1c56

2023-07-28 16:19 UTC, matibat commented on lib/blocs/pin_file/pin_file_bloc.dart
> +    // idTextController.dispose();
76113eb4ac649b5fbfffddac4dbfa589120d1c56

2023-07-28 16:25 UTC, matibat commented on lib/blocs/pin_file/pin_file_state.dart
> +  // network check
b9924b726f56f31db14c7c5d6f3aea73f601bb1b

2023-07-28 17:51 UTC, matibat commented on lib/blocs/pin_file/pin_file_state.dart
DrivePrivacy: 147dd8d81b331266b6292075a3be7bab4852d1ea

2023-07-28 17:59 UTC, matibat commented on lib/blocs/pin_file/pin_file_state.dart
Transaction ID and File ID types: 83fb9f426093cb4914e46929be6f90346c1232d1

2023-07-28 18:03 UTC, matibat commented on lib/blocs/pin_file/pin_file_state.dart
> +          idValidation: IdValidationResult.validEntityId,
ba3178616fe79c9ff176b4056fd6744b60553b03

2023-07-28 18:07 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +                      if (validation == IdValidationResult.invalid) {
Required field validation: 6e4df16e7d432b2d88da9cb8e069964550e0d901

2023-07-28 18:09 UTC, matibat commented on test/blocs/pin_file_bloc_test.dart
> +
3bfaca75f86b42f6ef276f60060b34163f220307

2023-07-28 18:11 UTC, matibat commented on lib/blocs/pin_file/file_id_resolver.dart
> +    final uri = Uri.https(
f9b6a7f9f4a8c16052ebd192050d3741f01a7ac1

2023-07-28 18:12 UTC, matibat commented on lib/blocs/pin_file/file_id_resolver.dart
> +    late FileEntity? fileEntity;
448ecbc87695e923f4a8439fbb166e20fe29ff63

2023-07-28 18:20 UTC, matibat commented on lib/blocs/pin_file/types.dart
> +class FileInfo {
If I made it private I couldn't access it from the unit tests, so I renamed to `ResolveIdResult`: b93318fe53d8e49f0d02846e4546e6f8153250e0

2023-07-28 18:21 UTC, matibat commented
Addressed the most relevant and non-tech-debt-related comments. Will now setup localization

2023-07-28 18:47 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +          emit(PinFileFieldsValidationError(
For example:

```dart
emitPinFileFieldsValidationError() 
```

which emits the state inside

2023-07-28 19:06 UTC, matibat commented
Localizations in place!

2023-07-28 19:11 UTC, matibat commented on lib/l10n/app_en.arb
> +  "createAndConfirmPassword": "Please create and confirm your password.",
It seems someone edited this locally but not in Localizely

2023-07-28 20:42 UTC, matibat commented
Re-enabled turbo uploads!

I tested them again and they are working just fine. My guess is that what happened is that a chain fork made my files go away when testing yesterday.

2023-07-28 20:43 UTC, matibat commented
Also, I realized that in the case you provide a File-Id, the owner it was setting is the owner of the File METADATA (which can be a pin), and not the owner of the actual DATA. Here it is the fix: [7417978](https://github.com/ardriveapp/ardrive-web/pull/1249/commits/7417978be2cc124d93c233d20de363d361639b78)

2023-07-31 13:15 UTC, thiagocarvalhodev reviewed
Left just a few more comments.

2023-07-31 13:15 UTC, thiagocarvalhodev commented on lib/components/pin_file_dialog.dart
> +                      if (validation == IdValidationResult.invalid) {
The input validation returns the text with the validation message and displays it at the bottom of the ArDriveTextField. If it is not what is happening, so it's an error on the component.

2023-07-31 13:15 UTC, thiagocarvalhodev commented on lib/l10n/app_en.arb
> +  "createAndConfirmPassword": "Please create and confirm your password.",
It was edited on localizelly but after you start this feature, so for you it was the old text

2023-07-31 13:15 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/file_id_resolver.dart
> +class OwnerAndPrivacy {
This class name is very generic. One good question is: owner and privacy of what? In this case, an transaction.
Consider: `TransationOwnerAndPrivacy`.

Or, we can make this class only visible inside this file, so the reader know exactly the context and won't get confused seeing this class in another context.

2023-07-31 13:15 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +  NameValidationResult validateName(String value) {
That's a pretty good solution. Don't forget to create a tech debt to update this!

2023-07-31 13:15 UTC, thiagocarvalhodev commented on lib/blocs/pin_file/pin_file_bloc.dart
> +    on<FieldsChanged>((event, emit) async {
@matibat , consider doing the refactor I suggested

2023-07-31 15:37 UTC, matibat commented on lib/components/pin_file_dialog.dart
> +                      if (validation == IdValidationResult.invalid) {
Yes. That's the only way to make a text field display an error: it's triggered when the user manually edits the field. There's no way of setting a custom error message that came from the state, let's say.

In my case, I cannot set the errors that came from the network, such as for non-existing transactions.

That's why I'm displaying the error message at the bottom.

2023-07-31 15:51 UTC, matibat commented on lib/blocs/pin_file/file_id_resolver.dart
> +class OwnerAndPrivacy {
I made it be private: de31ebb864b4b801e8d3dd4a3eb99bd105ca5444

IMO it's not the "owner and privacy of a transaction" because transactions are always public, privacy is an ArFS concept. The class has a generic name because it is actually a generic pair of owner address and privacy: it can be the owner and privacy of a drive, a folder, a file, or a snapshot.

2023-07-31 16:00 UTC, matibat commented on lib/blocs/pin_file/pin_file_bloc.dart
> +    on<FieldsChanged>((event, emit) async {
Here: ca94bd75218d11780a1f24013ce73e4d1e252256

2023-07-31 16:01 UTC, matibat commented on lib/blocs/pin_file/pin_file_bloc.dart
> +            // TODO: key
Not a tech debt: it's out of scope

2023-07-31 16:02 UTC, matibat commented on lib/components/new_button/new_button.dart
> +            icon: ArDriveIcons.arconnectIcon1(size: defaultIconSize),
Out of scope for this story

2023-07-31 16:03 UTC, matibat commented on lib/blocs/pin_file/pin_file_bloc.dart
> +          logger.d('Unexpected state $state');
The bloc already has an error state, there's the other story that will handle the UI

2023-07-31 16:06 UTC, matibat commented on lib/l10n/app_en.arb
> +  "createAndConfirmPassword": "Please create and confirm your password.",
Hmm, I exported these changes on Friday. Was it changed on late Friday? If not then we have to update it on Localizely

2023-07-31 16:40 UTC, thiagocarvalhodev submitted a review, later dismissed
Thanks for the hard work!

2023-07-31 16:59 UTC, thiagocarvalhodev commented on lib/l10n/app_en.arb
> +  "createAndConfirmPassword": "Please create and confirm your password.",
Checked on localizelly and the Strings match

2023-08-18 19:41 UTC, karlprieb approved these changes

2023-08-18 19:48 UTC, merged