PE-4502: filters the arfs transactions in the client side
ardriveapp/ardrive-web pull request #1328
Opened 2023-08-30 15:40 UTC by matibat

WIP

### Changes
- Filters the ArFS transactions in the client side

### TODO
- Make the single-item-queries request pages of one until the first one matches.

2023-08-30 15:43 UTC, matibat commented
Follow-up work of #1316

2023-08-30 18:10 UTC, matibat reviewed
Self-review checkpoint

2023-08-30 18:10 UTC, matibat commented on lib/services/arweave/arweave_service.dart
> +    // FIXME: make me run all pages
This comment refers to #1330 
TODO: either integrate that PR into this one, or remove the comment

2023-08-30 18:10 UTC, matibat commented on lib/services/arweave/graphql/queries/FirstFileEntityWithIdOwner.graphql
>      first: 1
```suggestion
    first: 10
```

2023-09-01 13:20 UTC, thiagocarvalhodev commented on lib/utils/arfs_txs_filter.dart
> +class Tag {
We already have a class `Tag` on our `arweave-dart` package, let's use the same class here

2023-09-01 13:23 UTC, thiagocarvalhodev requested changes
Just a minor change

2023-09-01 13:33 UTC, matibat commented on lib/utils/arfs_txs_filter.dart
> +class Tag {
Yes. And we also have another one from the auto-generated code of GQL as well, so I opted to use a custom one. I'd indeed prefer to simply describe the shape of the tags so I could take any implementation but didn't know how to.

2023-09-01 13:51 UTC, thiagocarvalhodev commented on lib/utils/arfs_txs_filter.dart
> +class Tag {
>I'd indeed prefer to simply describe the shape of the tags so I could take any implementation but didn't know how to.

So we can re-use the tag from the `arweaved-dart`, this way we can avoid some confusion in the future because of 3 class that represents the same entity, does that make sense?

2023-09-01 14:08 UTC, matibat commented on lib/utils/arfs_txs_filter.dart
> +class Tag {
Makes sense. Applied - 2557e91b6f4d309b4833a54e33ed513bf9099006

2023-09-01 15:00 UTC, thiagocarvalhodev approved these changes
LGTM! thanks mati!

2023-09-05 14:13 UTC, merged