PE-4454: Add Promo Code Field to Turbo Modal
ardriveapp/ardrive-web pull request #1335
Opened 2023-09-05 14:28 UTC by matibat

2023-09-05 15:10 UTC, matibat commented
@matibat, the tests are not passing!

2023-09-06 12:32 UTC, thiagocarvalhodev reviewed
@matibat , the promo field doesn't apply the promo, even though the text field shows the green border indicating the code entered is valid, but no promotion or any other feedback is shown

https://github.com/ardriveapp/ardrive-web/assets/32248947/99443d0f-b544-4fa5-9950-8ffd8166a7b5

2023-09-06 12:56 UTC, thiagocarvalhodev requested changes
Left a couple of comments and some required changes.

2023-09-06 15:35 UTC, matibat commented on lib/turbo/topup/blocs/payment_review/payment_review_state.dart
> +    // PaymentUserInformation? userInformation,
Ahh yes. I was pretty sure we were not using that piece of data. IMO we can remove that.

2023-09-06 15:38 UTC, matibat commented
RE:
> @matibat , the promo field doesn't apply the promo, even though the text field shows the green border indicating the code entered is valid, but no promotion or any other feedback is shown

You have to click the Apply button, although it seems it's not visible on the light theme.

Also, the only three valid Codes I've enabled are `TURBO`, `ARDRIVE`, and `MATI`.

2023-09-06 18:28 UTC, matibat commented
Added an extra code: `ERROR` that will simulate a network error.

2023-09-07 12:13 UTC, thiagocarvalhodev reviewed
We will need just more one refactor on the `Turbo` class, and also to update the unit tests on the PaymentFormBloc

2023-09-07 12:13 UTC, thiagocarvalhodev commented on lib/turbo/turbo.dart
> +  Future<double?> getPromoDiscountFactor(String promoCode) async {
The Turbo class should use an abstraction for the logic of the promo code and implement a method using an abstraction. We can see similar examples on the other methods. 

What I suggest is to implement this method in a new class to retrieve the promo code and that also validates the code, example: `TurboPromoDiscountValidator`, that will get a promo code, fetch the API and validate if it's valid or not depending on the service response.

We can also implement a method on the `PaymentService` class to mock the http call, and use this class on the `TurboPromoDiscountValidator`, so, when the backend is done, we can just replace the call on the payment service and we won't change anything else in the code.

2023-09-07 12:13 UTC, thiagocarvalhodev commented on lib/turbo/turbo.dart
> +  Future<double?> getPromoDiscountFactor(String promoCode) async {
With that, we can also implement the unit tests validating a mocked response from the `PaymentService`

2023-09-07 12:13 UTC, thiagocarvalhodev commented on lib/turbo/turbo.dart
> +  // Future<double?> _getPromoDiscountFactor(String promoCode) async {
Commented code

2023-09-07 12:13 UTC, thiagocarvalhodev commented on test/turbo/blocs/payment_form/payment_form_bloc_test.dart
> +        credits: BigInt.from(10),
We are not testing the case when the promo discount is different than 0.
We need to test:
 - promo discount different from 0
 - promo discount has an error

2023-09-07 12:15 UTC, thiagocarvalhodev commented
Now the feature is looking great! Thanks for the fix on Theme, @matibat

2023-09-07 16:03 UTC, matibat commented on lib/turbo/turbo.dart
> +  Future<double?> getPromoDiscountFactor(String promoCode) async {
Is this what you meant? - 5912114a34c596c110d74bf223d66bd60dd65cef

2023-09-07 16:30 UTC, matibat commented on lib/turbo/topup/blocs/payment_review/payment_review_state.dart
> +    // PaymentUserInformation? userInformation,
26aa7a40c25351c08ec4d70cc89cf88290d07a96

2023-09-07 16:30 UTC, matibat commented on lib/turbo/topup/views/topup_payment_form.dart
> +  }
Applied

2023-09-07 16:31 UTC, matibat commented on lib/turbo/turbo.dart
> +  // Future<double?> _getPromoDiscountFactor(String promoCode) async {
Removed

2023-09-07 16:33 UTC, matibat commented on test/turbo/blocs/payment_form/payment_form_bloc_test.dart
> +        credits: BigInt.from(10),
The bloc won't behave differently for a different promoDiscountFactor. So the zero value is not distinct (in behavior) from one.

Also, there's no error case for this bloc.

2023-09-07 18:00 UTC, thiagocarvalhodev commented on test/turbo/blocs/payment_form/payment_form_bloc_test.dart
> +        credits: BigInt.from(10),
>Also, there's no error case for this bloc.

I mean the test for emitting this state:

```dart
emit(
        PaymentFormLoaded(
          state.priceEstimate,
          _expirationTimeInSeconds(turbo.maxQuoteExpirationDate),
          (state as PaymentFormLoaded).supportedCountries,
          isPromoCodeInvalid: false,
          isFetchingPromoCode: false,
          errorFetchingPromoCode: true,
        ),
      );

2023-09-07 18:03 UTC, thiagocarvalhodev commented on lib/turbo/turbo.dart
> +  Future<double?> getPromoDiscountFactor(String promoCode) async {
Exactly! We are now just missing the unit tests

2023-09-07 18:58 UTC, matibat commented on test/turbo/blocs/payment_form/payment_form_bloc_test.dart
> +        credits: BigInt.from(10),
Makes the class be testable by injecting a method to make it be deterministic - d228ee900704c19d7bdf22a691f6d9ed08973d0d
Unit tests those cases - 2428e7394be807a3685c3819320be238072c1189

2023-09-08 13:59 UTC, thiagocarvalhodev approved these changes
Tested and it's working nicely! I just noticed that we can improve the UX by a simple change. @matibat , I think it would be a nice UX if we also could load the promo code by hitting enter on the field. We have already a property on the component that does that: `onFieldSubmitted`. It's a callback that will be triggered when you hit enter, so you can just call the same function you call on the `Apply` button.

I'm approving, if you think it makes sense just let me know so I'll approve again.

2023-09-11 18:21 UTC, matibat commented
Changes are carried to #1349

2023-09-11 18:21 UTC, closed without merging