PE-4559: Integrate the promo code ui to the backend
ardriveapp/ardrive-web pull request #1349
Opened 2023-09-09 19:02 UTC by matibat

2023-09-09 22:13 UTC, matibat reviewed
Some cleanup to do

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/blocs/payment_form/payment_form_bloc.dart
> +      logger.d('Invalid promo code: $promoCode.');
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/blocs/topup_estimation_bloc.dart
> +      logger.i('selected amount: ${priceEstimate.priceInCurrency}');
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/blocs/topup_estimation_bloc.dart
> +      logger.e('Error calculating the estimation', e, s);
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/models/payment_model.dart
> +  // adjustments
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/models/payment_model.dart
> +  String? get humanReadableDiscountPercentage {
```suggestion
  String get humanReadableDiscountPercentage {
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/views/topup_modal.dart
> +                  // HOLA MATI
Hola!
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/views/topup_payment_form.dart
> +                  // Here you have to reset the promo code
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/views/topup_review_view.dart
> +                                // HOLA, MATI
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/topup/views/topup_review_view.dart
> +                                  // HERE, Mati
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/turbo.dart
> +    // required TurboPromoCode turboPromoCode,
```suggestion
```

2023-09-09 22:13 UTC, matibat commented on lib/turbo/turbo.dart
> +  // _turboPromoCode = turboPromoCode;
```suggestion
```

2023-09-09 22:17 UTC, matibat reviewed
I'm good with the code now. Let's fix the unit tests.

2023-09-10 21:12 UTC, matibat commented
Just fixed the unit tests. Now I'll make a quick smoke test to ensure it's still working as intended :)

2023-09-11 13:40 UTC, thiagocarvalhodev requested changes
Reviewed the UI and the blocs. I still need to finish the review of the tests.

2023-09-11 13:40 UTC, thiagocarvalhodev commented on lib/turbo/services/payment_service.dart
> +    logger.d('Turbo price fetch status code: ${result.statusCode}');
Use the `logger.e` method

2023-09-11 13:40 UTC, thiagocarvalhodev commented on lib/turbo/topup/blocs/topup_estimation_bloc.dart
> +            logger.e('error updating the promo code', e, s);
We're assuming that every error on the price estimation is due to the promo code

2023-09-11 13:40 UTC, thiagocarvalhodev commented on lib/turbo/topup/blocs/topup_estimation_bloc.dart
> +    } catch (e, _) {
Remove this try-catch block

2023-09-11 13:40 UTC, thiagocarvalhodev commented on lib/turbo/topup/models/payment_model.dart
> +    final discountPercentage = 100 - (operatorMagnitude * 100);
We have this logic already implemented.

2023-09-11 13:40 UTC, thiagocarvalhodev commented on lib/turbo/topup/views/topup_payment_form.dart
> +      final hasPromoCodeApplied =
Instead of accessing the `priceEstimate.estimate.adjustments` add the `hasPromoCodeApplied` property to the state to abstract this logic from the UI.

2023-09-11 13:40 UTC, thiagocarvalhodev commented on lib/turbo/topup/views/topup_payment_form.dart
> +                          if (state.priceEstimate.estimate
Instead of accessing the estimate object, consider passing the `humanReadableDiscountPercentage` on the state object.

2023-09-11 13:40 UTC, thiagocarvalhodev commented on lib/turbo/topup/views/topup_payment_form.dart
> +                    final actualPaymentAmount = state
Add this property to the state object instead of accessing the estimate object and performing business logic on the UI

2023-09-11 13:46 UTC, matibat commented on lib/turbo/services/payment_service.dart
> +          logger.d('Invalid promo code: $promoCode');
Yes, it is. The status code 400 (Bad request) means the promo code is invalid or expired.

2023-09-11 13:48 UTC, matibat commented on lib/turbo/topup/blocs/payment_form/payment_form_bloc.dart
> +            mockExpirationTimeInSeconds: mockExpirationTimeInSeconds,
In order to make it deterministic. The original implementation is using dynamic values (i.e. `DateTime.now()`)

2023-09-11 16:29 UTC, matibat commented
The comments on this PR are gonna be addressed in a following-up task - PE-4565

Thanks, @thiagocarvalhodev, for the thoughtful review! <3

2023-09-11 18:47 UTC, thiagocarvalhodev approved these changes

2023-09-11 18:56 UTC, merged

2023-09-19 20:42 UTC, matibat commented on lib/turbo/services/payment_service.dart
> +    logger.d('Turbo price fetch status code: ${result.statusCode}');
This is not an error.