PE-4752: Wallet address in login page PoC
ardriveapp/ardrive-web pull request #1413
Opened 2023-10-06 18:14 UTC by matibat

2023-10-09 14:46 UTC, thiagocarvalhodev commented on lib/authentication/login/blocs/login_bloc.dart
> +  Future<String?> getWalletAddress() async {
Can we implement this method on the `ArDriveAuth` class?

2023-10-09 14:48 UTC, thiagocarvalhodev commented on lib/user/repositories/user_repository.dart
> +  Future<String?> getOwnerOfDefaultProfile();
Can you add a comment here explaining why we can receive a null value? e.g. returns null if no profile is available

2023-10-09 14:48 UTC, thiagocarvalhodev requested changes
Left a few changes that you can consider implementing

2023-10-09 15:27 UTC, matibat commented on lib/authentication/login/blocs/login_bloc.dart
> +  Future<String?> getWalletAddress() async {
There we go - 7f293297c9285c708b5fdf29c9ed357c1d6f46c6

2023-10-09 15:27 UTC, matibat commented on lib/user/repositories/user_repository.dart
> +  Future<String?> getOwnerOfDefaultProfile();
Here it is - 756f7141bbff1adaa57dc4d6ebfa456d8449b3af

2023-10-09 17:47 UTC, thiagocarvalhodev requested changes
Thanks for applying the changes! We are just missing the tests on the new method of the repository. I can approve after that

2023-10-11 16:03 UTC, thiagocarvalhodev submitted a review, later dismissed

2023-10-12 13:40 UTC, thiagocarvalhodev approved these changes

2023-10-18 14:58 UTC, merged