PE-4866: implement a contract reader that reads our own cache
ardriveapp/ardrive-web pull request #1439
Opened 2023-10-24 13:17 UTC by thiagocarvalhodev

2023-10-24 18:30 UTC, kunstmusik commented on packages/pst/lib/src/implementations/pst_web.dart
> +// ignore: depend_on_referenced_packages
Shouldn't we add a dependency rather than use this ignore?

2023-10-25 20:13 UTC, kunstmusik commented on lib/turbo/utils/utils.dart
> +String convertARToLiteralString(BigInt ar) {
Using substring looks a little awkward, may need rework (from Slack huddle discussion)

2023-10-25 20:14 UTC, kunstmusik commented on lib/turbo/utils/utils.dart
> +String convertARToLiteralString(BigInt ar) {
rename to convertWinstonToARLiteralString and rename ar argument to winston

2023-10-25 20:17 UTC, kunstmusik commented on packages/ardrive_uploader/lib/src/ardrive_uploader.dart
> +    arweave ??= Arweave();
Make non-optional and remove default

2023-10-25 20:26 UTC, kunstmusik commented on packages/pst/lib/src/ardrive_contract_oracle.dart
> +          reason: 'Max retry attempts reached',
Needs a better reason due to the code change

2023-10-25 20:28 UTC, kunstmusik commented on packages/pst/lib/src/ardrive_contract_oracle.dart
> +      return contract;
Need to check if contract is empty (i.e., no results). Could add call to fallback contract oracle here, so that try/catch can catch any errors that might happen with it.

2023-10-25 20:33 UTC, kunstmusik commented on packages/pst/lib/src/ardrive_contract_oracle.dart
> +      return _fallbackContractOracle!.getCommunityContract();
Maybe use _getContractWithRetries with the fallbackContractOracle

2023-10-25 20:38 UTC, kunstmusik commented on packages/pst/lib/src/pst.dart
> +    _communityTip = CommunityTip(
We should not cache PST holder, but can cache PST fee

2023-10-25 20:41 UTC, kunstmusik commented on packages/pst/lib/src/pst.dart
> +    _communityTip = CommunityTip(
We can cache the list of holders and then recalculate for random holder each time.

2023-10-26 00:29 UTC, thiagocarvalhodev commented on lib/turbo/utils/utils.dart
> +String convertARToLiteralString(BigInt ar) {
@kunstmusik , in the end, the wonky balance was due to a difference in the price of the upload adding the fee, and the upload not using the fee. So, I just changed the method name. 65c607da153f721c84d7c401574aaca3b0a88e4e

2023-10-26 00:29 UTC, thiagocarvalhodev commented on packages/ardrive_uploader/lib/src/ardrive_uploader.dart
> +    arweave ??= Arweave();
a1cbb70da5acc4d000a9844765abbdb8cbce8525

2023-10-26 00:29 UTC, thiagocarvalhodev commented on packages/pst/lib/src/ardrive_contract_oracle.dart
> +          reason: 'Max retry attempts reached',
a1cbb70da5acc4d000a9844765abbdb8cbce8525

2023-10-26 00:31 UTC, thiagocarvalhodev commented on packages/pst/lib/src/ardrive_contract_oracle.dart
> +      return contract;
a2902134301050c13b3bc0adbe4537eb9525591c

2023-10-26 00:31 UTC, thiagocarvalhodev commented on packages/pst/lib/src/ardrive_contract_oracle.dart
> +      return _fallbackContractOracle!.getCommunityContract();
a1cbb70da5acc4d000a9844765abbdb8cbce8525

2023-10-26 00:31 UTC, thiagocarvalhodev commented on packages/pst/lib/src/pst.dart
> +    _communityTip = CommunityTip(
a1cbb70da5acc4d000a9844765abbdb8cbce8525

2023-10-26 14:24 UTC, kunstmusik requested changes

2023-10-26 14:24 UTC, kunstmusik commented on packages/pst/lib/src/ardrive_contract_oracle.dart
> +      return _getContractWithRetries(_fallbackContractOracle!);
Could the fallback oracle throw an exception?

2023-10-26 14:24 UTC, kunstmusik commented on packages/pst/lib/src/community_oracle.dart
> +        contractData.settings.fee / 100;
Suggest to divide by 100.0 to force a double division, since fee is defined as num and could be an integer.

2023-10-26 14:26 UTC, thiagocarvalhodev commented on packages/pst/lib/src/ardrive_contract_oracle.dart
> +      return _getContractWithRetries(_fallbackContractOracle!);
Yes. If so, the client should handle it properly.

2023-10-26 14:27 UTC, thiagocarvalhodev commented on packages/pst/lib/src/community_oracle.dart
> +        contractData.settings.fee / 100;
I agree. 1b4f08080e04c6fde007187c5d5425ae72e94b69

2023-10-26 14:56 UTC, kunstmusik commented on packages/ardrive_uploader/lib/src/ardrive_uploader.dart
> +    arweave ??= Arweave();
Does not look addressed as ArDriveUploader still has optional args

2023-10-26 15:27 UTC, kunstmusik approved these changes

2023-10-26 16:29 UTC, merged