PE-4709: Image preview on Shared File Page
ardriveapp/ardrive-web pull request #1444
Opened 2023-10-25 19:15 UTC by matibat

2023-10-31 12:59 UTC, thiagocarvalhodev requested changes

2023-10-31 12:59 UTC, thiagocarvalhodev commented on lib/pages/drive_detail/components/fs_entry_preview_widget.dart
> +    return widget.contentType
You can use a helper method from `ardrive_io`:  `getFileExtension`

2023-11-01 17:50 UTC, matibat commented on lib/pages/drive_detail/components/fs_entry_preview_widget.dart
> +    return widget.contentType
If I upload my PNG image (`application/png`) named `image.png.txt` it would return TXT instead of PNG.

2023-11-01 17:54 UTC, matibat commented on lib/pages/drive_detail/components/fs_entry_preview_widget.dart
> +    return widget.contentType
Perhaps I can rename the method to "_getFileExtensionFromContentType"

2023-11-01 18:00 UTC, thiagocarvalhodev commented on lib/pages/drive_detail/components/fs_entry_preview_widget.dart
> +    return widget.contentType
That's a good point. We must rename the `getFileExtension` on `ardrive_ui` for something like: `getFileExtensionFromPath` and we probably want a new method for getting the extension based on content type.

2023-11-01 18:01 UTC, thiagocarvalhodev approved these changes
LGTM. We will update the `ardrive_io` helper method in another ticket.

2023-11-01 18:26 UTC, thiagocarvalhodev approved these changes

2023-11-02 19:02 UTC, merged