PE-4875: Image Preview In-App
ardriveapp/ardrive-web pull request #1465
Opened 2023-11-03 14:58 UTC by matibat

2023-11-06 13:19 UTC, thiagocarvalhodev requested changes
@matibat , I think it's a good opportunity to implement the methods I mentioned in the comments at the `ardrive_io` code base.

2023-11-07 18:59 UTC, matibat commented
Let's see here, @thiagocarvalhodev - https://github.com/ardriveapp/ardrive-web/pull/1470

2023-11-07 19:39 UTC, thiagocarvalhodev approved these changes
LGTM

2023-11-21 17:36 UTC, thiagocarvalhodev approved these changes

2023-11-21 17:36 UTC, merged