Task/296 attach arconnect session to wallet address
ardriveapp/ardrive-web pull request #147
Opened 2021-05-27 17:41 UTC by jdaev

Shows a log out dialog when wallet is switched with arconnect.

2021-06-25 16:51 UTC, fedellen commented on README.md
> +## Setting up the Development Environment
Assuming the merge direction listed in the header is correct, I think we need branch `feat/224-Connect-with-ARConnect` to reintegrate with dev to get these changes out of the diff here

2021-06-25 18:08 UTC, arielmelendez commented on lib/app_shell.dart
> +  bool _showWalletSwitchDialog = true;
Is the intent for this to only happen 1 time? If so, you might want to add a comment about that in the area where it's used below.

2021-06-25 18:09 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +    await _db.transaction(() async {
Should any of this cleanup take place up above in the other ProfilePromptAdd scenarios?

2021-06-25 18:15 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
>      if (profile != null) {
Consider emitting ProfilePromptAdd and an early return if profile is null and getting rid of the indentation.

2021-06-25 20:12 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +      print(e);
Are there any risks of leaking info to the logs that could be used by malicious actors? I'm looking into Application Performance Monitoring tools for us to use where we can pipe errors like this for aggregated analysis.

2021-06-25 22:23 UTC, arielmelendez commented on lib/components/wallet_switch_dialog.dart
> +                print(fromAuthPage);
Clean up unnecessary print

2021-06-25 22:40 UTC, arielmelendez commented on lib/components/wallet_switch_dialog.dart
> +  final bool fromAuthPage;
Member variable should have a leading underscore.

2021-06-25 22:44 UTC, arielmelendez commented on lib/pages/app_router_delegate.dart
> +            signingIn = true;
Don't necessarily have to clean this up here, but all the members in this class should have leading underscores.

2021-06-25 22:45 UTC, arielmelendez commented on lib/pages/profile_auth/components/profile_auth_add_screen.dart
> +                            ? Text('LOG OUT')
Do the mocks have "LOG OUT" in all caps?

2021-06-25 22:53 UTC, arielmelendez commented on lib/pages/profile_auth/components/profile_auth_fail_screen.dart
> +              child: Text('Login'),
'Login' is a noun, as in the process of logging in. 'Log In' is a call to action. Which do we want here?

2021-06-25 22:57 UTC, arielmelendez commented on lib/pages/profile_auth/components/profile_auth_unlock_screen.dart
> +            } else {
`else` is redundant. Save an indentation.

2021-06-25 23:03 UTC, arielmelendez commented on lib/pages/profile_auth/profile_auth_page.dart
> +  bool _showWalletSwitchDialog = true;
Same comment here about leaving a note about how this is used.

2021-06-25 23:11 UTC, arielmelendez requested changes
Left a handful of comments and questions. Thanks!

2021-06-28 11:23 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +      print(e);
I don't think so. Not from here at least, this one who just print out dart-js interop errors.

2021-06-28 11:28 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +    await _db.transaction(() async {
No. The cleanup already happens in the other cases as it is in the logout function. It was added here only for unexpected cases.

2021-06-28 11:30 UTC, jdaev commented on lib/components/wallet_switch_dialog.dart
> +  final bool fromAuthPage;
Not here. The convention is different for arguments that are used as a named parameter in the class.

2021-06-28 11:31 UTC, jdaev commented on lib/pages/app_router_delegate.dart
> +            signingIn = true;
Again no, those are named parameters. Can't use underscores here.

2021-06-28 11:32 UTC, jdaev commented on lib/pages/profile_auth/components/profile_auth_add_screen.dart
> +                            ? Text('LOG OUT')
Mocks?

2021-06-28 11:35 UTC, jdaev commented on lib/pages/profile_auth/profile_auth_page.dart
> +  bool _showWalletSwitchDialog = true;
[Added](https://github.com/ardriveapp/ardrive-web/pull/147/commits/85cf9fa36cfb1d372d82ba474e703560c1dec477)

2021-06-28 11:35 UTC, jdaev commented on lib/pages/profile_auth/components/profile_auth_fail_screen.dart
> +              child: Text('Login'),
Changed to "Log In" [here](https://github.com/ardriveapp/ardrive-web/pull/147/commits/85cf9fa36cfb1d372d82ba474e703560c1dec477)

2021-06-28 11:35 UTC, jdaev commented on lib/components/wallet_switch_dialog.dart
> +                print(fromAuthPage);
[Added](https://github.com/ardriveapp/ardrive-web/pull/147/commits/85cf9fa36cfb1d372d82ba474e703560c1dec477)

2021-06-28 11:36 UTC, jdaev commented on lib/app_shell.dart
> +  bool _showWalletSwitchDialog = true;
[Added](https://github.com/ardriveapp/ardrive-web/pull/147/commits/85cf9fa36cfb1d372d82ba474e703560c1dec477)

2021-06-28 11:42 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
>      if (profile != null) {
[Added](https://github.com/ardriveapp/ardrive-web/pull/147/commits/21873aa2ce87fe269b2f842e47ecd6aaa147c779)

2021-06-29 05:36 UTC, arielmelendez commented on lib/pages/profile_auth/components/profile_auth_add_screen.dart
> +                            ? Text('LOG OUT')
Design mock ups from Sketch, etc.

2021-06-29 05:46 UTC, arielmelendez commented on lib/models/tables/profiles.moor
> +    profileType INTEGER NOT NULL
nit: missing newline at end of file

2021-06-29 05:48 UTC, arielmelendez approved these changes

2021-06-29 17:45 UTC, merged