Task/rm 313 add wallet check to profile cubit
ardriveapp/ardrive-web pull request #155
Opened 2021-06-16 17:55 UTC by jdaev

Adds a wallet check function to profile cubit that checks if the wallet public key has changed.
`Future<void> checkForWalletMismatch() async {
    final profile = await _profileDao.defaultProfile().getSingleOrNull();

    if (profile.isArConnect == 1) {
      final currentPublicKey = await arconnect.getPublicKey();
      final savedPublicKey =
          (await _db.profileDao.defaultProfile().getSingleOrNull())
              .walletPublicKey;
      if (currentPublicKey != savedPublicKey) {
        await logoutProfile();
      }
    }
  }`

This function is called before each transaction in the app, like so 
`    await _profileCubit.checkForWalletMismatch();
`

It has been added to UploadCubit, SyncCubit, FsEntryRenameCubit, FsEntryMoveCubit, FolderCreateCubit, DriveRenameCubit, and DriveCreateCubit. 

A different approach was tried and tested on this [branch](https://github.com/ardriveapp/ardrive-web/tree/task/RM-313-Check-Wallet-before-Transactions), but wasn't used because this is less verbose.

2021-06-17 18:55 UTC, arielmelendez commented on lib/blocs/drive_create/drive_create_cubit.dart
> +    unawaited(_profileCubit.checkForWalletMismatch());
This does the following asynchronously:
- Gets the default profile
- Check the arconnect wallet state if necessary
- Gets the default wallet from the DB to get props from it
- Compares that to local state in the profile cubit
- May optionally kick off a profile logout which: disconnects arconnect -> emits new state -> deletes tables from the db -> prompts to authenticate

It then goes on to make various other state changes to the cubit synchronously. That means there's race conditions here, at a minimum, for the state management of this cubit. There's lots of other awaited activity on shared objects down below as well (read: likely more race conditions in the overall system).

When can't we await here?

2021-06-17 18:56 UTC, arielmelendez requested changes
See my comment about race conditions.

2021-06-17 18:58 UTC, arielmelendez commented on lib/blocs/drive_rename/drive_rename_cubit.dart
> +      await _profileCubit.checkForWalletMismatch();
Do we have any kind of wait cursors or anything that we can throw up to gate user inputs when we're making these blocking calls?

2021-06-18 10:03 UTC, jdaev commented on lib/blocs/drive_create/drive_create_cubit.dart
> +    unawaited(_profileCubit.checkForWalletMismatch());
That was an oversight on my part. Thank you for catching that.

2021-06-18 10:05 UTC, jdaev commented on lib/blocs/drive_rename/drive_rename_cubit.dart
> +      await _profileCubit.checkForWalletMismatch();
As of now, no.

2021-06-21 17:54 UTC, arielmelendez commented on lib/blocs/fs_entry_move/fs_entry_move_state.dart
> +  FolderEntryMoveWalletMismatch() : super(isMovingFolder: false);
As discussed, this should be "true" even though we're not using it.

2021-06-21 17:54 UTC, arielmelendez commented on lib/blocs/fs_entry_rename/fs_entry_rename_state.dart
> +  FolderEntryRenameWalletMismatch() : super(isRenamingFolder: false);
As discussed, this should be "true" even though we don't use the value.

2021-06-21 17:56 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +  Future<bool> checkForWalletMismatch() async {
As discussed, rename to `logoutIfWalletMismatch`. Also add a docblock above to explain the cases in which this might happen AND what the return value means.

2021-06-21 21:23 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +  /// Returns true if there has been a wallet change, or permissions change on another tab.
Consider:
`  /// Returns true if a logout flow is initiated as a result of a detected wallet or permissions change
`
It highlights that a logout flow takes place, the reasons why, and the meaning of the return value.

2021-06-21 21:25 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +    if (profile != null && profile.profileType == ProfileType.ArConnect.index) {
Should we force a logout flow if the profile is missing for some reason?

2021-06-21 21:34 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +              .walletPublicKey;
This could NPE if getSingleOrNull returns null, yes?

2021-06-21 21:55 UTC, arielmelendez commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +            form
Is this copy-pasta?

2021-06-21 21:57 UTC, arielmelendez commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +          final privateDrive = await _arweave.getLatestDriveEntityWithId(
In the case of a correct password, is this guaranteed to return a drive (e.g. in the case of a brand new user)?

2021-06-21 22:07 UTC, arielmelendez commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
>      try {
There's a lot going on down below. Can you please add some comments to guide the reader through what they're about to consume and/or wrap some of what it's doing in other functions with sensible function names?

2021-06-21 22:07 UTC, arielmelendez requested changes
See my comments above for requested changes.

2021-06-22 10:23 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +    if (profile != null && profile.profileType == ProfileType.ArConnect.index) {
Can't think of any reason to. If the profile is missing it means that they aren't logged in in the first place.

2021-06-22 10:26 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +              .walletPublicKey;
If the profile is null, which is checked before this. I don't know why I'm not using that same profile variable here, but have changed it now.

2021-06-22 10:27 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +  Future<bool> checkForWalletMismatch() async {
Added

2021-06-22 10:27 UTC, jdaev commented on lib/blocs/fs_entry_rename/fs_entry_rename_state.dart
> +  FolderEntryRenameWalletMismatch() : super(isRenamingFolder: false);
Fixed

2021-06-22 10:27 UTC, jdaev commented on lib/blocs/fs_entry_move/fs_entry_move_state.dart
> +  FolderEntryMoveWalletMismatch() : super(isMovingFolder: false);
Fixed

2021-06-22 10:28 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +  /// Returns true if there has been a wallet change, or permissions change on another tab.
Changed it to /// Returns true if a logout flow is initiated as a result of a detected wallet or permissions change

2021-06-22 10:30 UTC, jdaev commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +            form
What do you mean? It's the same process that's used for login.

2021-06-22 10:30 UTC, jdaev commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +          final privateDrive = await _arweave.getLatestDriveEntityWithId(
As long as the user has a private drive.

2021-06-22 10:36 UTC, jdaev commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
>      try {
Done. Added comments

2021-06-22 15:59 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +    if (profile != null && profile.profileType == ProfileType.ArConnect.index) {
Since the use case for this function is to log people out during an authenticated request if anything looks fishy, I think we need to log them out in the case of a missing profile object.

2021-06-22 16:51 UTC, jdaev commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
>      try {
Simplified it [here](https://github.com/ardriveapp/ardrive-web/pull/155/commits/89b9cd7f034a5d2984117323f04a8e2845cc5dab)

2021-06-22 16:56 UTC, arielmelendez commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +      _driveTxs = await _arweave.getUniqueUserDriveEntityTxs(await profile.id);
Can we please wrap this functionality (retrieving private drives) in a function that lives in a Business Logic class? e.g. we can create an ArDriveBLL class which takes an ArweaveService as a dependency. It could have a function like `getPrivateDrivesForUserId`.

2021-06-22 16:59 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +    if (profile != null && profile.profileType == ProfileType.ArConnect.index) {
Added [here ](https://github.com/ardriveapp/ardrive-web/pull/155/commits/ee4a4abeb3502188d2478bf8eda0044637f10c37)

2021-06-22 17:00 UTC, jdaev commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +      _driveTxs = await _arweave.getUniqueUserDriveEntityTxs(await profile.id);
I agree, but I believe it would be better in another PR. We could look though the code to find such functions and abstract all of them instead of just doing it here for this case.

2021-06-22 17:11 UTC, jdaev commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +            form
Fixed [here](https://github.com/ardriveapp/ardrive-web/pull/155/commits/345df129e1a9c599816d0c2d5a7f6ad07e9cbb88)

2021-06-22 19:48 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +    } else {
Wouldn't this always log out non-arconnect wallets? I don't think that's what we want...

2021-06-22 20:46 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +    } else {
Also, are there any considerations we should make for non-arconnect wallets here?

2021-06-22 20:47 UTC, arielmelendez commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +      _driveTxs = await _arweave.getUniqueUserDriveEntityTxs(await profile.id);
Please apply the patch we worked on together today. Thanks!

2021-06-23 11:03 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +    } else {
No. Only way to change json wallets is to log out, so it doesn't matter.

2021-06-23 11:05 UTC, jdaev commented on lib/blocs/profile/profile_cubit.dart
> +    } else {
Fixed [here ](https://github.com/ardriveapp/ardrive-web/pull/155/commits/c4cad29f3b6c2de7d1f088f4f7869410d118d486)

2021-06-23 11:06 UTC, jdaev commented on lib/blocs/profile_unlock/profile_unlock_cubit.dart
> +      _driveTxs = await _arweave.getUniqueUserDriveEntityTxs(await profile.id);
Added [here](https://github.com/ardriveapp/ardrive-web/pull/155/commits/547f4420e76919b8603d31c4d4b60cfc65b554a0)

2021-06-23 15:28 UTC, arielmelendez approved these changes

2021-06-29 17:44 UTC, merged