Pe 20/move string literals to resource file
ardriveapp/ardrive-web pull request #162
Opened 2021-06-28 13:13 UTC by jdaev

Sets up flutter localization and adds the string literals to arb files.

2021-07-08 17:02 UTC, fedellen submitted a review, later dismissed
Looks good and simple enough 👍

My only minor question is if we could make the usage slightly less verbose since we might be using it all over the place to localize in both the web app and mobile app. Is it possible with flutter/dart to shorten it from `AppLocalizations.of(context).myTextVariable` to something like a `localizedText(myTextVariable)` which handles the context in the background?

2021-07-09 05:13 UTC, arielmelendez commented on lib/main.dart
> +              const Locale('es', ''), // Spanish, no country code
Should we have 'es' here if we don't yet have translations for it?

2021-07-09 05:13 UTC, arielmelendez commented on lib/l10n/app_en.arb
> +
rogue whitespace

2021-07-09 05:14 UTC, arielmelendez commented on lib/l10n/app_en.arb
> +{
This file is a great start. Where did you source all the strings from?

2021-07-09 05:15 UTC, arielmelendez commented on lib/main.dart
> +              const Locale('es', ''), // Spanish, no country code
I see now that we have the single translation for welcomeBack in an 'es' file. As long as everything falls back to 'en' in the absence of 'es' we should be fine.

2021-07-09 05:17 UTC, arielmelendez commented on lib/main.dart
> +              const Locale('es', ''), // Spanish, no country code
I confirmed for myself:
"The MaterialApp supportedLocales parameter limits locale changes. When the user changes the locale setting on their device, the app’s Localizations widget only follows suit if the new locale is a member of this list. If an exact match for the device locale isn’t found, then the first supported locale with a matching languageCode is used. If that fails, then the first element of the supportedLocales list is used."

Source: https://flutter.dev/docs/development/accessibility-and-localization/internationalization#specifying-the-apps-supportedlocales-parameter

2021-07-09 05:19 UTC, arielmelendez submitted a review, later dismissed
Approved with nit suggestions.

2021-07-09 14:37 UTC, jdaev commented on lib/l10n/app_en.arb
> +{
I just did a search for all Text widgets and added the strings one by one.

2021-07-09 14:52 UTC, jdaev commented on lib/l10n/app_en.arb
> +
[Fixed](https://github.com/ardriveapp/ardrive-web/pull/162/commits/42a0a114e0e71b5a745dd3c549067508f5e2fdeb)

2021-07-09 15:16 UTC, arielmelendez approved these changes
LGTM

2021-07-10 22:32 UTC, agsuy requested changes
Please change the Spanish sample with the text I just provided.

2021-07-10 22:32 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "welcomeBack": "Bienvenido de nuevo"
"welcomeBack": "Bienvenido de nuevo" should be "welcomeBack": "Bienvenido nuevamente"

2021-07-12 16:58 UTC, agsuy approved these changes

2021-07-12 17:15 UTC, arielmelendez approved these changes
LGTM

2021-07-12 22:22 UTC, merged