PE-5690: feat(ANS-105)
ardriveapp/ardrive-web pull request #1637
Opened 2024-02-22 18:37 UTC by thiagocarvalhodev

- Adds new cc license types:
  - CC-BY
  - CC-BY-NC
  - CC-BY-NC-ND
  - CC-BY-NC-SA 
  - CC-BY-ND
  - CC-BY-SA 
- Adds the LicenseCategory enum to differentiate cc and udl licenses.

2024-02-23 18:11 UTC, kunstmusik commented on lib/blocs/fs_entry_license/fs_entry_license_bloc.dart
>          if (event is FsEntryLicenseReviewBack) {
Odd that this file has separated if- checks for event type vs. else-if's or switch.

2024-02-23 18:13 UTC, karlprieb submitted a review, later dismissed

2024-02-26 13:42 UTC, karlprieb submitted a review, later dismissed

2024-02-27 15:04 UTC, kunstmusik requested changes

2024-02-27 15:04 UTC, kunstmusik commented on lib/components/fs_entry_license_form.dart
> +                  title: 'Configure Creative Commons License',
This shows incorrect information when UDL is selected as it hardcodes the title.

2024-02-27 15:10 UTC, thiagocarvalhodev commented on lib/components/fs_entry_license_form.dart
> +                  title: 'Configure Creative Commons License',
https://github.com/ardriveapp/ardrive-web/pull/1637/commits/b41e51ed208a08f9cc2fc5a56d235e5e6b86e1a9

2024-02-27 15:22 UTC, kunstmusik approved these changes

2024-02-27 16:44 UTC, merged