PE-45/Warn about user switching focus
ardriveapp/ardrive-web pull request #164
Opened 2021-07-02 17:03 UTC by jdaev

Shows appropriate warning message based on wallet type.

2021-07-02 17:11 UTC, arielmelendez commented on lib/app_shell.dart
> +                                      title: 'Syncing, please wait',
Let's make the prompts consistent (I know this isn't in the requirements, but it should be). Let's make the copy here:
"Syncing... Please wait."

2021-07-02 17:12 UTC, arielmelendez commented on lib/pages/profile_auth/components/profile_auth_loading_screen.dart
> +                  'Loading, please remain on this tab.',
The copy from the requirements is:
"Loading... Please remain on this tab."

2021-07-02 17:14 UTC, arielmelendez requested changes
A few copy updates need to be made.

2021-07-02 17:15 UTC, jdaev commented on lib/pages/profile_auth/components/profile_auth_loading_screen.dart
> +                  'Loading, please remain on this tab.',
[Corrected ](https://github.com/ardriveapp/ardrive-web/pull/164/commits/c9297c9d6e118e2983c398d49b53c35aff59a624)

2021-07-02 17:15 UTC, jdaev commented on lib/app_shell.dart
> +                                      title: 'Syncing, please wait',
[Corrected ](https://github.com/ardriveapp/ardrive-web/pull/164/commits/c9297c9d6e118e2983c398d49b53c35aff59a624)

2021-07-02 17:28 UTC, arielmelendez approved these changes

2021-07-02 19:21 UTC, agsuy commented
Wondering if we could reuse isCurrentProfileArConnect() somewhere as I am not sure where/how we are checking for ArConnect presence on the app (any doc on this?). Besides this I would start testing this right away.

2021-07-02 19:21 UTC, arielmelendez submitted a review, later dismissed

2021-07-06 15:38 UTC, arielmelendez submitted a review, later dismissed

2021-07-06 18:16 UTC, agsuy approved these changes
We now emit syncs to console.

Approved.

2021-07-06 18:17 UTC, merged