add tests job to github actions and repair tests PE-110
ardriveapp/ardrive-web pull request #225
Opened 2021-10-06 15:16 UTC by jdaev

Adds tests job to github actions (PE-110). Also fixes the existing tests (PE-523)

2021-10-06 17:58 UTC, agsuy commented
Can not merge this until we fix Flutter Tests

2021-11-15 18:30 UTC, jdaev commented
PE-523 should have been a different PR. My mistake. If necessary I can separate these.

2021-11-16 08:18 UTC, arielmelendez commented on lib/services/crypto/keys.dart
> +    // This was an empty Uint8List(0), but due to the deferring implmentations of web crypto and dart-vm
Are the keys derived this way compatible with those derived from past and current versions of the CLI? I would be very surprised if so.

2021-11-16 08:23 UTC, arielmelendez commented on test/blocs/drive_create_cubit_test.dart
> +    const testGatewayURL = 'https://arweave.net';
Does this need to connect to a real arweave gateway? Can these tests run without a network connection?

2021-11-16 08:24 UTC, arielmelendez commented on test/blocs/drive_create_cubit_test.dart
> +          walletBalance: BigInt.from(20000000),
Was this required because you started actually hitting the arweave network during tests (which we should not)?

2021-11-16 08:25 UTC, arielmelendez commented on test/utils/mocks.dart
> +  String get username => 'Test';
You might want to make these different values to reduce the chance of accidentally using them in the wrong spot and getting a false positive.

2021-11-16 08:27 UTC, arielmelendez requested changes
Generally looks ok. Just please answer the few questions I posed and consider the updates I suggested. Thanks.

2021-11-16 12:46 UTC, jdaev commented on lib/services/crypto/keys.dart
> +    // This was an empty Uint8List(0), but due to the deferring implmentations of web crypto and dart-vm
Yes, it's compatible tested it myself with private drives and files. However this is also the same nonce used in mine and Almog's mobile versions. Phil has confirmed it works fine on them.

2021-11-16 12:48 UTC, jdaev commented on test/blocs/drive_create_cubit_test.dart
> +          walletBalance: BigInt.from(20000000),
Yeah, it does. How should I change it? Add a dry run parameter?

2021-11-17 15:02 UTC, jdaev commented on test/blocs/drive_create_cubit_test.dart
> +          walletBalance: BigInt.from(20000000),
Actually, it wasn't required due to it hitting the network, but to get around the minimum balance limit we added before.

2021-11-30 16:08 UTC, jdaev commented on test/blocs/drive_create_cubit_test.dart
> +    const testGatewayURL = 'https://arweave.net';
It does. Fails without a network connection

2021-11-30 17:15 UTC, arielmelendez commented on test/blocs/drive_create_cubit_test.dart
> +    const testGatewayURL = 'https://arweave.net';
That's tech debt we should track for future cleanup. Our tests shouldn't rely on a live network connection.

2021-11-30 17:16 UTC, arielmelendez approved these changes

2021-12-03 12:27 UTC, matibat commented on test/blocs/drive_create_cubit_test.dart
> +    const testGatewayURL = 'https://arweave.net';
I'm not sure about the implementation, but I'd say we can accomplish this by mocking Arweave -the one that takes the gatewayUrl param-

2021-12-03 12:31 UTC, matibat commented on test/models/daos/drive_dao_test.dart
>          expectLater(folderStream.map((f) => f.folder!.id), emits(rootFolderId)),
Unrelated to the introduced changes, but: are we sure `f.folder` is not null?

2021-12-03 12:33 UTC, matibat reviewed
Left one question & one comment

2021-12-07 15:00 UTC, jdaev commented on test/models/daos/drive_dao_test.dart
>          expectLater(folderStream.map((f) => f.folder!.id), emits(rootFolderId)),
Yes, folders must have an id. It's nullable because it derived from nullable tags.

2021-12-07 16:35 UTC, jdaev commented
Going to close this.
Split into https://github.com/ardriveapp/ardrive-web/pull/289 and https://github.com/ardriveapp/ardrive-web/pull/290

2021-12-13 22:33 UTC, closed without merging