feature: csv export of file data for a drive
ardriveapp/ardrive-web pull request #262
Opened 2021-11-07 20:47 UTC by jdaev

Exports the latest revisions of all filescontained in a drive as a csv. Simply open the drive in the web app andclick on the table icon next to the rename icon.

2021-11-09 07:30 UTC, arielmelendez commented on lib/pages/drive_detail/drive_detail_page.dart
> +import 'package:ardrive/components/csv_export_dialog.dart';
Why is this needed here?

2021-11-09 11:12 UTC, jdaev commented on lib/pages/drive_detail/drive_detail_page.dart
> +import 'package:ardrive/components/csv_export_dialog.dart';
The file that calls the dialog is a part of this file, so the import statement goes here.

2021-11-10 23:42 UTC, arielmelendez requested changes

2021-11-11 13:52 UTC, jdaev commented on lib/models/queries/drive_queries.moor
> +filesInDriveithRevisionTransactions ($order = '') AS FileWithLatestRevisionTransactions:
[Fixed](https://github.com/ardriveapp/ardrive-web/pull/262/commits/4e1c3fefa53787ffd52a6b0014858fad500d5e4e)

2021-11-17 07:42 UTC, arielmelendez commented on test/snapshots/data_export_snapshot.dart
> +const String dataExportSnapshot =
FYI there's a package mimicking Jest's snapshot testing capabilities for Flutter UIs calls `Fest`: https://pub.dev/documentation/fest/latest/
We can't use it here in the way that you can in Jest for non-UI components, but I thought you'd find it interesting.

2021-11-17 07:44 UTC, arielmelendez commented on lib/blocs/data_export/data_export_cubit.dart
> +    return const ListToCsvConverter().convert(export);
This is a great first pass at this feature. Any idea how well it scales?

2021-11-17 07:44 UTC, arielmelendez approved these changes

2021-11-17 13:53 UTC, jdaev commented on lib/blocs/data_export/data_export_cubit.dart
> +    return const ListToCsvConverter().convert(export);
Well, it'll get slower the more files and folders there are, but still less than the time it takes to sync such a drive. I can improve it by adding multi-threading, but that's overkill at this point. A better improvement would be to add the exports to folders as well.

2021-11-22 15:24 UTC, agsuy approved these changes
Supports own and attached drives

2021-11-22 15:24 UTC, merged