Test/PE 572 multifile bundle tests
ardriveapp/ardrive-web pull request #293
Opened 2021-12-13 20:06 UTC by jdaev

Adds tests for multi file bundles

Currently covered:

- Bundle packer

2021-12-14 17:53 UTC, fedellen commented
You've got an unresolved conflict with a test file here

2021-12-15 11:41 UTC, matibat requested changes
Left a couple of minor comments.
Requesting changes as the branch has conflicts with its base

2021-12-15 11:41 UTC, matibat commented on test/utils/bundle_packer_test.dart
> +      test('Creates a new bundle when next item does not fit', () async {
Missing new line
```suggestion

      test('Creates a new bundle when next item does not fit', () async {
```

2021-12-15 11:41 UTC, matibat commented on test/utils/bundle_packer_test.dart
> +      test('Creates a single bundle of max size for one max size item',
Missing new line
```suggestion

      test('Creates a single bundle of max size for one max size item',
```

2021-12-15 13:46 UTC, matibat approved these changes
LGTM

2021-12-15 15:43 UTC, merged