feat(ui): add table pagination PE-847
ardriveapp/ardrive-web pull request #303
Opened 2021-12-28 18:41 UTC by jdaev

2022-01-18 15:42 UTC, matibat reviewed
Nice changes overall! I left a couple of comments

2022-01-18 15:42 UTC, matibat commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +          : index - folders.length];
Given that at this point `index >= folders.length`, is there any issue by doing the following?
```suggestion
      int fileIndex = index - folders.length;
      final file = files[fileIndex];
```

2022-01-18 15:42 UTC, matibat commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +  });
Q: Is it possible to organize this data in an interface instead of a class?

2022-01-18 15:43 UTC, matibat commented
Also, would you take care of the merging conflicts with the base branch?

2022-01-18 22:57 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +              currentFolder.files.length + currentFolder.subfolders.length;
Why isn't the linter warning about potentially uninitialized access here? `currentFolder` could be null if `folderContents.folder` is null. I'd avoid `var` without a type and uninitialized variables like the plague if possible.

2022-01-18 22:59 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +              currentFolder.files.length + currentFolder.subfolders.length;
Using the type explicitly seems to get the static analyzer/compiler wise to the situation:
![image](https://user-images.githubusercontent.com/7692385/150032306-722bd6cb-7111-4931-9c5f-9bbc7da44e90.png)

2022-01-18 23:01 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +          var currentFolder;
I'd like to see as much of this region of code rewritten as a pure input/output, unit-testable/tested function as possible.

2022-01-18 23:03 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +          var currentFolder;
Seems like:
inputs = item count, default rows per page
outputs = rowsPerPage, availableRowsPerPage

2022-01-18 23:03 UTC, jdaev commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +  });
Yeah, it's a constructor.
I could add an interface that abstracts away what's common with files and folders but I don't think it's really necessary, since files and folders are the only things we have.

2022-01-18 23:10 UTC, jdaev commented on lib/pages/drive_detail/components/custom_paginated_data_table.dart
> +      //row ??= _getBlankRowFor(index);
[Removed](https://github.com/ardriveapp/ardrive-web/pull/303/commits/07a20d6e791cec419b4edf45b9a19260948f0e7d)

2022-01-18 23:19 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +    final state = this.state is DriveDetailLoadSuccess
Saves you one line of code and a few branches:
```
    switch (state.runtimeType) {
      case DriveDetailLoadSuccess:
        final state = this.state as DriveDetailLoadSuccess;
        emit(
          state.copyWith(
            rowsPerPage: rowsPerPage,
          ),
        );
    }
```

2022-01-18 23:23 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_state.dart
> +  final int rowsPerPage;
I don't find these names meaningfully different at first glance. Either add comments explaining them, or update the names.

2022-01-18 23:24 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_state.dart
> +  final int rowsPerPage;
Maybe `rowsPerPageChoices`? I'm not sure that's less confusing than `available`. I can see the naming trickiness here.

2022-01-18 23:28 UTC, arielmelendez commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +    if (index >= (folders.length + files.length)) {
If `(folders.length + files.length)` has a special meaning, consider making an accessor for it so the reader sees something like:
```
    if (index >= totalNumEntries()) {
```

2022-01-18 23:29 UTC, arielmelendez commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +    if (index < folders.length) {
Is this really `if (isFolderIndex(index)) {`?

2022-01-18 23:29 UTC, arielmelendez commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +      final file = files[folders.length > files.length
Not super reader friendly here

2022-01-18 23:30 UTC, arielmelendez requested changes
A bit more to review but taking a break for now.

2022-01-19 14:13 UTC, jdaev commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +      final file = files[folders.length > files.length
[Updated](https://github.com/ardriveapp/ardrive-web/pull/303/commits/0185ac6325f84a2e4c31737d183a06cff4fc1d48)

2022-01-19 14:13 UTC, jdaev commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +    if (index >= (folders.length + files.length)) {
[Updated](https://github.com/ardriveapp/ardrive-web/pull/303/commits/0185ac6325f84a2e4c31737d183a06cff4fc1d48)

2022-01-19 14:13 UTC, jdaev commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +    final state = this.state is DriveDetailLoadSuccess
Thank you. [Updated](https://github.com/ardriveapp/ardrive-web/pull/303/commits/0185ac6325f84a2e4c31737d183a06cff4fc1d48)

2022-01-19 14:13 UTC, jdaev commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +              currentFolder.files.length + currentFolder.subfolders.length;
Thanks. [Updated it](https://github.com/ardriveapp/ardrive-web/pull/303/commits/0185ac6325f84a2e4c31737d183a06cff4fc1d48)

2022-01-19 16:26 UTC, jdaev commented on lib/blocs/drive_detail/drive_detail_state.dart
> +  final int rowsPerPage;
rowsPerPage and availableRowsPerPage are whats used in the default flutter widgets, which is why I went with it.

2022-01-19 16:27 UTC, jdaev commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +          var currentFolder;
[Updated](https://github.com/ardriveapp/ardrive-web/pull/303/commits/e8b5e45405d2e1845ff5311ac3099ac9f77bd6a2)

2022-01-19 21:46 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +  List<int> calculateRowsPerPage(int totalEntries) {
`calculateAvailbleRowsPerPage` might be a better name. And making it a static function rather than a member function and passing in the defaults would make it more unit testable.

2022-01-19 21:49 UTC, arielmelendez commented on lib/pages/drive_detail/components/drive_detail_data_table_source.dart
> +    if (index < folders.length) {
Then it might make sense to make that function. Your code is making a hard assumption that ordering in the list is based on folders, then files. This will break in the future if we allow users to sort differently. Then, in the future, you'd just change the logic of `isFolderIndex` to account for sort algorithm and this would "just work".

2022-01-19 22:05 UTC, arielmelendez submitted a review, later dismissed
Some missed opportunities for unit testing. Approving nonetheless.

2022-01-20 03:16 UTC, fedellen approved these changes

2022-01-21 16:10 UTC, matibat approved these changes
It looks good overall :+1:

2022-02-03 17:49 UTC, matibat submitted a review, later dismissed
LGTM

2022-02-03 20:17 UTC, arielmelendez submitted a review, later dismissed

2022-02-03 23:00 UTC, arielmelendez approved these changes

2022-02-03 23:01 UTC, merged