PE 765/Add bundledIn to files
ardriveapp/ardrive-web pull request #307
Opened 2022-01-03 17:40 UTC by jdaev

Adds a bundledIn field to file entities, file entries and file revisions.
UI now shows bundle tx id for files in the info side sheet. 
Also adds the bundled tx id to the file entity on db after the bundle is prepared and signed.

2022-01-03 17:53 UTC, matibat reviewed
Left one single comment there

2022-01-03 17:53 UTC, matibat commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                      DataRow(cells: [
Shouldn't this field be hidden when there's no bundle tx (aka non-bundled entities)?
I think it will render a row with the clipboard icon, but it will copy `null` to the clipboard

2022-01-03 18:11 UTC, jdaev commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                      DataRow(cells: [
[Corrected](https://github.com/ardriveapp/ardrive-web/pull/307/commits/e2b98885a976430df944ac047c493181001f88c5)

2022-01-03 21:45 UTC, matibat submitted a review, later dismissed
It looks good to me now

2022-01-03 22:54 UTC, arielmelendez commented on lib/blocs/upload/upload_cubit.dart
> +              .toList(),
Is toList() redundant?

2022-01-03 23:07 UTC, arielmelendez requested changes
Missing schema version update

2022-01-04 00:10 UTC, jdaev commented on lib/blocs/upload/upload_cubit.dart
> +              .toList(),
Nope. Reduce returns an Iterable which has to be converted to a List

2022-01-04 14:38 UTC, matibat submitted a review, later dismissed
Left one minor suggestion. It seems nice to go!

2022-01-04 14:38 UTC, matibat commented on lib/models/database/database.dart
> +          if (from >= 1 && from <= 10) {
If we want that number to be the previous version, then let's define a `prevSchemaVersion` so we reduce redundancy
_Please ensure the syntax I used is fine before committing, or edit in your IDE_
```suggestion
          int prevSchemaVersion = schemaVersion - 1;
          if (from >= 1 && from <= prevSchemaVersion) {
```

2022-01-04 14:38 UTC, matibat commented on lib/models/database/database.dart
> +          if (from >= 1 && from <= 10) {
We can also use the strict less-than, so it never reaches the current version
```suggestion
          if (from >= 1 && from < schemaVersion) {
```

2022-01-06 19:31 UTC, arielmelendez commented on lib/blocs/upload/upload_cubit.dart
> +              .toList(),
Hmm. When i tested locally the static analyzer/compiler didn't seem to care.

2022-01-06 19:33 UTC, arielmelendez approved these changes

2022-01-06 21:34 UTC, jdaev commented on lib/models/database/database.dart
> +          if (from >= 1 && from <= 10) {
Will add this when I finalize the db version. There's multiple PRs right now that require it.

2022-01-11 23:31 UTC, agsuy approved these changes
Merge of 766 fix

2022-01-11 23:31 UTC, merged