PE 766 Add bundled in for drives
ardriveapp/ardrive-web pull request #316
Opened 2022-01-05 18:17 UTC by jdaev

Adds a bundledIn field for drive and shows drive tx id, root folder tx id and bundle tx id in info sheet.

2022-01-05 18:33 UTC, matibat reviewed
LGTM
Left one single comment regarding the indentation

2022-01-05 18:33 UTC, matibat commented on lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
> +        final rootFolder = await _driveDao
The indentation is weird here

2022-01-05 18:44 UTC, jdaev commented on lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
> +        final rootFolder = await _driveDao
Updated

2022-01-06 10:40 UTC, matibat approved these changes

2022-01-06 19:51 UTC, arielmelendez commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                            tooltip: 'Copy Drive Tx ID',
Why is this copy changing? There were no requirements in the ticket about this?

2022-01-06 19:53 UTC, arielmelendez commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                            tooltip: 'Copy Drive Tx ID',
I think I see why -  to disambiguate Drive Metadata Tx ID from Root Folder's. But there is nothing in the ticket about the need for this change. You should align with the team about a change like this before making it. My suggestion would be to use:
```
'Copy Drive Metadata Tx ID'
and
'Copy Root Folder Metadata Tx ID'
```

2022-01-06 19:53 UTC, arielmelendez commented on lib/blocs/fs_entry_info/fs_entry_info_state.dart
> +  final Drive drive;
Is it necessary to store a direct reference if the superclass is holding the `entry`?

2022-01-06 19:54 UTC, arielmelendez commented on lib/models/tables/drive_revisions.moor
> +    bundledIn TEXT,
Do we need another schema update?

2022-01-06 19:54 UTC, arielmelendez requested changes
Some quick q's to answer.

2022-01-06 21:06 UTC, jdaev commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                            tooltip: 'Copy Drive Tx ID',
Noted. Thank you

2022-01-06 21:23 UTC, jdaev commented on lib/blocs/fs_entry_info/fs_entry_info_state.dart
> +  final Drive drive;
Yeah. We need the drive there, or override entry if we want to pass a named parameter in the constructor.

2022-01-06 21:23 UTC, jdaev commented on lib/models/tables/drive_revisions.moor
> +    bundledIn TEXT,
[Done](https://github.com/ardriveapp/ardrive-web/pull/316/commits/bb21021e4d9403259927eea861298a7a68d7129d)

2022-01-06 23:17 UTC, arielmelendez commented on lib/models/tables/drive_revisions.moor
> +    bundledIn TEXT,
If we're going to keep forgetting to do this every time, then it may be time for some build automation that throws errors if changes are detected in these files without a schema update. This has happened in basically every DB update I've seen in the past few months. And/or a PR publishing checklist, though historically I haven't seen those implemented very successfully.

2022-01-07 00:13 UTC, arielmelendez commented on lib/blocs/fs_entry_info/fs_entry_info_state.dart
> +  final Drive drive;
![image](https://user-images.githubusercontent.com/7692385/148470269-bbd93684-945a-423a-9814-ce871d7b35cb.png)
Yea this seems to build fine for me. I don't see the need for the extra storage. If we need to access a property called drive seems like we could just add a getter that returns the entry.

2022-01-07 00:17 UTC, arielmelendez approved these changes

2022-01-11 23:28 UTC, merged