Rework Uploads
ardriveapp/ardrive-web pull request #319
Opened 2022-01-11 16:44 UTC by jdaev

2022-01-19 22:47 UTC, jdaev commented on lib/blocs/upload/file_upload_handle.dart
>      return (entityTx as Transaction).reward + (dataTx as Transaction).reward;
Will fail for v2 files since entityTx is null at this point. TODO: Use size estimator here.

2022-01-19 22:48 UTC, arielmelendez requested changes
Identified in pair review that V2 txs are broken

2022-01-20 20:32 UTC, fedellen commented on lib/utils/bundles/fake_tags.dart
> +  Tag(EntityTag.appVersion, '0.0.0'),
I don't think we can assume that that this version will always have single digits. While its fine for now and the near future, we might bypass this to perhaps version `1.10.0` and not remember that this was hard coded here. Not a huge deal, it would only mean that we'd be under estimating by 1 byte

2022-01-20 20:44 UTC, fedellen commented on lib/services/arweave/arweave_service.dart
> +
This does not seem to be accurate here. I wish it were this simple, it could save us a lot of pricing requests. First off, you need to factor in the base cost (`getPrice(byteSize: 0)`) and also the cost of one chunk (`getPrice(byteSize: 1)`) to determine the cost of each subsequent chunk ( oneChunk - basePrice = eachChunk )  . 

BUT there are additional variables that we haven't been able to solve here. And when we thought we had a solution, it proved to be false and the method eventually as under-funding rewards. Unfortunately we haven't been able to nail down an algorithm here after trying a couple times in Core. 

What we've done instead is cache prices on a chunk by chunk basis. Meaning we create and cache a mapping of: `[numberOfChunk]: winstonPrice`

So before each price request, we calculate how many chunks the provided byteCount would be. If we have a cached price for that number of chunks, we skip the price request and return that price. Otherwise we fetch a new price.

This saves on repeated price checks of the same chunk value. But with web as a potentially persisting program, I think we'll need some sort of cache invalidation after time to ensure that these values don't become stale.

2022-01-20 23:39 UTC, jdaev commented on lib/services/arweave/arweave_service.dart
> +
Thanks for that. I guess the way forward is to just use the price api like before.

2022-01-27 21:16 UTC, arielmelendez approved these changes

2022-01-31 19:50 UTC, fedellen approved these changes
🚀

2022-02-08 17:40 UTC, merged