PE-913/Display folder and file counts
ardriveapp/ardrive-web pull request #330
Opened 2022-01-20 20:43 UTC by jdaev

2022-01-31 23:44 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_state.dart
> +    } else if (folderInView.folder!.id != currentDrive.rootFolderId) {
The force unwrapping is unfortunate :(

2022-01-31 23:47 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_state.dart
> +    } else if (folderInView.folder!.id != currentDrive.rootFolderId) {
It's actually unnecessary since we can return an optional String. Also I'd like for the codebase to stop referring to the ID types as strings when supplying type information. Instead, create a types file somewhere and create a typedef for each of the ID types to string, e.g.:
```
typedef FolderID = String;
```
Then this function can return a `FolderID?`.

2022-01-31 23:52 UTC, arielmelendez commented on lib/blocs/drive_detail/drive_detail_state.dart
> +  String? getCurrentFolderId() {
This needs documentation, a name change, or both. `currentFolder` has a different meaning here prior to this PR. This function is actually fetching the folderID needed for the info context. Consider: `getSelectedFolderID` and document that the default behavior is to fall back on the folderID of the folder "in view".

2022-01-31 23:56 UTC, arielmelendez commented on lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
> +          _driveDao.getFolderTree(driveId, folderId!).asStream().listen(
How do the stream behaviors of `watchSingle` and `asStream` differ?

2022-02-01 00:02 UTC, arielmelendez commented on lib/models/daos/drive_dao/folder_node.dart
> +  int getRecursiveFolderCount() {
Consider `getRecursiveSubFolderCount()` so that it's clearer that the folder itself isn't included.

2022-02-01 00:05 UTC, arielmelendez commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +  final FolderWithContents currentFolder;
Consider `currentOrSelectedFolder`, or if we don't even care about those concepts here, just `folder` or `folderWithContents`.

2022-02-01 00:07 UTC, arielmelendez commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                      '${(state as FsEntryDriveInfoSuccess).rootFolderTree.getRecursiveFileCount()} files, '
Is there no requirement to handle the singular case differently? e.g. `1 file` and `1 folder`

2022-02-01 00:07 UTC, arielmelendez commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                    '${state.entry.getRecursiveFileCount()} files, ${state.entry.getRecursiveFolderCount()} folders',
Same question as above. Also, DRY out this code with a helper function.

2022-02-01 00:11 UTC, arielmelendez commented on test/models/daos/drive_dao_test.dart
> +    test('watchFolder() with root path (' ') returns root folder', () async {
Description doesn't match test `' '` vs `''`

2022-02-01 00:12 UTC, arielmelendez commented on test/models/daos/drive_dao_test.dart
> +    test('watchFolder() with root path (' ') returns root folder', () async {
Is this actually concatenating 2 strings since you're not using `"` on the outside?

2022-02-01 00:16 UTC, arielmelendez requested changes
A few questions and suggestions. Let's circle up on test code tomorrow

2022-02-01 01:01 UTC, jdaev commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                    '${state.entry.getRecursiveFileCount()} files, ${state.entry.getRecursiveFolderCount()} folders',
[Updated](https://github.com/ardriveapp/ardrive-web/pull/330/commits/48459424b183779257cd3316ca96eb337516321f)

2022-02-01 01:01 UTC, jdaev commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +                      '${(state as FsEntryDriveInfoSuccess).rootFolderTree.getRecursiveFileCount()} files, '
It's not stated in the requirements, but my bad. I should have inferred that. [Updated](https://github.com/ardriveapp/ardrive-web/pull/330/commits/48459424b183779257cd3316ca96eb337516321f)

2022-02-01 01:02 UTC, jdaev commented on lib/pages/drive_detail/components/fs_entry_side_sheet.dart
> +  final FolderWithContents currentFolder;
Removed it since it wasn't necessary. Thanks for catching that.

2022-02-01 01:02 UTC, jdaev commented on lib/models/daos/drive_dao/folder_node.dart
> +  int getRecursiveFolderCount() {
[Done](https://github.com/ardriveapp/ardrive-web/pull/330/commits/48459424b183779257cd3316ca96eb337516321f)

2022-02-01 01:03 UTC, jdaev commented on lib/blocs/fs_entry_info/fs_entry_info_cubit.dart
> +          _driveDao.getFolderTree(driveId, folderId!).asStream().listen(
Get folder tree returns a future which when converted to a stream emits a stream event when the future completes.

2022-02-01 01:43 UTC, jdaev commented on lib/blocs/drive_detail/drive_detail_state.dart
> +    } else if (folderInView.folder!.id != currentDrive.rootFolderId) {
Done.

2022-02-01 15:31 UTC, jdaev commented on lib/blocs/drive_detail/drive_detail_state.dart
> +  String? getCurrentFolderId() {
I've refactored this to make it hopefully less weird. Please take a look here https://github.com/ardriveapp/ardrive-web/pull/339

2022-02-03 18:47 UTC, arielmelendez commented on test/models/daos/drive_dao_test.dart
> +    test('watchFolder() with root path (' ') returns root folder', () async {
You can't just use double quotes on the outside of the whole string?

2022-02-03 18:49 UTC, arielmelendez commented on lib/utils/num_to_string_parsers.dart
> +String fileAndFolderCountsToString({
Missed opportunity to unit test.

2022-02-03 18:50 UTC, arielmelendez commented on lib/entities/string_types.dart
> +typedef FolderID = String;
Nice

2022-02-03 18:51 UTC, arielmelendez commented on test/models/daos/drive_dao_test.dart
> +    test('getRecursiveFolderCount returns the correct folder count', () async {
Nit: comment is out of date now that name is `getRecursiveSubFolderCount`

2022-02-03 18:56 UTC, arielmelendez requested changes
Fix logic on string generation

2022-02-03 19:10 UTC, jdaev commented on lib/utils/num_to_string_parsers.dart
> +String fileAndFolderCountsToString({
[Added](https://github.com/ardriveapp/ardrive-web/pull/330/commits/d1720861916a20a05b846cd9337c0c0fb9ffa6c3)

2022-02-03 19:10 UTC, jdaev commented on test/models/daos/drive_dao_test.dart
> +    test('getRecursiveFolderCount returns the correct folder count', () async {
[Updated](https://github.com/ardriveapp/ardrive-web/pull/330/commits/97e506ff60943306d06701265fd02ce20462153e)

2022-02-03 19:11 UTC, jdaev commented on test/models/daos/drive_dao_test.dart
> +    test('watchFolder() with root path (' ') returns root folder', () async {
Sorry, didn't realize at first what you mean. [Updated](https://github.com/ardriveapp/ardrive-web/pull/330/commits/97e506ff60943306d06701265fd02ce20462153e)

2022-02-03 19:11 UTC, jdaev commented on lib/utils/num_to_string_parsers.dart
> +  final folderSuffix = folderCount > 1 ? 'folders' : 'folder';
[Updated](https://github.com/ardriveapp/ardrive-web/pull/330/commits/a5239f6d00b08bbe9713aa05d1f2877cdcf0bcda). Thanks for correcting that.

2022-02-03 20:11 UTC, arielmelendez commented on test/utils/num_to_string_parsers_test.dart
> +      final fileCount = Random().nextInt(9000) + 1;
This isn't super useful for this test and in fact creates more test complexity than you need. I think you need the following permutations of tests:

- (0 files, 0 folders)
- (0 files, 1 folder)
- (1 file, 0 folders)
- (1 file, 1 folder)
- (2 files, 1 folder)
- (1 file, 2 folders)
- (2 files, 2 folders)

2022-02-03 20:12 UTC, arielmelendez requested changes
Remove unnecessarily complex randoms from test and add other permutations.

2022-02-03 20:55 UTC, jdaev commented on test/utils/num_to_string_parsers_test.dart
> +      final fileCount = Random().nextInt(9000) + 1;
[Updated](https://github.com/ardriveapp/ardrive-web/pull/330/commits/bd8933b4e0e00136151e25a63f5931f8b3b9f037)

2022-02-03 21:06 UTC, arielmelendez approved these changes

2022-02-11 05:00 UTC, arielmelendez approved these changes

2022-02-11 09:03 UTC, merged