PE 910/ Pre push hook
ardriveapp/ardrive-web pull request #334
Opened 2022-01-27 18:45 UTC by jdaev

This PR uses lefthook to add a pre push hook for checking database modifications.
It compares the diff, and checks if the database folder has been modified, and then stops the push if the database version has not been updated.

2022-01-27 19:44 UTC, arielmelendez commented on README.md
> +Install lefthook for your platform from the intructions [here](https://github.com/evilmartians/lefthook/blob/master/docs/other.md).
I'd put this at the TOP of this section.

2022-01-27 19:46 UTC, arielmelendez commented on lefthook/database_checker.sh
> +    previousSchemaPattern='([-][[:space:]]* int get schemaVersion =>[[:space:]]*[[:digit:]]+)'
```suggestion
    previousSchemaPattern='([-][[:space:]]*int get schemaVersion =>[[:space:]]*[[:digit:]]+)'
```

2022-01-27 19:47 UTC, arielmelendez commented on lefthook/database_checker.sh
> +    currentSchemaPattern='([+][[:space:]]* int get schemaVersion =>[[:space:]]*[[:digit:]]+)'
```suggestion
    currentSchemaPattern='([+][[:space:]]*int get schemaVersion =>[[:space:]]*[[:digit:]]+)'
```

2022-01-27 19:55 UTC, arielmelendez commented on lefthook/database_checker.sh
> +    if [ $currentVersion -lt $previousVersion ]; then
If something goes wrong with the regex match parsing and the integer conversion doesn't go well, could we end up with something like `0 -lt 0` and get a false positive from this script?

2022-01-27 19:56 UTC, arielmelendez commented on lefthook/database_checker.sh
> +    if [ $currentVersion -lt $previousVersion ]; then
We should really throw and error if we can't get a valid new schema version because it means that the schema version getter function has changed in a way we didn't anticipate. Perhaps the code below is already catching that case?

2022-01-27 19:56 UTC, arielmelendez requested changes
I think the regexes can both have a space removed. Left suggested updates and a few questions.

2022-01-27 20:22 UTC, jdaev commented on lefthook/database_checker.sh
> +    if [ $currentVersion -lt $previousVersion ]; then
Yeah, you were correct. I added a check for it [here](https://github.com/ardriveapp/ardrive-web/pull/334/commits/232bfe628a70e078ca90c841e360d9957f66fdf1)

2022-01-27 20:47 UTC, arielmelendez submitted a review, later dismissed

2022-01-28 13:26 UTC, agsuy commented on lefthook/database_checker.sh
> +else
What are you trying to achieve here with this else?

2022-01-28 13:26 UTC, agsuy commented on lefthook.yml
> +  parallel: true
parallel with one command, while ok, takes no effect

2022-01-28 13:34 UTC, agsuy requested changes
There are some concerns that script would not run as expected.

2022-01-28 13:34 UTC, agsuy commented on lefthook/database_checker.sh
> +if [ $(git diff @{u}...HEAD ./lib/models/tables | wc -l) -eq "0" ]; then
Running this locally I get this outcome:

```
$ ./lefthook/database_checker.sh 
./lefthook/database_checker.sh: line 13: previousSchemaRegexMatch: bad array subscript
./lefthook/database_checker.sh: line 18: currentSchemaRegexMatch: bad array subscript
  🔴 Database schema parsing error. Quit
```

Seems like errors on:

`previousVersion=${previousSchemaRegexMatch[${#previousSchemaRegexMatch[@]} - 1]}`

and

`currentVersion=${currentSchemaRegexMatch[${#currentSchemaRegexMatch[@]} - 1]}`

2022-01-28 13:36 UTC, jdaev commented on lefthook/database_checker.sh
> +else
Yes

2022-01-28 15:41 UTC, agsuy commented on lefthook/database_checker.sh
> +if [ $(git diff @{u}...HEAD ./lib/models/tables | wc -l) -eq "0" ]; then
This was actually script logging errors to STDERR.

2022-01-28 15:42 UTC, agsuy approved these changes
Now we filter STDERR !
LGTM!

2022-01-28 15:42 UTC, merged