PE 876/Generate private drive share links
ardriveapp/ardrive-web pull request #367
Opened 2022-02-18 00:32 UTC by jdaev

2022-02-18 13:54 UTC, karlprieb commented on lib/utils/link_generators.dart
> +  final linkOrigin = kIsWeb ? Uri.base.origin : 'https://app.ardrive.io';
Can we create a constant somewhere for `https://app.ardrive.io` and use it here and on `file_share_cubit`?

2022-02-18 14:04 UTC, jdaev commented on lib/utils/link_generators.dart
> +  final linkOrigin = kIsWeb ? Uri.base.origin : 'https://app.ardrive.io';
[Added](https://github.com/ardriveapp/ardrive-web/pull/367/commits/3b88ab05d040a2750e0fb06ab2401a946628220b)

2022-02-18 14:05 UTC, jdaev commented on lib/utils/link_generators.dart
> +Future<Uri> generateDriveShareLink({
In this ticket an PR? That doesn't really have anything to do with the requirements on this one

2022-02-18 14:06 UTC, jdaev commented on lib/blocs/drive_share/drive_share_state.dart
> +
[Added](https://github.com/ardriveapp/ardrive-web/pull/367/commits/029b6db39496f08d923ce5b0305f1c96a4f7ebec)

2022-02-18 14:17 UTC, karlprieb commented on lib/utils/link_generators.dart
> +Future<Uri> generateDriveShareLink({
It doesn't have anything with this ticket requirements, but I considered that as code maintenance as you are introducing better standards.

2022-02-18 14:37 UTC, karlprieb commented on lib/blocs/drive_share/drive_share_cubit.dart
> +        drive: drive,
👍

2022-02-18 15:21 UTC, karlprieb commented on lib/blocs/file_share/file_share_cubit.dart
> +        isPublicFile: drive.isPrivate,
Shouldn't be the negation of `drive.isPrivate`?

2022-02-18 15:31 UTC, karlprieb commented on lib/utils/link_generators.dart
> +  required Privacy drivePrivacy,
Not an issue, just a question: Why in some places we are passing `isPublic` or `isPrivate` and here we use `drivePrivacy`?

2022-02-18 15:33 UTC, jdaev commented on lib/utils/link_generators.dart
> +  required Privacy drivePrivacy,
Just trying to reduce the use of booleans where I can, especially where you have to pass it into a function.

2022-02-18 22:41 UTC, fedellen commented on lib/blocs/drive_share/drive_share_cubit.dart
> +      emit(DriveShareLoadFail(message: 'Please login to share private drive.'));
Without a return here, doesn't this emit here get overwritten by the one below?

2022-02-18 22:50 UTC, fedellen commented on lib/blocs/drive_share/drive_share_cubit.dart
> +      emit(DriveShareLoadFail(message: 'Please login to share private drive.'));
Could eliminate the `late` here to make it easier to digest:

```dart
  if (drive.isPrivate && !(_profileCubit.state is ProfileLoggedIn)) {
      // Note: Should we even show the share drive link on attached private drive?
      emit(DriveShareLoadFail(message: 'Please login to share private drive.'));
      return;
    }

    final driveShareLink = await () async {
      if (drive.isPrivate) {
        final profileKey = (_profileCubit.state as ProfileLoggedIn).cipherKey;
        final driveKey = await _driveDao.getDriveKey(drive.id, profileKey);
        return generateDriveShareLink(
          drive: drive,
          driveKey: driveKey,
        );
      }

      return generateDriveShareLink(drive: drive);
    }();

    emit(
      // ...
    )
```

2022-02-18 23:14 UTC, fedellen commented on lib/entities/string_types.dart
> +typedef Privacy = String;
Doesn't the DrivePrivacy type already provide this?

2022-02-19 02:20 UTC, fedellen submitted a review, later dismissed

2022-02-22 11:18 UTC, matibat submitted a review, later dismissed
LGTM

2022-02-22 11:18 UTC, matibat commented on lib/components/drive_share_dialog.dart
> +                    'drive using the link above.',
Isn't there a need to use commas here?

2022-02-25 22:40 UTC, arielmelendez commented on lib/blocs/drive_share/drive_share_cubit.dart
> +      emit(DriveShareLoadFail(message: 'Please login to share private drive.'));
`login` -> `log in`
login is a noun
log in is an imperative phrase

2022-02-26 01:20 UTC, jdaev commented on lib/components/drive_share_dialog.dart
> +                    'drive using the link above.',
It's for formatting.

2022-02-26 01:23 UTC, jdaev commented on lib/blocs/drive_share/drive_share_cubit.dart
> +      emit(DriveShareLoadFail(message: 'Please login to share private drive.'));
[Updated](https://github.com/ardriveapp/ardrive-web/pull/367/commits/8d0b8a91e1b225e5bf51b3f4a0bd468603ca7ec0)

2022-03-04 07:10 UTC, arielmelendez commented on lib/blocs/drive_share/drive_share_cubit.dart
> +    if (drive.isPrivate && !(_profileCubit.state is ProfileLoggedIn)) {
Negation logic is tough on the reader. While I appreciate the value of an early return via guard clauses, I think the following is just easier to reason about:

```
    if (drive.isPrivate) {
      if (_profileCubit.state is ProfileLoggedIn) {
        final profileKey = (_profileCubit.state as ProfileLoggedIn).cipherKey;
        final driveKey = await _driveDao.getDriveKey(drive.id, profileKey);
        driveShareLink = await generateDriveShareLink(
          drive: drive,
          driveKey: driveKey,
        );
      } else {
        emit(
          DriveShareLoadFail(message: 'Please log in to share private drive.'),
        );
        return;
      }
    } else {
      driveShareLink = await generateDriveShareLink(drive: drive);
    }
```

2022-03-04 07:45 UTC, jdaev commented on lib/blocs/drive_share/drive_share_cubit.dart
> +    if (drive.isPrivate && !(_profileCubit.state is ProfileLoggedIn)) {
[Updated](https://github.com/ardriveapp/ardrive-web/pull/367/commits/4202d469896223116a414d7fdf87c03cdb4d0144)

2022-03-04 07:57 UTC, arielmelendez commented on lib/utils/link_generators.dart
> +  required Drive drive,
So I'd like to point out some of the consequences of the design choices here.

The variables needed to generate a drive share link are:

1. a drive name (a string)
2. a drive ID (a string)
3. a drive key (a SecretKey)

The choice to provide a Drive object to satisfy 1 and 2 creates a dependency on an object. And what's more, that object is actually a database entity.

Consequence 1: This function has no value to any other application or library now without a database.

By providing the Drive object, we get lulled into thinking:
- that the drive name and drive id, since they're traveling together, must be cohesive and correct
- that we'll make a good decision about what to do about the optionally provided drive key since we'll have access to the drive object's privacy setting.

But these beliefs are an illusion because:
- there's no guarantee that the Drive object, as assembled, is "legitimate".
- there's no guarantee that the provided drive key is the right one for the provided drive object.

We don't have access to the classes necessary to prove either of those things, nor would it be palatable to introduce those here due to crushing number of dependencies and complexity it would introduce. That sort of validation could and should be handled before calls to this (potentially) simple, pure input/output function.

Consequence 2: More branching logic that needs to be tested to make sure that the function gives the correct outputs given various permutations of Drive objects and key nullability.

Consequence 3: The potential for the function to be used incorrectly and the need to throw errors (e.g. when it's a private drive but no drive key is provided.

I think you can control for all three of the consequences above, put the heavier business logic back where it belongs (e.g. cubits and/or supporting helper classes), and make this function easier to use correctly and harder to use incorrectly like so:

```
Uri generatePublicDriveShareLink({
  required final String driveName,
  required final String driveId,
}) {
  // On web, link to the current origin the user is on.
  // Elsewhere, link to app.ardrive.io.
  final linkOrigin = kIsWeb ? Uri.base.origin : linkOriginProduction;

  final driveShareLink = '$linkOrigin/#/drives/${driveId}?name=' +
      Uri.encodeQueryComponent(driveName);
  return Uri.parse(driveShareLink);
}

Future<Uri> generatePrivateDriveShareLink({
  required final String driveName,
  required final String driveId,
  required final SecretKey driveKey,
}) async {
  final driveKeyBase64 = encodeBytesToBase64(await driveKey.extractBytes());

  return Uri.parse(generatePublicDriveShareLink(
        driveName: driveName,
        driveId: driveId,
      ).toString() +
      '&driveKey=$driveKeyBase64');
}
```

2022-03-04 08:14 UTC, arielmelendez commented on test/utils/link_generators_test.dart
> +          'generateDriveShareLink generates the correct link for a private drive',
Love that you added tests for these (seemingly) simple functions! As I mentioned in the design decisions message above, since it's possible for your code as currently written to pass a private drive and no secret key, you need a test for that permutation. That said, that's probably an illegal permutation that we don't even want. So either:
a) Test for the current behavior you have coded up which is to return the equivalent of a public drive link (which is not really desirable since that link won't even work anywhere, so why let the app even generate them?)
b) Throw an error when that state is encountered and add a test for that.
c) Update to the public vs. private implementation that I suggested where the illegal states aren't necessarily possible since the business logic considerations around validity are hoisted up to the callers that have the appropriate tools to make good choices.

2022-03-04 08:15 UTC, arielmelendez requested changes
Made a comment about the design choices for generateDriveShareLink (it's applicable to the file version as well). Whether or not you decide to make the changes I suggested, you'll need to update tests.

2022-03-04 08:21 UTC, jdaev commented on lib/utils/link_generators.dart
> +  required Drive drive,
Thanks for the insight, I made the mistake of assuming that I was just using an entity class instead of a database class without looking into it. 
[Updated](https://github.com/ardriveapp/ardrive-web/pull/367/commits/62b5a73987a0d5ca459eb0b1d62b980b01207f91)

2022-03-04 08:21 UTC, jdaev commented on test/utils/link_generators_test.dart
> +          'generateDriveShareLink generates the correct link for a private drive',
[Updated](https://github.com/ardriveapp/ardrive-web/pull/367/commits/62b5a73987a0d5ca459eb0b1d62b980b01207f91)

2022-03-04 08:23 UTC, jdaev commented
Note: Do not merge before attach private drives is also approved. Sharing private drives is useless without it.

2022-03-04 08:48 UTC, arielmelendez approved these changes
Thanks for the updates!

2022-03-04 16:25 UTC, fedellen approved these changes
LGTM!

Though if this PR depends on another PR, I would expect the base branch to be the one it depends on rather than `dev`

2022-03-07 05:32 UTC, jdaev commented
> 

This one doesn't depend on anything, but Attach Private Drives depends on this

2022-03-15 15:52 UTC, merged

2022-03-15 15:52 UTC, matibat approved these changes
:+1:

2022-03-15 15:52 UTC, matibat commented on lib/blocs/file_share/file_share_cubit.dart
> +      default:
This empty `default` could be handled at PE-1115