PE-815: Create manifest
ardriveapp/ardrive-web pull request #368
Opened 2022-02-24 18:49 UTC by fedellen

This PR adds the create manifest feature for public drives.

The cubit/form/state patterns are largely extended from the existing code as I was learning to work with the Flutter codebase and learn Dart in general. Specifically, create manifest uses a similar flow to the ghost folder cubit as suggested by @jdaev. 

I've extracted some logic for the manifest out into the new `ManifestEntity` class for testability where it made sense to do so here. I could continue, but its functional and I'm opening it up for review in its current state for feedback.

2022-02-25 00:44 UTC, jdaev commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +          dataContentType: ContentType.manifest);
Please add a trailing comma after the last argument everywhere it's applicable. The dart formatter relies on the trailing comma to add proper spacing.
eg:
```
final manifestFileEntity = FileEntity(
          size: arweaveManifest.size,
          parentFolderId: parentFolder.id,
          name: manifestName,
          lastModifiedDate: DateTime.now(),
          id: existingManifestFileId ?? Uuid().v4(),
          driveId: drive.id,
          dataTxId: manifestDataItem.id,
          dataContentType: ContentType.manifest,
          );
```

2022-02-25 00:50 UTC, jdaev commented on lib/components/create_manifest_form.dart
> +                onPressed: () => readCubitContext.prepareManifestTx(
Form validation should be done inside the cubit. You can have submit methods in there that you call from here.

2022-02-25 00:57 UTC, jdaev commented on lib/entities/manifest_entity.dart
> +class ManifestEntity {
ManifestEntity sort of makes it feel like this is an extension of entity, but that isn't the case. This ManifestEntity is just the data of a file right?  Maybe consider ManifestData?

2022-02-25 00:58 UTC, jdaev requested changes
Left some comments. Please add all the trailing commas

2022-02-25 08:28 UTC, jdaev commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +    emit(CreateManifestInitial());
You may want to clear the form here as well.

2022-02-25 14:09 UTC, fedellen commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +          dataContentType: ContentType.manifest);
Wouldn't the formatter add the trailing comma or the IDE show an error if this was the case?

2022-02-25 14:13 UTC, jdaev commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +          dataContentType: ContentType.manifest);
We don't have the lint rule enabled. It's a bit contextual. Generally we wanna have trailing commas if the declaration takes up more than one line, as in the case above.

2022-02-25 14:19 UTC, fedellen commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +          dataContentType: ContentType.manifest);
Added some here: 6b933bd2

Not sure if thats all of them

2022-02-25 16:12 UTC, fedellen commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +    emit(CreateManifestInitial());
[f2e9715](https://github.com/ardriveapp/ardrive-web/pull/368/commits/f2e9715ca5ea6ea2820f15b2ef49145bfa0a2322)

2022-02-25 16:13 UTC, fedellen commented on lib/components/create_manifest_form.dart
> +                onPressed: () => readCubitContext.prepareManifestTx(
Moved form validation with some new methods: [b3ed02b](https://github.com/ardriveapp/ardrive-web/pull/368/commits/b3ed02b9cf5079f5c594fe379ef586db8e0d77d6)

And refactored accessing the state values, but not sure this one cleaned up that much: [b53a381](https://github.com/ardriveapp/ardrive-web/pull/368/commits/b53a381f3bffcea948f1e4913e7ac0320a9c5695)

2022-02-25 16:29 UTC, fedellen commented on lib/entities/manifest_entity.dart
> +class ManifestEntity {
a4486ca7

2022-02-25 16:43 UTC, fedellen commented on test/models/daos/drive_dao_test.dart
> +    //   test('getRecursiveFiles with a maxDepth of 0 returns no files', () async {
Should be contents of root folder

2022-02-25 16:53 UTC, fedellen commented on lib/entities/manifest_data.dart
> +    {required String path, required int rootFolderLength}) {
Change to `filePath` and `rootFolderPath` and handle length in the function. Or add documentation

2022-02-25 16:56 UTC, fedellen commented on lib/entities/manifest_data.dart
> +  ManifestData(this.index, this.paths);
Make private by adding `_` in front

2022-02-25 16:58 UTC, fedellen commented on lib/entities/manifest_data.dart
> +  Future<DataItem> asPreparedDataItem({required Wallet wallet}) async {
Doesn't need wallet, just `owner`

2022-02-25 17:04 UTC, fedellen commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +        emit(CreateManifestInsufficientBalance());
Pass walletBalance and totalCost to display

2022-02-25 17:56 UTC, fedellen commented on lib/entities/manifest_data.dart
> +  ManifestData(this.index, this.paths);
This change seems to have conflicts with the JSON serializable side of this class. Might try this one further later on

2022-02-25 18:10 UTC, fedellen commented on test/models/daos/drive_dao_test.dart
> +    //   test('getRecursiveFiles with a maxDepth of 0 returns no files', () async {
[8d55d7c](https://github.com/ardriveapp/ardrive-web/pull/368/commits/8d55d7c7cc9eee326e9cd24c7094ba4e287eace8)

2022-02-25 18:10 UTC, fedellen commented on lib/entities/manifest_data.dart
> +    {required String path, required int rootFolderLength}) {
[883fc6c](https://github.com/ardriveapp/ardrive-web/pull/368/commits/883fc6cdd15e986f9ab7ff68850abf032a80898e)

2022-02-25 18:11 UTC, fedellen commented on lib/entities/manifest_data.dart
> +  Future<DataItem> asPreparedDataItem({required Wallet wallet}) async {
[96afcb6](https://github.com/ardriveapp/ardrive-web/pull/368/commits/96afcb63040562f46e5e61ba3cc81f2f98cda650)

2022-02-25 18:11 UTC, fedellen commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +        emit(CreateManifestInsufficientBalance());
[2b40095](https://github.com/ardriveapp/ardrive-web/pull/368/commits/2b40095a1c3a089337158cf1b563f3abd794f7f5)

2022-02-25 18:35 UTC, fedellen commented on lib/blocs/create_manifest/create_manifest_cubit.dart
> +          dataContentType: ContentType.manifest);
More commas: 1ae30feb

2022-03-01 18:25 UTC, karlprieb commented on lib/components/create_manifest_form.dart
> +        if (state is CreateManifestUploadInProgress) {
Maybe a switch case would make this more readable.

2022-03-01 18:25 UTC, karlprieb commented on lib/components/create_manifest_form.dart
> +          Navigator.pop(context);
Why do we pop twice?

2022-03-01 18:31 UTC, karlprieb commented
The manifest file appears in the folder before we confirm the transaction upload. If you cancel, it stays there:
![Kapture 2022-03-01 at 15 29 43](https://user-images.githubusercontent.com/9200155/156227774-08a4b2c5-6abf-4a5e-8e9d-40de8743e03a.gif)

2022-03-01 20:05 UTC, fedellen commented on lib/components/create_manifest_form.dart
> +        if (state is CreateManifestUploadInProgress) {
I thought so as well and tried that out during development. But, doing these type checks for the state with `is` during a switch case doesn't seem to be possible. If you know of a way it can work, I'd be happy to add it in here

2022-03-01 20:12 UTC, fedellen commented on lib/components/create_manifest_form.dart
> +          Navigator.pop(context);
This double pop originally came from the ghost folder form duplication. When I remove one of them, there is a dark overlay screen that seems to remain after a manifest upload has succeeded.

2022-03-01 20:13 UTC, fedellen commented
> The manifest file appears in the folder before we confirm the transaction upload. If you cancel, it stays there: ![Kapture 2022-03-01 at 15 29 43](https://user-images.githubusercontent.com/9200155/156227774-08a4b2c5-6abf-4a5e-8e9d-40de8743e03a.gif)

Thanks for catching that! 

I have cleaned up that promise and properly call it after the upload has succeeded in this commit: [b80795c](https://github.com/ardriveapp/ardrive-web/pull/368/commits/b80795cb72d0993dff55a61384683309a14d19b5)

2022-03-01 23:58 UTC, matibat reviewed
Left some comments

2022-03-01 23:58 UTC, matibat commented on lib/components/create_manifest_form.dart
> +        if (state is CreateManifestUploadInProgress) {
If there were a `typeof` you could switch over that

2022-03-01 23:58 UTC, matibat commented on lib/components/create_manifest_form.dart
> +                child: Text('CREATE'),
Something wrong with the indentation here :thinking:

2022-03-01 23:58 UTC, matibat commented on lib/entities/manifest_data.dart
> +}
Does it make sense to use `"%20"` instead of space? There could be an already built-in URL sanitization tool :thinking:

2022-03-01 23:58 UTC, matibat commented on lib/models/daos/drive_dao/folder_node.dart
> +  // TODO: maxDepth
Let's have a ticket for it

2022-03-02 14:51 UTC, fedellen commented on lib/components/create_manifest_form.dart
> +                child: Text('CREATE'),
Added some commas 😅  750d1c08

2022-03-02 15:14 UTC, fedellen commented on lib/components/create_manifest_form.dart
> +        if (state is CreateManifestUploadInProgress) {
I actually found a way to use this in a switch case, but it doesn't seem to properly type check the state. Which means I don't have safe access to the props on the state:

```dart
        switch (state.runtimeType) {

          case CreateManifestInsufficientBalance:
            return errorDialog(
              errorText:
                  'Provided wallet balance of ${state.walletBalance} AR is not enough for this manifest transaction costing ${state.totalCost} AR...',
                   // The above line has errors because `state` is not typechecked and remains as `CreateManifestState`
            );
```

2022-03-03 15:38 UTC, jdaev approved these changes

2022-03-03 21:15 UTC, fedellen commented on lib/models/daos/drive_dao/folder_node.dart
> +  // TODO: maxDepth
Added: 75fb39c1

2022-03-04 14:28 UTC, karlprieb approved these changes

2022-03-09 00:05 UTC, thiagocarvalhodev commented on test/models/daos/drive_dao_test.dart
> +    //   test('getRecursiveFiles with a maxDepth of 0 returns just the files in the root folder',
Would this test be implemented in a near future?

2022-03-09 00:05 UTC, thiagocarvalhodev commented on lib/models/daos/drive_dao/folder_node.dart
> +    // if (maxDepth == -1) {
Would this validation be implemented in a near future? If not, I think that would be better to remove, to avoid misunderstandings about it

2022-03-09 15:34 UTC, fedellen commented on lib/models/daos/drive_dao/folder_node.dart
> +    // if (maxDepth == -1) {
Not sure about the timetable here. This functionality works as is, but we don't have a design for the slider as of yet.

2022-03-10 12:54 UTC, matibat approved these changes
Left some non-blocking comments. It looks good to me! :clap:

2022-03-10 12:54 UTC, matibat commented on lib/components/create_manifest_form.dart
> +        if (state is CreateManifestUploadInProgress) {
I guess it's fine with the nested IFs

2022-03-10 12:54 UTC, matibat commented on lib/components/create_manifest_form.dart
> +              title: 'FAILED TO CREATE MANIFEST',
The newly added text has to be internationalized as well. I'm taking notes ;)

2022-03-10 12:54 UTC, matibat commented on lib/entities/constants.dart
> +const int maxConcurrentUploadCount = 32;
Non-blocking one: `camelCase` vs `MACRO_CASE` for constants :thinking:

2022-03-10 14:05 UTC, karlprieb commented on lib/entities/constants.dart
> +const int maxConcurrentUploadCount = 32;
https://dart.dev/guides/language/effective-dart/style#prefer-using-lowercamelcase-for-constant-names

2022-03-10 14:09 UTC, karlprieb approved these changes

2022-03-18 15:06 UTC, thiagocarvalhodev approved these changes

2022-03-18 15:09 UTC, karlprieb approved these changes

2022-03-18 15:33 UTC, merged