PE-1221: Missing Spanish translations
ardriveapp/ardrive-web pull request #436
Opened 2022-04-06 00:38 UTC by matibat

**This PR...**
- Adds the missing keys at app_es.arb
  - So the Back and Next buttons on the onboarding page are translated
  - The form validation messages are translated 
  - The manifest creation form is fully translated
- Fixes a Spanish typo: "Aplicación" at the onboarding page
- Declares insufficientARWarning and displayedPaginatedData keys in both ARB files
  - So the "Insufficient Funds" warning is translated
  - The paginated data count is translated: {from} - {to} of {total}
- Temporarily adds the keys aggreeToTerms_main, aggreeToTerms_link, welcomeTo_main, and welcomeTo_description directly in the code as those has a direct order relationship (1 to 1) between en and es. That will be dynamically handled in a [following-up work PE-1125](https://ardrive.atlassian.net/browse/PE-1125) when required for other languages.

2022-04-06 00:45 UTC, matibat reviewed
A couple more

2022-04-06 00:45 UTC, matibat commented on lib/l10n/app_es.arb
> +  "nextEmphasized": "NEXT",
```suggestion
  "nextEmphasized": "SIGUIENTE",
```

2022-04-06 00:45 UTC, matibat commented on lib/l10n/app_es.arb
> +  "backEmphasized": "BACK",
This is for text on the onboarding page, the BACK button. I suggest:
```suggestion
  "backEmphasized": "VOLVER",
```
```suggestion
  "backEmphasized": "ATRÁS",
```

2022-04-06 00:45 UTC, matibat commented on lib/l10n/app_es.arb
> +  "uploadEmphasized": "UPLOAD",
```suggestion
  "uploadEmphasized": "CARGAR",
```

2022-04-06 00:45 UTC, matibat commented on lib/l10n/app_es.arb
> +  "backEmphasized": "BACK",
```suggestion
  "backEmphasized": "ANTERIOR",
```

2022-04-06 15:03 UTC, karlprieb approved these changes

2022-04-06 15:27 UTC, fedellen approved these changes
The Spanish UI view is looking nice!

2022-04-07 17:47 UTC, agsuy requested changes
Left some comments

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "insufficientBalanceForManifest": "El balance de {walletBalance} AR es insuficiente para esta transacción de manifesto que cuesta: {totalCost} AR...",
manifiesto

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +    "description": "The user must type a non-conflicting name"
Update description to reflect text

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "conflictingManifestFound": "El manifesto ya existe",
manifiesto

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "conflictingManifestFoundChooseNewName": "Ya hay un manifesto con ese nombre aquí. ¿Quieres continuar y cargar este manifesto como una nueva revisión?",
manifiesto

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "addnewManifestEmphasized": "AÑADIR NUEVO MANIFESTO",
MANIFIESTO

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "aManifestIsASpecialKindOfFile": "Un manifesto es un tipo especial de archivos que relaciona cualquier cantidad de transacciones Arweave con direcciones amigable.",
"Un manifiesto es un tipo especial de archivo que relaciona transacciones Arweave con rutas perzonalizadas."

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "createManifestEmphasized": "CREAR MANIFESTO",
MANIFIESTO

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "filesWillBePermanentlyPublicWarning": "Todos los archivos cargados aquí serán permanentemente públicos para cualquiera en el internet. Asegúrate de estar haciendo la información pública a propósit
"Todos los archivos cargados aquí serán públicos por siempre para cualquiera en el internet. Asegúrate de que quieres que esta informacion sea publica."

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "validationAttachUserLoggedOut": "Debes iniciar sesión para vincular discos privados.",
... vincular unidades privadas."

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "validationEntityNameAlreadyPresent": "Una carpeta o archivo con el mismo nombre ya existe aquí.",
"Ya existe una carpeta o archivo con el mismo nombre."

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "validationDriveNameAlreadyPresent": "Un disco con el mismo nombre ya existe aquí.",
"Una unidad con el mismo nombre ya existe."

2022-04-07 17:47 UTC, agsuy commented on lib/l10n/app_es.arb
> +  "validationNameUnchanged": "Este nombre es el idéntico al nombre original",
"Este nombre es idéntico al nombre original"

2022-04-07 18:15 UTC, jdaev approved these changes

2022-04-07 18:40 UTC, agsuy approved these changes
LGTM!

2022-04-08 23:17 UTC, merged