feat: add mandarin string literals
ardriveapp/ardrive-web pull request #497
Opened 2022-05-16 04:12 UTC by fewwwww

2022-05-16 18:07 UTC, thiagocarvalhodev commented
Thanks for the really hard work! We appreciate! 

As I'm unable to understand Mandarin, I'll chat with the team for help. I will give you an update soon!

2022-05-16 18:17 UTC, matibat commented
TODO here
- Add 'zh' to the available locales

2022-05-23 14:08 UTC, thiagocarvalhodev commented
Hey, @fewwwww ! We are following our internalization process with your translations. We'll keep you up to date with the progress. Thanks!

2022-05-25 17:52 UTC, matibat requested changes
Hey @fewwwww! Thanks again for the translations, we appreciate your contribution ❤️ 

We are making some cleanup in the codebase to remove unused text from the resource file, would you mind applying the suggestions I made here? Those are supposed to remove the following keys at the ARB file: `errorLog`, `failedToPrepareFileUpload`, and `failedToPrepareFileUploadExplanation`.

2022-05-25 17:52 UTC, matibat commented on lib/l10n/app_zh.arb
> +  },
```suggestion
```

2022-05-25 17:52 UTC, matibat commented on lib/l10n/app_zh.arb
> +  },
```suggestion
```

2022-05-25 18:12 UTC, fewwwww commented
> Hey @fewwwww! Thanks again for the translations, we appreciate your contribution ❤️
> 
> We are making some cleanup in the codebase to remove unused text from the resource file, would you mind applying the suggestions I made here? Those are supposed to remove the following keys at the ARB file: `errorLog`, `failedToPrepareFileUpload`, and `failedToPrepareFileUploadExplanation`.

Done!

2022-05-25 20:27 UTC, matibat approved these changes
It looks good to me. Thank you! 🚀

2022-05-25 20:38 UTC, merged