PE-1662: Adds the Survey Feedback Modal
ardriveapp/ardrive-web pull request #540
Opened 2022-06-07 21:12 UTC by matibat

There's now a button at the profile to take the user to the Survey Feedback Form.
The modal is opened only after the first sync of the session.
It's not using `AppDialog`, but instead `AlertDialog` to have control on the position of it (bottom right).
It will start persisting the "Don't remind me again" flag in following up tickets.

2022-06-08 12:41 UTC, karlprieb commented
Please change to draft :)
LGTM, but I missed tests.

2022-06-08 18:17 UTC, thiagocarvalhodev commented on lib/utils/launch_survey_url.dart
> +  const url = 'https://ardrive.typeform.com/UserSurvey';
We can add that url to `resources.dart` `R` class.

2022-06-08 18:17 UTC, thiagocarvalhodev commented on lib/blocs/feedback_survey/feedback_survey_cubit.dart
> +  void dontRemindMeAgainClose() {
What do you think about calling it as `closeDontRemindMeModal()` and the `closeModal` function call as `closeRemindMeModal()`?

2022-06-08 20:57 UTC, matibat commented on lib/components/feedback_survey.dart
> +              right: 50,
dbb5f3f4af1c8cd40d8be55f03ce7a3e43b886d2

2022-06-08 20:57 UTC, matibat commented on lib/utils/launch_survey_url.dart
> +  const url = 'https://ardrive.typeform.com/UserSurvey';
9741c12d1bbcff069013b6d60c150fa8eeb8fc49

2022-06-08 20:58 UTC, matibat commented on lib/pages/app_router_delegate.dart
> +                          print('It is close! :D');
9e90b941dcc479285f1702296551f3248e7c8fb9

2022-06-08 20:58 UTC, matibat commented on lib/blocs/feedback_survey/feedback_survey_cubit.dart
> +  void dontRemindMeAgainClose() {
910976157f0f92731d8da0a10dd93c45904094f6

2022-06-08 21:01 UTC, matibat commented
Thanks for your comments @thiagocarvalhodev! I haven't yet applied the sleep before opening the modal, but that can come in a following up PR (I'd like to ask the Design guys before :D)
I also added the missing tests there

2022-06-08 23:40 UTC, matibat commented on lib/blocs/sync/sync_cubit.dart
> +    _feedbackCubit.openRemindMe('sync');
I've tested on a fresh wallet and it won't reach this point because there's no drive to sync

2022-06-08 23:40 UTC, matibat commented on lib/components/feedback_survey.dart
> +Future<void> openFeedbackSurveyModal(BuildContext context) => showGeneralDialog(
It's not a future. 
```suggestion
void openFeedbackSurveyModal(BuildContext context) => showGeneralDialog(
```

2022-06-08 23:42 UTC, matibat commented on lib/components/feedback_survey.dart
> +Future<void> openFeedbackSurveyModal(BuildContext context) => showGeneralDialog(
Hmm it actually is 😅

2022-06-09 00:08 UTC, thiagocarvalhodev commented on lib/blocs/sync/sync_cubit.dart
> +    _feedbackCubit.openRemindMe('sync');
ummmm! Do you think that is expected?

2022-06-09 11:38 UTC, thiagocarvalhodev requested changes
Beautiful see more tests! 😎

2022-06-09 15:25 UTC, matibat commented on lib/pages/app_router_delegate.dart
> +                        } else if (state is FeedbackSurveyDontRemindMe &&
Nice point ae87f149f718ef8e4435f612bb98b0cc95ffa5be

2022-06-09 15:31 UTC, matibat commented on lib/blocs/sync/sync_cubit.dart
> +    _feedbackCubit.openRemindMe('sync');
That might be expected for the sync behavior. But in this ticket I only needed a single condition to be able to see the modal; the actual conditions for opening the modal are gonna be addressed in PE-1663 so... I will ask the team if we want to display the modal even for fresh wallets -we maybe don't, and the current behavior is OK-.

2022-06-09 16:49 UTC, thiagocarvalhodev approved these changes
LGTM! Nice job, Matt!

2022-06-09 20:01 UTC, merged