Pe 1747 retry 5 xx errors
ardriveapp/ardrive-web pull request #561
Opened 2022-06-28 00:51 UTC by thiagocarvalhodev

2022-06-28 19:00 UTC, matibat reviewed
The code looks good to me!

---------

I would simply be more explicit on the tests' description:
- The group description talking about what component (e.g. class) are we testing
- The test description specifying:
  - **What inputs** are being tested,
  - over **which methods** (e.g. "handle()"),
  - and what's the expected behavior (this last point seems to be correctly covered)

One example for this would be:
`handle method should return RateLimitError when response has err code 429`

2022-06-28 19:07 UTC, thiagocarvalhodev commented on test/utils/network_error_handler_test.dart
> +  group('description', () {
Good catch!

2022-06-28 19:07 UTC, thiagocarvalhodev commented on test/utils/network_error_handler_test.dart
> +  group('description', () {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/34c2f5175deb104767c83443d237d6ef73fb6acf

2022-06-28 19:10 UTC, arielmelendez commented on lib/utils/network_error_handler.dart
> +          reasonPhrase: response.reasonPhrase ?? '');
The reason phrase null coalescing is happening in 3 different places. You might as well factor it out to a variable up above.

2022-06-28 19:13 UTC, thiagocarvalhodev commented on test/utils/http_retry_test.dart
> +  group('Testing HttpRetry', () {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/a175eaafeba08f538eb71641fbf3647e6045a78d

2022-06-28 19:13 UTC, thiagocarvalhodev commented on test/utils/http_retry_test.dart
> +    test('should throw ServerError for status code 504', () async {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/a175eaafeba08f538eb71641fbf3647e6045a78d

2022-06-28 19:14 UTC, arielmelendez commented on lib/utils/network_error_handler.dart
> +  NetworkError handle(Response response) {
Why would we return any kind of error for a 200? Why not make NetworkError nullable?

2022-06-28 19:15 UTC, arielmelendez commented on lib/utils/network_error_handler.dart
> +class NetworkErrorHandler {
This is less of a "handler" and more of a "mapper"

2022-06-28 19:16 UTC, thiagocarvalhodev commented on lib/utils/network_error_handler.dart
> +          reasonPhrase: response.reasonPhrase ?? '');
https://github.com/ardriveapp/ardrive-web/pull/561/commits/917a78849009b68c69b2932a9a2e98fe711954e8

2022-06-28 19:19 UTC, arielmelendez commented
Why did we build all these new classes if the dart retry library supports conditional retries via `retryIf`? Would have been a much smaller PR...

2022-06-28 19:21 UTC, thiagocarvalhodev commented on lib/utils/network_error_handler.dart
> +  NetworkError handle(Response response) {
Interesting point. My point with this class was to map the correct exception for each status code. The client class should verify any errors before mapping the response with this class. What do you think?

2022-06-28 19:24 UTC, arielmelendez commented on lib/utils/network_error_handler.dart
> +  NetworkError handle(Response response) {
I think this code is all kind of unusual to see in application code and a bit heavy handed when useful, tested alternatives already exist off the shelf. See my comment here: https://github.com/ardriveapp/ardrive-web/pull/561#issuecomment-1169127862

2022-06-28 19:26 UTC, thiagocarvalhodev commented
> Why did we build all these new classes if the dart retry library supports conditional retries via retryIf? Would have been a much smaller PR... See: https://github.com/google/dart-neats/tree/master/retry#using-retry

My goal was to map different error cases, so this can be useful not only on `retry` but for every http request. With that, we can improve our logs: for instance printing the type of exception, the status code, and the route for that exception...

2022-06-28 20:06 UTC, arielmelendez commented on lib/utils/http_retry.dart
> +  Future<Response> call(Future<Response> Function() request) {
This is not a great name for a function. It's not explaining what it's actual behaviors are, namely:
- retrying the provided closure if an exception occurs
- passing http responses to handler which itself is decided whether the http response should caused an exception to be thrown.

Consider a more useful name like: `processRequest`

2022-06-28 20:08 UTC, arielmelendez commented on lib/utils/http_retry.dart
> +  Future<Response> call(Future<Response> Function() request) {
Also consider naming the input parameter `requestFactory` since it's a factory function.

2022-06-28 20:12 UTC, arielmelendez commented on lib/utils/http_retry.dart
> +  final NetworkErrorHandler errorHandler;
Consider an interface called `ResponseHandler` and then create an implementation like `GatewayResponseHandler`.

2022-06-28 20:13 UTC, arielmelendez commented on lib/utils/http_retry.dart
> +  final NetworkErrorHandler errorHandler;
I think the `handle` function would just be a void function that may or may not throw based on the response object passed to it.

2022-06-28 20:24 UTC, arielmelendez commented on lib/utils/http_retry.dart
> +          'Retrying for ${exception.runtimeType} exception\n'
I don't think we need BOTH an exception AND a status code - we just need one or the other in the log. In the case of exceptions, there may not even be a status code.

2022-06-28 20:25 UTC, arielmelendez commented on lib/utils/http_retry.dart
> +      if (response.statusCode == 200) {
This would go away if the handler were responsible for deciding whether or not to throw.

2022-06-28 20:26 UTC, arielmelendez commented on lib/utils/http_retry.dart
> +      return exception is! RateLimitError;
This makes me sad. Large drives with fast internet connections simply will not work. Let's open a tech debt ticket for this. I think we need to make a PR to dart-neats for the retry library so that we can provide for dynamic delay duration calculation based on exception type (i.e.  rate limit exception).

2022-06-28 20:28 UTC, arielmelendez requested changes
See my comments about the handler class and the tech debt ticket.

2022-06-29 13:37 UTC, thiagocarvalhodev commented on lib/utils/http_retry.dart
> +          'Retrying for ${exception.runtimeType} exception\n'
We can have more than one status code for a specific exception, that is the cade of ServerError that can have 5xx status code. I guess for log porpuses it will help us to underdant which error we are facing and also the request route related to that. What do you think?

2022-06-29 13:45 UTC, thiagocarvalhodev commented on lib/utils/http_retry.dart
> +  Future<Response> call(Future<Response> Function() request) {
Great suggestion!

2022-06-29 13:51 UTC, thiagocarvalhodev commented on lib/utils/http_retry.dart
> +  Future<Response> call(Future<Response> Function() request) {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/97e0dbdda5302d64c23bf14fc238b91fd69bf791

2022-06-29 13:51 UTC, thiagocarvalhodev commented on lib/utils/http_retry.dart
> +      if (response.statusCode == 200) {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/876963f818ada6359d4caf9388e2f9c87e3295ad

2022-06-29 16:10 UTC, thiagocarvalhodev commented on lib/utils/error.dart
> +// TODO(@thiagocarvalhodev): Add more error constants
https://github.com/ardriveapp/ardrive-web/pull/561/commits/fc885b45257082ca708ba932805179170463f260

2022-06-30 16:03 UTC, arielmelendez commented on lib/utils/error.dart
> +abstract class ArDriveError implements Exception {}
Remove this class. It has no clear or documented value right now.

2022-06-30 16:03 UTC, arielmelendez commented on lib/utils/response_handler.dart
> +  Response? handle(Response response);
Make this a void function

2022-06-30 16:04 UTC, arielmelendez commented on lib/utils/response_handler.dart
> +class GatewayResponseHandler implements ResponseHandler {
Move this class to be a peer to arweave_service.dart in the services/arweave folder so that the handling and errors are in the logical domain of Arweave code.

2022-06-30 16:04 UTC, arielmelendez commented on lib/utils/error.dart
> +abstract class NetworkError extends ArDriveError with EquatableMixin {
Rename NetworkError to GatewayError.

2022-06-30 16:47 UTC, thiagocarvalhodev commented on lib/utils/response_handler.dart
> +class GatewayResponseHandler implements ResponseHandler {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/8bd1bdb4ea435b1dff02a68c16af6ba9e2ec1076

2022-06-30 16:47 UTC, thiagocarvalhodev commented on lib/utils/response_handler.dart
> +  Response? handle(Response response);
https://github.com/ardriveapp/ardrive-web/pull/561/commits/8bd1bdb4ea435b1dff02a68c16af6ba9e2ec1076

2022-06-30 16:47 UTC, thiagocarvalhodev commented on lib/utils/error.dart
> +      {this.requestRoute,
https://github.com/ardriveapp/ardrive-web/pull/561/commits/8bd1bdb4ea435b1dff02a68c16af6ba9e2ec1076

2022-06-30 16:49 UTC, thiagocarvalhodev commented on lib/utils/response_handler.dart
> +  NetworkError _mapError(Response response) {
https://github.com/ardriveapp/ardrive-web/commit/8bd1bdb4ea435b1dff02a68c16af6ba9e2ec1076

2022-06-30 16:49 UTC, thiagocarvalhodev commented on lib/utils/error.dart
> +class NetworkTimeOut extends NetworkError {
https://github.com/ardriveapp/ardrive-web/commit/8bd1bdb4ea435b1dff02a68c16af6ba9e2ec1076

2022-06-30 16:50 UTC, thiagocarvalhodev commented on lib/utils/error.dart
> +abstract class NetworkError extends ArDriveError with EquatableMixin {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/e1145156d6b54984a915cdc78b25c56a4804abda

2022-06-30 19:58 UTC, arielmelendez commented on lib/services/arweave/error/gateway_error.dart
> +          requestRoute: requestUrl,
The word "route" is still leaking here 😬

2022-06-30 20:02 UTC, arielmelendez commented on lib/services/arweave/error/gateway_response_handler.dart
> +/// Throws a `GatewayError` exception for `statusCode` different from 200
nit: not in the 2xx range

2022-06-30 20:03 UTC, arielmelendez commented on test/services/arweave/error/response_handler_test.dart
> +    test('should return the response for success', () {
should return null

2022-06-30 20:03 UTC, arielmelendez commented on test/services/arweave/error/response_handler_test.dart
> +    test('should return the response for success', () {
also null

2022-06-30 20:04 UTC, arielmelendez commented on test/services/arweave/error/response_handler_test.dart
> +  final success250 = Response('body', 250);
this should probably be 299

2022-06-30 20:05 UTC, arielmelendez commented on test/utils/http_retry_test.dart
> +    test('Should return the response when dont have any errors', () async {
null

2022-06-30 20:05 UTC, arielmelendez requested changes
left some minor comments re: test names and inputs

2022-06-30 20:15 UTC, thiagocarvalhodev commented on test/utils/http_retry_test.dart
> +    test('Should return the response when dont have any errors', () async {
Here we returns the response.

2022-06-30 20:22 UTC, thiagocarvalhodev commented on test/services/arweave/error/response_handler_test.dart
> +    test('should return the response for success', () {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/6042fdf5b0d5aeb47182e10f29e2dab3d6e285f2

2022-06-30 20:22 UTC, thiagocarvalhodev commented on test/services/arweave/error/response_handler_test.dart
> +    test('should return the response for success', () {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/6042fdf5b0d5aeb47182e10f29e2dab3d6e285f2

2022-06-30 20:22 UTC, thiagocarvalhodev commented on test/services/arweave/error/response_handler_test.dart
> +    test('should return the response for success', () {
https://github.com/ardriveapp/ardrive-web/pull/561/commits/6042fdf5b0d5aeb47182e10f29e2dab3d6e285f2

2022-06-30 20:22 UTC, thiagocarvalhodev commented on lib/services/arweave/error/gateway_response_handler.dart
> +/// Throws a `GatewayError` exception for `statusCode` different from 200
https://github.com/ardriveapp/ardrive-web/pull/561/commits/6042fdf5b0d5aeb47182e10f29e2dab3d6e285f2

2022-06-30 20:23 UTC, thiagocarvalhodev commented on test/services/arweave/error/response_handler_test.dart
> +  final success250 = Response('body', 250);
https://github.com/ardriveapp/ardrive-web/pull/561/commits/a8e855cc084c4bb80384ee2d91e6ab7675ce0f35

2022-06-30 20:23 UTC, thiagocarvalhodev commented on lib/services/arweave/error/gateway_error.dart
> +          requestRoute: requestUrl,
https://github.com/ardriveapp/ardrive-web/pull/561/commits/b17012ca00fe91ca23ac7b43584b2f12c5e15bc1

2022-06-30 20:30 UTC, arielmelendez approved these changes

2022-07-01 21:17 UTC, agsuy commented on test/services/arweave/error/response_handler_test.dart
> +    test('should throws a ServerError', () {
Nit(grammar):
```suggestion
    test('should throw a ServerError', () {
```

2022-07-05 12:50 UTC, thiagocarvalhodev commented
Improvements:

- Added `UnExpectedRedirection` error
- Test if the `HttpRetry` is retrying how many times we choose
- Pass the callbacks functions on a object `HttpRetryOptions` in order to test
- Verify only possible 2xx status code

2022-07-05 19:25 UTC, karlprieb approved these changes

2022-07-05 19:31 UTC, merged

2023-04-24 23:49 UTC, matibat commented on lib/utils/http_retry.dart
> +        },
The exponential backoff for error 429 can be done here if we declare the method as async (a future).