Pe 1863 implement ardrive_io abstraction and an Android implementation (WIP)
ardriveapp/ardrive-web pull request #596
Opened 2022-07-18 18:56 UTC by thiagocarvalhodev

### Overview

**[Important]:** don't be afraid of review, most of the files are from the example project, in this case, the only file that matter is:
- `example/lib/main.dart`.

### Abstraction overview
We are implementing an abstraction to handle I/O operations such as picking a file, picking folders, etc... our goal is to have an agnostic platform package.

### Entities
#### `IOEntity` 
The base class for an agnostic file system entity
#### `IOFile ` 
Base class for every file, where each platform can implement.
#### `IOFolder ` 
Base class for every folder, where each platform can implement.

#### `IOException`
Base class for exceptions handled in this library

### I/O Operations

The I/O operations on the file system will be handled at the `ArDriveIO` class. Its interface covers our needed methods:
```dart
Future<IOFile> pickFile({List<String>? allowedExtensions});
Future<List<IOFile>> pickFiles({List<String>? allowedExtensions});
Future<IOFolder> pickFolder();
Future<void> saveFile(IOFile file);
 ```
#### MobileIO
That class will implement the `ArDriveIO` for both platforms: `Android` and `iOS`. This PR will address an Android first implementation, but the same code can work for iOS, unless the method `save()`.

#### Adapters
`IOFileAdapter` 
`IOFolderAdapter`

2022-07-19 15:31 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/adrive_io.dart
> +    if (kIsWeb) {
What we need for this case is just to implement a stub for the web implementation and import it when running on Web.

```dart
import 'io_exception.dart';
import 'mobile/mobile_io.dart';
import 'web/stub_io.dart' // Stub implementation
    if (dart.library.html) 'web/web_io.dart';

abstract class ArDriveIO {
  Future<IOFile> pickFile({List<String>? allowedExtensions});
  Future<List<IOFile>> pickFiles({List<String>? allowedExtensions});
  Future<IOFolder> pickFolder();
  Future<void> saveFile(IOFile file);

  factory ArDriveIO() {
    if (kIsWeb) {
      return WebIO();
    }

    return MobileIO(
        fileSaver: FileSaver(),
        fileAdapter: IOFileAdapter(),
        folderAdapter: IOFolderAdapter());
  }
}
```

2022-07-20 19:02 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +String lookupMimeTypeWithDefaultType(String path, {List<int>? headerBytes}) =>
Copy unit tests from `mime_lookup.dart` and remove after adding this implementation to web

2022-07-20 19:03 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +String lookupMimeTypeWithDefaultType(String path, {List<int>? headerBytes}) =>
Implement unit test for `lookupMimeTypeWithDefaultType`

2022-07-20 19:32 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +  final String fileExtension;
Remove this function as we already have the `contentType`.

2022-07-20 19:32 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +    final xfile = XFile(file.path);
Remove xfile and implement a function to get the file name. Look at `path` implementation

2022-07-20 19:32 UTC, thiagocarvalhodev commented on ardrive_io/test/src/io_folder_test.dart
> +      expect(firstLevelFolder.path, 'first-level');
add test for `modifiedDate` property.

2022-07-20 19:42 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +String getExtensionFromPath(String path) {
Remove this function and its tests.

2022-07-20 20:15 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +    final xfile = XFile(file.path);
https://github.com/ardriveapp/ardrive-web/pull/596/commits/4bee381020f492ec3f01ed7e322d659c09814676

2022-07-20 20:26 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +String lookupMimeTypeWithDefaultType(String path, {List<int>? headerBytes}) =>
https://github.com/ardriveapp/ardrive-web/pull/596/commits/d1c019cc8f9d3a7cd2722096e9b67642fa8000a6

2022-07-20 20:27 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +String lookupMimeTypeWithDefaultType(String path, {List<int>? headerBytes}) =>
https://github.com/ardriveapp/ardrive-web/pull/596/commits/d1c019cc8f9d3a7cd2722096e9b67642fa8000a6

2022-07-20 20:28 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +String? lookupMimeType(String path, {List<int>? headerBytes}) {
https://github.com/ardriveapp/ardrive-web/pull/596/commits/76cc0e24694062ea05037306a406e6ff67a429c0

2022-07-20 20:31 UTC, thiagocarvalhodev commented on ardrive_io/test/src/io_folder_test.dart
> +      expect(firstLevelFolder.path, 'first-level');
https://github.com/ardriveapp/ardrive-web/pull/596/commits/44efd30ead9e73c388000730565868233cca963c

2022-07-20 20:31 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +String getExtensionFromPath(String path) {
https://github.com/ardriveapp/ardrive-web/pull/596/commits/431741498753d5459af6233023947cc557a065d5

2022-07-21 13:41 UTC, karlprieb commented on ardrive_io/CHANGELOG.md
> +* TODO: Describe initial release.
Can we have a proper changelog here?

2022-07-21 13:42 UTC, karlprieb commented on ardrive_io/LICENSE
> +TODO: Add your license here.
Use AGPL-3

2022-07-21 13:43 UTC, karlprieb commented on ardrive_io/README.md
> +<!--
Can you update the README?

2022-07-21 13:51 UTC, karlprieb commented on ardrive_io/lib/src/adrive_io.dart
> +    if (kIsWeb) {
👍

2022-07-21 13:55 UTC, karlprieb commented on ardrive_io/lib/src/io_file.dart
> +class _CommonFile implements IOFile {
What about a better name here to differentiate it from `_DataFile`?

2022-07-21 13:56 UTC, karlprieb commented on ardrive_io/lib/src/io_exception.dart
> +class FileSystemPermissionDeniedException extends IOException {}
Can we return more details here?

2022-07-21 13:58 UTC, karlprieb commented on ardrive_io/lib/src/io_folder.dart
> +  Future<List<IOEntity>> _mountFolderChildren() async {
maybe `_populateFolderWithChildrens` or something more meaningful?

2022-07-21 14:01 UTC, karlprieb commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +final gZipRegExp = RegExp('.\\.(gz|tgz)\$');
Add a comment to remember us to remove this edge case when https://github.com/dart-lang/mime/pull/66 get released.

2022-07-21 14:05 UTC, karlprieb commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +          /// TODO(@thiagocarvalhodev): implement a function to get the extension
we can use https://pub.dev/documentation/mime/latest/mime/extensionFromMime.html

2022-07-21 14:08 UTC, karlprieb commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +MimeType getMimeTypeFromString(String mimeType) {
Can't we use https://api.dart.dev/stable/2.17.5/dart-io/ContentType-class.html to wrap a content type and get the `MimeType` from it?

2022-07-21 14:09 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +    return _CommonFile(
I totally agree that the name could improve. Thanks!

> Is there a need for different classes instead of just using different constructors?

As we want to have an abstraction for files and folders, we are adding only the interface for `IOFile` or `IOFolder`. As those classes are abstract, we can't call its constructor. Another reason is that building the object construction for different platforms will add more complexity for just one class.

2022-07-21 14:10 UTC, karlprieb commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +String getFolderNameFromPath(String path) {
`getLastFolderNameFromPath`?

2022-07-21 14:14 UTC, karlprieb commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +    Directory generalDownloadDir = Directory('/storage/emulated/0/Download/');
Great! Let's remove `AndroidDownloadsFileSaver`

2022-07-21 14:17 UTC, karlprieb commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +    await Permission.storage.request();
Do we still need to ask for permissions to manage all folders? Using `FileSaver` would be good to ask for permission only for the folder that we want to write.

2022-07-21 14:37 UTC, thiagocarvalhodev commented on ardrive_io/LICENSE
> +TODO: Add your license here.
https://github.com/ardriveapp/ardrive-web/pull/596/commits/15453adf2fceea631ae1879f4dae7d5f32257ed2

2022-07-21 17:16 UTC, fedellen commented on ardrive_io/example/lib/main.dart
> +}
Is this running the app at the top level? If so, do we need to catch errors globally here in flutter?

2022-07-21 17:18 UTC, fedellen commented on ardrive_io/example/lib/main.dart
> +    final folder = await ArDriveIO().pickFolder();
whitespace nit, so it will be consistent with `pickFile`:

```suggestion
    final folder = await ArDriveIO().pickFolder();
    
```

2022-07-21 17:21 UTC, fedellen commented on ardrive_io/lib/src/adrive_io.dart
> +abstract class ArDriveIO {
This file is misspelled: `adrive_io.dart`

2022-07-21 17:30 UTC, fedellen commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +  Future<IOFile> pickFile({List<String>? allowedExtensions}) async {
Would allowedExtensions have a default value?

2022-07-21 17:31 UTC, fedellen commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +      }).toList());
These seem to be almost the same thing. Can we share the implementations?

2022-07-21 17:33 UTC, fedellen commented on ardrive_io/lib/src/io_file.dart
> +class IOFileAdapter {
What would you describe as the responsibilities of the `FileAdapter` and `FolderAdapter` classes?

2022-07-21 17:35 UTC, fedellen commented on ardrive_io/lib/src/io_file.dart
> +  final String path;
Consider lifting these into `IOFile`

2022-07-21 17:36 UTC, fedellen commented on ardrive_io/lib/src/io_file.dart
> +  final String path;
Or at least some of them fileExtension and bytes are obviously unique.

2022-07-21 17:39 UTC, fedellen commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +  Future<List<IOFile>> pickFiles({List<String>? allowedExtensions}) async {
Is it possible to create unit tests for these methods? It seems like a good opportunity to test reading files/folders if there aren't any blockers

2022-07-21 17:54 UTC, fedellen commented on ardrive_io/CHANGELOG.md
> +* TODO: Describe initial release.
do we maintain CHANGELOG.md anywhere else? I think we can probably remove this unless we move to using them for our release process

2022-07-21 17:56 UTC, fedellen commented on ardrive_io/lib/src/io_file.dart
> +class IOFileAdapter {
I'd add the answer to the above question that as doc blocks for those classes. And then maybe we can riff on a more descriptive name if necessary

2022-07-21 19:20 UTC, thiagocarvalhodev commented on ardrive_io/example/lib/main.dart
> +}
We can use this function https://api.flutter.dev/flutter/dart-async/runZoned.html and catch every exception. But for this example, we don't need.

2022-07-21 19:23 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/adrive_io.dart
> +abstract class ArDriveIO {
f0f1282d

2022-07-21 19:24 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/adrive_io.dart
> +abstract class ArDriveIO {
Really good catch!

2022-07-21 19:27 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +  Future<IOFile> pickFile({List<String>? allowedExtensions}) async {
No. the default behavior is to show all files, and this case is when we don't pass any `allowedExtensions`.

2022-07-21 19:35 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +      }).toList());
https://github.com/ardriveapp/ardrive-web/pull/596/commits/107b5fbf16b1447dfaa5e59352383936cffa602b

2022-07-21 19:43 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +  Future<List<IOFile>> pickFiles({List<String>? allowedExtensions}) async {
It is possible! https://stackoverflow.com/a/71150352/12227195 we can use this.

2022-07-21 19:46 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +          /// TODO(@thiagocarvalhodev): implement a function to get the extension
107b5fbf

2022-07-21 19:49 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +final gZipRegExp = RegExp('.\\.(gz|tgz)\$');
dart-lang/mime#66

2022-07-21 19:50 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +MimeType getMimeTypeFromString(String mimeType) {
The `MimeType` that we are getting here is a concrete class from the `file_saver` package.

2022-07-21 20:11 UTC, matibat reviewed
\* almost done reviewing *

2022-07-21 20:11 UTC, matibat commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +String getFolderNameFromPath(String path) {
I'd say the current name is correct. What's happening in the `return` line is that they're getting the `last` item of the split array, that is: the name.

I'd say there should be a built-in method to get the basename

2022-07-21 20:11 UTC, matibat commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +  return path.split('/').last;
We may want to resolve the absolute path before doing that. It would return '.' if I ask for the name of '.'

2022-07-21 20:11 UTC, matibat commented on ardrive_io/test/src/io_folder_test.dart
> +    });
Nit
```suggestion
    });

```

2022-07-21 20:11 UTC, matibat commented on ardrive_io/test/src/utils/mime_type_utils_test.dart
> +            pathToMimeMapping[path] ?? 'application/octet-stream';
Instead of this conditional we can explicitly set octet-stream in the mapping itself

2022-07-21 20:16 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +String getFolderNameFromPath(String path) {
We have this function: https://api.flutter.dev/flutter/package-path_path/dirname.html

2022-07-21 20:31 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +String getFolderNameFromPath(String path) {
> We have this function: https://api.flutter.dev/flutter/package-path_path/dirname.html. Gonna use that.

This function doesn't do what we want. Instead, we should use this: https://api.flutter.dev/flutter/package-file_file/FileSystemEntity/basename.html

2022-07-21 20:36 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_exception.dart
> +  UnsupportedPlatformException([this.exception]);
It's not an array. lol. It is a way of passing an optional parameter.

2022-07-21 20:38 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +      throw Exception('Unreconized MIME type for $mimeType');
Great point. This function is only for handling the `file_saver` package. In case of an unrecognized mime type, we can pass `MimeType.OTHER` which means octet-stream.

2022-07-21 20:39 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +  return path.split('/').last;
Function removed at https://github.com/ardriveapp/ardrive-web/pull/596/commits/7ddab4419cdb610873e33c25a88520fedd40f593

2022-07-21 20:41 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +    return utf8.decode(bytes);
We use it on `profile_auth_prompt_wallet_screen.dart` line 70.

2022-07-21 20:42 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +    return utf8.decode(bytes);
As only use utf-8, I left the implementation as it is. If we want another, we can easily change.

2022-07-21 20:48 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_folder.dart
> +  Future<List<IOEntity>> listContent();
My goal with that class was to mount our folder structure reflecting what we have on O.S, so the library's client will decide how to use this information. It also makes it easier for us to mount our folder structure on the folder upload feature. I'd say that we can implement new two methods: `listFolders()` and `listFiles()` from the `listContent()` function. What do you think?

2022-07-21 20:58 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_exception.dart
> +class FileSystemPermissionDeniedException extends IOException {}
f4b03fff

2022-07-21 20:58 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_folder.dart
> +  Future<List<IOEntity>> _mountFolderChildren() async {
`mountFolderStructure()`?

2022-07-21 21:03 UTC, fedellen commented on ardrive_io/lib/src/io_file.dart
> +  /// `path` is optional since it will be stored in memory
`since it will be stored in memory` is a bit vague. 

Does `ArDriveIO` ever handle the path? Or is it up to users of this package to know how to interact with paths

2022-07-21 21:07 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +  /// `path` is optional since it will be stored in memory
We can set the path for future use, for instance set the path to save on O.S

2022-07-21 21:38 UTC, fedellen commented on ardrive_io/example/lib/main.dart
> +}
I know this was an example. I was just curious on what the standard way of running a Flutter app from top level might be. I've seen lots of `try { main() } catch (e) { console.error('MAJOR ERROR: ${e}') }` in JS for example

2022-07-22 13:56 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +  /// `path` is optional since it will be stored in memory
Parameter removed: https://github.com/ardriveapp/ardrive-web/pull/596/commits/a115f671f925ddea0e354709a0faacb00d37e9d2

2022-07-22 13:59 UTC, thiagocarvalhodev commented on ardrive_io/test/src/utils/mime_type_utils_test.dart
> +            pathToMimeMapping[path] ?? 'application/octet-stream';
We can, but for a better understanding of the code I prefer to put it there and let the reader knows that if we got a null mime type from lookupMimeType we'll pass `'application/octet-stream'`. Does that make sense?

2022-07-22 14:01 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +      throw Exception('Unreconized MIME type for $mimeType');
I added the `MimeType.OTHER` as a default option. Really good catch, @matibat ! thanks.
a115f671

2022-07-22 17:49 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_folder.dart
> +  Future<List<IOEntity>> listContent();
Added two new methods: `files()` and `subfolders()`. `files()` will list all files inside the current `IOFolder` structure. That means get all files from this folder and also the folder's children. `subfolders()` do the same, but getting only a list of `IOFolder`.

https://github.com/ardriveapp/ardrive-web/pull/596/commits/a4f8a19633d5949b9f795bf975f5c2618d5e2dfd

2022-07-22 20:41 UTC, thiagocarvalhodev commented
Added a brief explanation of the package on README.

2022-07-22 20:41 UTC, karlprieb commented on ardrive_io/CHANGELOG.md
> +* TODO: Describe initial release.
make sense!

2022-07-22 20:42 UTC, karlprieb commented on ardrive_io/lib/src/io_folder.dart
> +  Future<List<IOEntity>> _mountFolderChildren() async {
Sure :D

2022-07-25 16:00 UTC, arielmelendez commented on ardrive_io/example/README.md
> +This project is a starting point for a Flutter application.
As a reader stumbling in here, I'm not sure how to interpret this. Why is it a starting point? This is an ArDrive project, not a Flutter team project... so why is it "a starting point"? What does it give me? Why do I need it? How do I use it?

2022-07-25 16:19 UTC, arielmelendez commented on ardrive_io/lib/src/ardrive_io.dart
> +  Future<void> saveFile(IOFile file);
Is there hope of adding a saveFile interface function and implementations for accepting a stream rather than a file handle?

2022-07-25 16:21 UTC, arielmelendez commented on ardrive_io/lib/src/ardrive_io.dart
> +  Future<void> saveFile(IOFile file);
Also some documentation about the expected behaviors (from a high level) could be helpful here. For example, where does that input file get saved to? Do we need some additional (potentially optional) parameters for file destination?

2022-07-25 16:25 UTC, arielmelendez commented on ardrive_io/test/src/utils/mime_type_utils_test.dart
> +            pathToMimeMapping[path] ?? 'application/octet-stream';
@thiagocarvalhodev I agree with @matibat on this 100%. Minimizing logic in your tests is typically the best policy. I understand that from your perspective this is clearer for the reader but as actual readers that didn't write this, both Mati and I see it differently.

2022-07-25 16:26 UTC, arielmelendez requested changes
Left a comment on a test file. Also left and important question re: api design (and request for docs).

2022-07-25 16:30 UTC, thiagocarvalhodev commented on ardrive_io/example/README.md
> +This project is a starting point for a Flutter application.
This is a template file generated by Flutter for the example project. Commonly we describe those questions on the package's README, as you can see on [ardrive_io/README.md](https://github.com/ardriveapp/ardrive-web/pull/596/files#diff-0f5c6f7f05452dfa117d4da92f77fcac9d86816b87745ba0a15e1b138f43e8e2)

2022-07-25 16:51 UTC, karlprieb commented on ardrive_io/lib/src/io_folder.dart
> +  Future<List<IOEntity>> _mountFolderChildren() async {
Will you apply this change?

2022-07-25 16:56 UTC, karlprieb commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +  return path.split('/').last;
Can we remove this file and its tests as we're not using anymore?

2022-07-25 17:01 UTC, matibat commented on ardrive_io/example/README.md
> +This project is a starting point for a Flutter application.
We could make a cleanup ticket to follow up this later on

2022-07-25 17:01 UTC, karlprieb commented on ardrive_io/lib/src/ardrive_io.dart
> +  Future<void> saveFile(IOFile file);
I believe that right now (having only Android) this is just an abstraction to `filesaver.save` method that will allow the user to choose where this file should be saved.
For iOS and Web it should be the same, the user should choose the path where the file will be saved.
Now for a future Desktop app we could have a default download path setting that will require us to extend this method.

2022-07-25 17:15 UTC, karlprieb commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +  Future<List<IOFile>> pickFiles({List<String>? allowedExtensions}) async {
Can you create a tech_debt ticket to implement integration tests for all platforms when you finish the last platform implementation?

2022-07-25 17:53 UTC, thiagocarvalhodev commented on ardrive_io/test/src/utils/mime_type_utils_test.dart
> +            pathToMimeMapping[path] ?? 'application/octet-stream';
Added explicitly octet-stream in the map:

https://github.com/ardriveapp/ardrive-web/pull/596/commits/11543d186c5fe8c69081f6e9469949b8a256468b

2022-07-25 17:54 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +  return path.split('/').last;
Removed at
https://github.com/ardriveapp/ardrive-web/pull/596/commits/070530378d78ac8994e1006ad940670744d56fa3

2022-07-25 17:54 UTC, thiagocarvalhodev commented on ardrive_io/example/README.md
> +This project is a starting point for a Flutter application.
I don't think that is needed, as it is just an example.

2022-07-25 18:06 UTC, matibat reviewed
Most of my comments are non-blocking regarding the README

2022-07-25 20:01 UTC, thiagocarvalhodev commented on ardrive_io/README.md
> +### Save a file on O.S.
https://github.com/ardriveapp/ardrive-web/pull/596/commits/e9e50500d956666155f4710c1a244b2ab815d108

2022-07-25 20:01 UTC, thiagocarvalhodev commented on ardrive_io/README.md
> +### Pick a file(s) or an folder on O.S.
https://github.com/ardriveapp/ardrive-web/pull/596/commits/e9e50500d956666155f4710c1a244b2ab815d108

2022-07-25 20:03 UTC, thiagocarvalhodev commented on ardrive_io/README.md
> +### Pick a file(s) or an folder on O.S.
Removed change log file: https://github.com/ardriveapp/ardrive-web/pull/596/commits/cc6a2245f4c3b8d29bb23cb36a8732160fff7841

2022-07-26 10:11 UTC, thiagocarvalhodev commented on ardrive_io/README.md
> +Base class for every folder from O.S.
Nice! https://github.com/ardriveapp/ardrive-web/pull/596/commits/e9e50500d956666155f4710c1a244b2ab815d108

2022-07-26 10:19 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_folder.dart
> +  Future<List<IOEntity>> _mountFolderChildren() async {
https://github.com/ardriveapp/ardrive-web/pull/596/commits/52abdd66975a0c797b29359e660b22f609f41471

2022-07-26 10:41 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/utils/file_path_utils.dart
> +  return path.split('/').last;
I replied before seeing your last comment, Mati! Sorry :(

I agree with you, also we can export this function if we want to use it on ArDrive Web: https://github.com/ardriveapp/ardrive-web/pull/596/commits/68a74bb993867111b77741951b95c04b5c089601

2022-07-26 13:57 UTC, thiagocarvalhodev commented on ardrive_io/README.md
> +    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
Great question. The `MANAGE_EXTERNAL_STORAGE` was introduced in Android 11 and allows us to write to a file outside the application's directory. 

>Android 11 introduces the MANAGE_EXTERNAL_STORAGE permission, which provides write access to files outside the app-specific directory and MediaStore. To learn more about this permission, and why most apps don't need to declare it to fulfill their use cases, see the guide on how to [manage all files](https://developer.android.com/training/data-storage/manage-all-files) on a storage device.

I used this permission to save a file directly on Downloads folder without let the user choose where on a previous implementation. 

I tested using only `READ` and `WRITE` permissions and works on Android 11. I'll remove the `MANAGE_EXTERNAL_STORAGE` from the README since it requires a deep review from the Play Store to get approved, and also because it's working without that.

2022-07-26 14:01 UTC, thiagocarvalhodev commented on ardrive_io/README.md
> +    <uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"/>
https://github.com/ardriveapp/ardrive-web/pull/596/commits/5c502916fd3c901be012d7e54934097275ea2d25

2022-07-26 14:06 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +  Future<List<IOFile>> pickFiles({List<String>? allowedExtensions}) async {
PE-1948

2022-07-26 17:27 UTC, fedellen commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +    return Future.wait(result.files.map((e) async {
Non blocking nit: As I'm first reading, I'm not sure if `e` is meant to be signal something special or if its just a regular file. I think `file` would read better

2022-07-26 17:29 UTC, fedellen commented on ardrive_io/lib/src/utils/mime_type_utils.dart
> +      return MimeType.OTHER;
```suggestion
    case 'text/plain':
      return MimeType.TEXT;
    case 'text/csv':
      return MimeType.CSV;
    default:
      return MimeType.OTHER;
```

2022-07-26 17:37 UTC, fedellen approved these changes
LGTM

2022-07-26 17:56 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +    return Future.wait(result.files.map((e) async {
I agree. Also, we can change this to an arrow function. https://github.com/ardriveapp/ardrive-web/pull/596/commits/f353b3fab7ea884bde23ae82a1513ae78c0e895c

2022-07-26 18:33 UTC, karlprieb commented on ardrive_io/README.md
> +Custom library to perform I/O operations at ArDrive Web
Nit :)
```suggestion
Custom library to perform I/O operations at ArDrive Web

```

2022-07-26 18:33 UTC, karlprieb approved these changes

2022-07-26 18:34 UTC, fedellen commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +        result.files.map((file) => fileAdapter.fromFilePicker(file)).toList());
I noticed async was removed here. I'm guessing this is fine, but I'm wondering if this has been re-tested

2022-07-26 18:34 UTC, fedellen submitted a review, later dismissed

2022-07-26 20:50 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +        result.files.map((file) => fileAdapter.fromFilePicker(file)).toList());
If the function body is just returning a `Future` or if it performs other statements that don't need a `await` keyword, we don't need the `async`.

For example:

```dart
/// doesn't need the async keyword and still being a Future
Future<dynamic> someFuture() {
/// does something that doesn't need await
return Future.value(something);
}

/// need a async keyword
Future<dynamic> someFutureWithAsync() async {
 final someVariable = await someFuture();
 /// do something with `someVariable`
 return someVariable;
}
```

2022-07-26 20:55 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +        result.files.map((file) => fileAdapter.fromFilePicker(file)).toList());
In this case the `Future.wait()` function receives a list of `Future`s. 

```dart
result.files.map((file) => fileAdapter.fromFilePicker(file)).toList())
```
The return of the `map((file) => fileAdapter.fromFilePicker(file))` will be `Future<IOFile>`, so we don't need the `async` keyword.

2022-07-28 15:57 UTC, matibat reviewed
Left a couple of question. Looking good overall, nice job!

2022-07-28 15:57 UTC, matibat commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +  final IOFolderAdapter folderAdapter;
Are these used in the tests or somewhere else? If not we can make those private.

2022-07-28 15:57 UTC, matibat commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +    throw FileSystemPermissionDeniedException([Permission.storage]);
Are we catching the errors somewhere? Would it break if not?

2022-07-28 16:16 UTC, matibat commented on ardrive_io/lib/src/io_file.dart
> +        name: path.basename(file.path),
Would it make sense to use `getFolderNameFromPath` here as well?

2022-07-28 16:17 UTC, matibat commented on ardrive_io/lib/src/io_file.dart
> +        name: path.basename(file.path),
Maybe rename to `getBasenameFromPath` (?

2022-07-28 16:50 UTC, arielmelendez commented on ardrive_io/README.md
> +Custom library to perform I/O operations at ArDrive Web
Double nit: `at` is not the correct preposition here. Consider `for` or `in`.

2022-07-28 17:11 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +    throw FileSystemPermissionDeniedException([Permission.storage]);
The client of this library should handle that exception. In our case, we should handle it on `Cubit` level or, even better, a `Repository` level.

2022-07-28 17:12 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +        name: path.basename(file.path),
>Maybe rename to getBasenameFromPath ?

I liked that suggestion!

2022-07-28 17:13 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/mobile/mobile_io.dart
> +  final IOFolderAdapter folderAdapter;
We aren't, so makes sense to make those private! To test `MobileIO` we should pass those dependencies via dependency injection.

2022-08-02 14:18 UTC, thiagocarvalhodev commented on ardrive_io/lib/src/io_file.dart
> +        name: path.basename(file.path),
https://github.com/ardriveapp/ardrive-web/pull/596/commits/0590eed6888f104b066989d13ca186d80f7b7234

2022-08-02 21:19 UTC, thiagocarvalhodev commented on ardrive_io/README.md
> +Custom library to perform I/O operations at ArDrive Web
https://github.com/ardriveapp/ardrive-web/pull/596/commits/a3a77d72bb7dbbb0954de2ebb40822b6f868f566

2022-08-03 14:14 UTC, karlprieb approved these changes

2022-08-03 17:19 UTC, matibat commented on ardrive_io/README.md
> +Custom library to perform I/O operations at ArDrive Web
Missing the nit of the space after, but I think that's a correct MD file anyways

2022-08-03 17:28 UTC, matibat approved these changes
Looks good to me. Really nice improvements, well done! 🚀

2022-09-13 21:32 UTC, closed without merging