fix: mobile support for the folder and file data table
ardriveapp/ardrive-web pull request #83
Opened 2021-02-04 14:26 UTC by jdaev

PR changes the datatable into a listview

2021-02-07 21:34 UTC, CDDelta requested changes

2021-02-07 21:34 UTC, CDDelta commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +      // sortAscending: state.contentOrderingMode == OrderingMode.asc,
nit: remove comments here

2021-02-07 21:34 UTC, CDDelta commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +    ListView(
The Figma includes separators on the ListView. We should probably have that in here too.

2021-02-07 21:34 UTC, CDDelta commented on lib/pages/drive_detail/drive_detail_page.dart
> +                                      alignment: Alignment.centerRight,
Looks like `DriveDetailActionRow` is supposed to be right-aligned here but doesn't show up as so?

Anyway, we should look into where else we can put these actions as opposed to having them in the header like on desktop. Perhaps in a bottom sheet that pops up?

Discuss in Slack.

2021-02-07 21:34 UTC, CDDelta commented on lib/misc/misc.dart
> +const kTrimTrailingRegex = r'[^\s \.]+$';
Is this the best way we can implement these Regexes? If so, please add a comment explaining why here.

2021-02-08 01:01 UTC, jdaev commented on lib/misc/misc.dart
> +const kTrimTrailingRegex = r'[^\s \.]+$';
It was the only way that worked. I tried doing some of it in a Validator.any function inside the form but that kept throwing an invalid type error.

2021-02-08 05:25 UTC, CDDelta commented on lib/misc/misc.dart
> +const kTrimTrailingRegex = r'[^\s \.]+$';
Sorry, I meant to add a comment in the code explaining why we're doing this so we know in the future. Hopefully, we can swap over when Safari supports negative lookbehinds.

2021-02-08 15:26 UTC, jdaev commented on lib/misc/misc.dart
> +const kTrimTrailingRegex = r'[^\s \.]+$';
Okay

2021-02-08 22:46 UTC, CDDelta commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +    Column(
You should be able to do [ListView.separated](https://api.flutter.dev/flutter/widgets/ListView/ListView.separated.html) right?

2021-02-08 22:49 UTC, jdaev commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +    Column(
Sure

2021-02-09 16:59 UTC, jdaev commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +    Column(
Think this is simpler though. I'd have to merge the subfolders and files into a single list to use it in an itembuilder.

2021-02-10 00:15 UTC, CDDelta commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +    Column(
True. You should be able to remove the `Column` widget and flatten the tree a bit by only returning a `ListTile` from `buildFolderListTile()` and `_buildFileListTile()` and then using `intersperseOuter()` on the resulting Widget list.

2021-02-10 00:33 UTC, jdaev commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +    Column(
Alright

2021-02-10 00:59 UTC, jdaev reviewed
Changes done

2021-02-11 22:32 UTC, CDDelta commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +            .intersperseOuter(Divider()),
Could you do `intersperseOuter()` on the entire data widget list instead? Doing it like this can lead to inconsistent results with views that have folders but no files.

2021-02-11 22:55 UTC, jdaev commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +            .intersperseOuter(Divider()),
Done

2021-02-11 23:09 UTC, CDDelta commented on lib/pages/drive_detail/components/drive_detail_data_list.dart
> +            .intersperseOuter(Divider()),
Sorry. I miswrote here. We should use `intersperse()` instead of `intersperseOuter()`. I believe that's more in line with general UI designs?

Beyond that. LGTM.

2021-02-11 23:09 UTC, CDDelta commented
As soon as you make the change with `intersperse()`, we can merge. Sorry bout that

2021-02-11 23:09 UTC, CDDelta approved these changes

2021-02-11 23:19 UTC, merged