Direct public drive attach
ardriveapp/ardrive-web pull request #86
Opened 2021-02-07 16:41 UTC by jdaev

Pass name through share link and attach drive automatically.

2021-02-09 00:27 UTC, jdaev commented
@CDDelta Any ideas on how to improve this?

2021-02-11 23:37 UTC, CDDelta requested changes

2021-02-11 23:37 UTC, CDDelta commented on lib/blocs/drive_attach/drive_attach_cubit.dart
> +    print(stackTrace);
Do we need to print this? Does `flutter_bloc` not do it properly with `super.onError()`?

2021-02-11 23:37 UTC, CDDelta commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +      super.onError(e, stackTrace);
Instead of calling `super.onError()` directly let's override `onError()` here like in some of the other blocs so that other methods in this bloc can use it if it comes up in the future.

2021-02-11 23:37 UTC, CDDelta commented on lib/blocs/drive_share/drive_share_cubit.dart
> +    var driveShareLink = '$linkOrigin/#/drives/${drive.id}?name=${driveName}';
nit: let's use `final` whenever possible. There should be a lint for this already enabled?

2021-02-11 23:37 UTC, CDDelta commented on lib/blocs/drive_share/drive_share_cubit.dart
> +    var driveName = drive.name.replaceAll(' ', '+').replaceAll('.', '');
I believe `encodeQueryComponent()` might be a better fit for this: https://api.dart.dev/stable/2.10.5/dart-core/Uri/encodeQueryComponent.html

2021-02-11 23:37 UTC, CDDelta commented on lib/blocs/drive_attach/drive_attach_cubit.dart
> +      if ((autoDriveId == null) && (autoDriveName == null)) {
nit: are the brackets around the conditions required here? I'm not sure that they add to the readablity but just let me know.

2021-02-11 23:37 UTC, CDDelta commented on lib/components/drive_attach_form.dart
> +            context.read<DriveAttachCubit>().submit(
Instead of providing the drive name here can the cubit be provided with the name on construction? The cubit can then initiate the drive attachment without an external prompt on it.

We should then be able to share the same code path with `promptToAttachDrive()` (though you'll maybe want to rename it to `attachDrive()` instead). And hide the `DriveAttachForm` when the drive is being auto-attached. To also get the progress dialogues etc to show up, you'll want to break the `BlocConsumer` into a `BlocBuilder` in the form and a `BlocListener` in `attachDrive().

The attach process can take a while so I believe it would be best to have an indicator here.

2021-02-11 23:37 UTC, CDDelta commented on lib/components/drive_attach_form.dart
> +            context.read<DriveAttachCubit>().submit(
The problem with your current method is you're calling `DriveAttachCubit.submit()` in a builder which runs again when Flutter rebuilds the widget tree after the drive attach is successful causing another cubit submission.

2021-02-11 23:49 UTC, jdaev commented on lib/blocs/drive_attach/drive_attach_cubit.dart
> +    print(stackTrace);
It was useful for printing to the web console. I'll remove it

2021-02-11 23:52 UTC, jdaev commented on lib/blocs/drive_attach/drive_attach_cubit.dart
> +      if ((autoDriveId == null) && (autoDriveName == null)) {
It does add to the readability at least for me. I usually group conditions but if it's unnecessary I'll remove it.

2021-02-11 23:54 UTC, jdaev commented on lib/components/drive_attach_form.dart
> +            context.read<DriveAttachCubit>().submit(
Alright. Thanks

2021-02-12 00:02 UTC, CDDelta commented on lib/blocs/drive_attach/drive_attach_cubit.dart
> +      if ((autoDriveId == null) && (autoDriveName == null)) {
Cool. Let's just keep it then.

2021-02-13 02:38 UTC, CDDelta requested changes

2021-02-13 02:38 UTC, CDDelta commented on lib/blocs/drive_share/drive_share_cubit.dart
> +    final driveName = drive.name.replaceAll(' ', '+').replaceAll('.', '');
Does the Uri constructor here not encode `driveName` properly?

2021-02-13 02:38 UTC, CDDelta commented on lib/blocs/drive_attach/drive_attach_cubit.dart
> +      submit(autoDriveId: initialDriveId, autoDriveName: driveName);
Instead of passing the constructor parameters through, could we set the form values and then just have `submit()` without parameters instead?

2021-02-13 02:38 UTC, CDDelta commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +    emit(DriveDetailLoadNotFound());
Lets not emit a NotFound state here. I believe NotFound leads to some side-effects in some BlocListeners that we don't want.

On further thought, can't you call `onError()` without `super`, without overriding `onError()` here?

2021-02-13 02:46 UTC, CDDelta commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +    } catch (e, stackTrace) {
I missed this before. What error are you trying to catch here? It doesn't look like there's anything new to catch.

If you really need to catch something, would it be possible to do a `handleError()` on the stream instead?

2021-02-13 03:11 UTC, CDDelta commented on lib/blocs/drive_share/drive_share_cubit.dart
> +    final driveName = drive.name.replaceAll(' ', '+').replaceAll('.', '');
Looks like the Uri constructor does encode its inputs. It does encode the `path` at least, the `Copy Link` result is now broken as the `https://` portion of the URL is encoded wrongly.

I believe it'll be easier to revert to the old way the Uri was constructed and just do [`Uri.encodeQueryComponent()`](https://api.dart.dev/stable/2.10.5/dart-core/Uri/encodeQueryComponent.html)

2021-02-13 03:46 UTC, jdaev commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +    emit(DriveDetailLoadNotFound());
I don't think so

2021-02-13 03:47 UTC, jdaev commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +    } catch (e, stackTrace) {
There was an uncaught exception being triggered from here. Something to do with dart.js

2021-02-13 08:36 UTC, CDDelta requested changes

2021-02-13 08:36 UTC, CDDelta commented on lib/blocs/drive_share/drive_share_cubit.dart
> +    final driveName = drive.name.replaceAll(' ', '+').replaceAll('.', '');
If you're already doing Uri.encodeQueryComponent, there should be no need for `replaceAll()` etc right?

The current way will cause drive names with spaces to come out with +s when shared.

2021-02-13 08:38 UTC, CDDelta commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +    emit(DriveDetailLoadNotFound());
Just tried it out. Looks like you can.

2021-02-13 08:42 UTC, CDDelta commented on lib/blocs/drive_detail/drive_detail_cubit.dart
> +    } catch (e, stackTrace) {
Is catching this crucial to the PR/feature? We should only be catching errors like this if we want to show an error in the UI as the runtime will throw uncaught errors for us.

If you can find a way to reproduce this and file a bug, it can be looked into in a separate issue.

2021-02-13 17:09 UTC, jdaev commented on lib/blocs/drive_share/drive_share_cubit.dart
> +    final driveName = drive.name.replaceAll(' ', '+').replaceAll('.', '');
Missed that. Thanks

2021-02-15 01:38 UTC, CDDelta commented on lib/components/drive_attach_form.dart
> +              showProgressDialog(context, 'ATTACHING DRIVE...');
Does this not cause us to show two "ATTACHING DRIVE..." dialogs?

Is this possibly what's causing the entire app page to do that sliding animation after the drive is attached?

2021-02-15 01:39 UTC, jdaev commented on lib/components/drive_attach_form.dart
> +              showProgressDialog(context, 'ATTACHING DRIVE...');
Possibly. Should I remove the one in DriveAttachProgress?

2021-02-15 01:41 UTC, CDDelta commented on lib/components/drive_attach_form.dart
> +              showProgressDialog(context, 'ATTACHING DRIVE...');
Remove the one in the listener. You'll need to also then update the `Navigator.pop()` calls there so we don't over pop.

2021-02-15 01:49 UTC, jdaev commented on lib/components/drive_attach_form.dart
> +              showProgressDialog(context, 'ATTACHING DRIVE...');
Okay

2021-02-15 23:00 UTC, CDDelta commented
Perfect, that post-attach page jank is gone! LGTM!

2021-02-15 23:00 UTC, CDDelta approved these changes

2021-02-15 23:00 UTC, merged