PE-2857: implement turbo uploads with BDI
ardriveapp/ardrive-web pull request #873
Opened 2023-01-30 19:47 UTC by javdhu

--- Releases ---
Android release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:android:6cf0cd5ec064fad3ffce07/releases/703e3f616uebg
iOS release: https://appdistribution.firebase.google.com/testerapps/1:305132849030:ios:06ea33a95a2e0d42ffce07/releases/35hu2lnf5msro

2023-01-31 15:04 UTC, thiagocarvalhodev commented on lib/blocs/upload/models/upload_plan.dart
> +      final areDataItemSizesUnderThreshold = await Future.wait(
Instead of verifying the whole list and then, in the line 68, you verify if every item is `true`, you can use the method `any`.
 
 ```dart
 final areDataItemSizesUnderThreshold =  fileDataItemUploadHandles.any((e) => await e.estimateDataItemSizes() >
              turboService.allowedDataItemSize));
```

2023-01-31 15:15 UTC, thiagocarvalhodev commented on lib/components/upload_form.dart
> +                            if (state.costEstimate.usdUploadCost != null)
Why this `usdUploadCost` can be null? If so, what should we do as feedback?

2023-01-31 15:20 UTC, thiagocarvalhodev requested changes
LEft some comments and a suggestion verifying if all files are under threshold.

2023-01-31 15:20 UTC, thiagocarvalhodev commented on lib/blocs/upload/models/upload_plan.dart
> +      final areDataItemSizesUnderThreshold = await Future.wait(
Consider moving this logic for a private function too

2023-01-31 17:55 UTC, thiagocarvalhodev commented on lib/components/upload_form.dart
> +                            if (state.costEstimate.usdUploadCost != null)
As it is a possible case, I'll check with our PO to create a ticket to improve the feedback. Thanks!

2023-01-31 17:57 UTC, thiagocarvalhodev commented on lib/blocs/upload/models/upload_plan.dart
> +  if (!turboService.useTurbo) return false;
Add new lines between the blocks of code

2023-01-31 18:06 UTC, matibat submitted a review, later dismissed
LGTM

2023-01-31 18:11 UTC, thiagocarvalhodev approved these changes
LGTM.

2023-02-09 01:07 UTC, thiagocarvalhodev submitted a review, later dismissed

2023-02-17 15:21 UTC, karlprieb approved these changes

2023-02-23 14:28 UTC, karlprieb approved these changes

2023-02-23 14:29 UTC, merged