PE-2930: Let the "Computing snapshot" modal to be cancellable
ardriveapp/ardrive-web pull request #880
Opened 2023-02-03 19:42 UTC by matibat

2023-02-06 18:53 UTC, matibat reviewed
https://user-images.githubusercontent.com/22564541/217059715-af155b78-759d-48e9-a15b-f211b6dfe939.mov

2023-02-06 19:56 UTC, thiagocarvalhodev approved these changes
LGTM!

2023-02-06 19:56 UTC, thiagocarvalhodev commented on lib/components/create_snapshot_dialog.dart
> +          child: Text(appLocalizationsOf(context).cancel),
add a `,` after `cancel`

2023-02-06 19:56 UTC, thiagocarvalhodev commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +    _snapshotDataStreamSubscription =
nit: you can still use the `await for`.

```dart
await for (final item in _newItemToBeCreated.getSnapshotData()) {
      if(_wasSnapshotDataStreamSubscriptionCanceled) {
             throw Exception('canceled');
      }       
      dataBuffer.add(item);
}

 void cancelSnapshotCreation() async {
    _wasSnapshotDataStreamSubscriptionCanceled = true;
  }

2023-02-06 20:01 UTC, thiagocarvalhodev requested changes

2023-02-06 20:01 UTC, thiagocarvalhodev commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +  Future<void> cancelSnapshotCreation() async {
We're missing a test for this method.

2023-02-06 22:19 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +    _snapshotDataStreamSubscription =
I used listen here cuz it returns the subscription I can utilize to cancel the stream. I'm gonna try by simply throwing the way you suggested as the `await for` would consume the stream as well.

2023-02-07 13:44 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +    _snapshotDataStreamSubscription =
Much cleaner - a176c4c9ef66dda3ecffd9231b661fc9f85c56b7

2023-02-07 13:44 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +  Future<void> cancelSnapshotCreation() async {
Something like this -> 8cef93d5a4c9db072e3047f3d4b43189ba2148e4

2023-02-07 13:48 UTC, matibat commented on lib/components/create_snapshot_dialog.dart
> +          child: Text(appLocalizationsOf(context).cancel),
126adf839eee26898b8f1aea39fda169bbcced8a

2023-02-08 14:49 UTC, thiagocarvalhodev approved these changes
LGTM

2023-02-08 15:27 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +  bool _wasSnapshotDataComputingCanceled = false;
https://ardrive.atlassian.net/browse/PE-2954

2023-02-08 16:09 UTC, merged