feat: add and show minimum pst tip
ardriveapp/ardrive-web pull request #89
Opened 2021-02-12 14:49 UTC by jdaev

2021-02-13 02:28 UTC, CDDelta commented on lib/blocs/upload/upload_cubit.dart
> +      pstFee = _minimumpstTip;
You should be able to use `[math.max()](https://api.dart.dev/stable/2.10.4/dart-math/max.html)` here.

Also, lets define minimumPstTip as a local variable instead since it's only ever used here.

2021-02-13 02:30 UTC, CDDelta commented on lib/blocs/upload/upload_state.dart
> +  // Amount to PST holders in USD
nit: comment should come before the field declaration?

2021-02-13 02:32 UTC, CDDelta commented on lib/components/upload_form.dart
> +                        style: Theme.of(context).textTheme.bodyText1,
Did Phil request this? I recall him mentioning to not include it.

2021-02-13 02:33 UTC, jdaev commented on lib/components/upload_form.dart
> +                        style: Theme.of(context).textTheme.bodyText1,
Yes, he did

2021-02-13 02:58 UTC, CDDelta commented on lib/blocs/upload/upload_state.dart
> +  // Amount to PST holders in USD
Looks like `pstCost` here refers is in AR too, not USD?

Could you also call it something like `arPstCost` to be more explicit and consistent with the others?

2021-02-13 02:58 UTC, CDDelta commented on lib/components/upload_form.dart
> +                        style: Theme.of(context).textTheme.bodyText1,
If this is just a single line of text you can just use `Text()` right?

2021-02-13 04:02 UTC, jdaev commented on lib/components/upload_form.dart
> +                        style: Theme.of(context).textTheme.bodyText1,
Yes

2021-02-13 08:30 UTC, CDDelta requested changes

2021-02-13 08:30 UTC, CDDelta commented on lib/blocs/upload/upload_state.dart
> +  /// Amount to PST holders in USD
/// The PST tip paid in (AR)?

2021-02-13 08:31 UTC, CDDelta commented on lib/blocs/upload/upload_cubit.dart
> +    final _minimumpstTip = BigInt.from(10000000);
nit: it should be _minimumPstTip

2021-02-15 01:27 UTC, CDDelta commented
Looks like there's a bug? I can't upload any files and get a `checkNum` error in the preview build.

Also, we should get Phil to review the UI.

2021-02-15 22:35 UTC, jdaev commented
The error was due to using math.max(). Works fine with a ternary operator or if condition.

2021-02-16 02:32 UTC, CDDelta commented on lib/blocs/upload/upload_cubit.dart
> +    final pstCost = winstonToAr(pstFee);
Is this used anymore?

2021-02-16 02:33 UTC, CDDelta approved these changes

2021-02-16 02:33 UTC, CDDelta commented
Just fix the issue with the unused variable and merge. Nice!

2021-02-16 04:19 UTC, merged