PE-3012: Resume prepare/sign on tab focus when ArConnect wallet
ardriveapp/ardrive-web pull request #903
Opened 2023-02-16 20:16 UTC by matibat

2023-02-16 22:07 UTC, matibat commented
TODO: unit test the ArConnect tab focus stuff when preparing/signing, on the Snapshot Cubit

2023-02-16 22:34 UTC, matibat reviewed
Self-review checkpoint

2023-02-17 13:28 UTC, karlprieb commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +    if (await _profileCubit.isCurrentProfileArConnect()) {
just create a variable for that and use it on both `if` blocks

2023-02-17 13:31 UTC, karlprieb commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +  Future<void> _prepareSnapshotTx(
You can abstract prepareEntity and signTx. As we do the same thing for both JSON wallet and arconnect(we wait for focus here, but the function called is the same with the same params) we can create these abstractions and check if it's arconnect or not there.
At the end we should have a more readable `_prepareSnapshotTx` function

2023-02-17 13:33 UTC, karlprieb commented on lib/blocs/create_snapshot/create_snapshot_state.dart
> +/// User has insufficient balance to create the snapshot
we don't need this comment. the class name is self-explanatory

2023-02-17 13:37 UTC, karlprieb requested changes
Waiting for ArConnect tests. You can mock `whenTabIsUnhiddenFuture` and `isTabHidden` for that

2023-02-17 13:50 UTC, karlprieb commented on lib/utils/html/implementations/html_web.dart
> +Future<void> whenTabIsUnhiddenFuture(FutureOr<Function> onShow) async {
As this `Future` is meant to be used as a one-time thing, we should close the visibility stream (`closeVisibilityChangeStream`) after execute the callback. If we don't do that, the stream will remain opened and call the listener callback every time we have a window visibility change.

2023-02-17 13:51 UTC, karlprieb commented on lib/utils/html/implementations/html_web.dart
> +      await onShow;
should we execute `onShow` here?

2023-02-17 13:52 UTC, karlprieb commented on lib/utils/html/html_util.dart
>  bool isBrowserTabHidden() => implementation.isTabHidden();
Not related to this ticket, but we could use better names for these functions like:
- `isBrowserTabHidden` could be `isTabOnFocus`
- `whenBrowserTabIsUnhidden` could be `whenTabIsOnFocus` and the param to `onFocus`

2023-02-17 14:36 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +  Future<void> _prepareSnapshotTx(
There we are -> ab2fbc5d54ab94c889de3c1694577cfc5e32e516

2023-02-17 14:37 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_state.dart
> +/// User has insufficient balance to create the snapshot
Agree - a247d3f538ddedbcfe99403cdee29b81a4c5f9ed

2023-02-17 14:57 UTC, matibat commented on lib/utils/html/implementations/html_web.dart
> +Future<void> whenTabIsUnhiddenFuture(FutureOr<Function> onShow) async {
ad0f569a3d8ae6c664b23490aea05b15b22bf9d5

2023-02-17 14:59 UTC, matibat commented on lib/utils/html/implementations/html_web.dart
> +      await onShow;
Because it has the type `FutureOr<Function>`: `"The expression doesn't evaluate to a function, so it can't be invoked."`. So I simply await for it.

2023-02-17 15:08 UTC, matibat commented
> Waiting for ArConnect tests. You can mock whenTabIsUnhiddenFuture and isTabHidden for that

The thing is that we can't actually mock those methods. We gotta make the class testable.

2023-02-21 15:03 UTC, karlprieb commented on lib/utils/html/implementations/html_web.dart
> +Future<void> whenTabIsUnhiddenFuture(FutureOr<Function> onShow) async {
No... just call `closeVisibilityChangeStream` in `whenTabIsUnhiddenFuture` after you call `onShow`

2023-02-21 15:04 UTC, karlprieb commented on lib/utils/html/html_util.dart
>  bool isBrowserTabHidden() => implementation.isTabHidden();
Can you rename them in this ticket?

2023-02-21 15:05 UTC, karlprieb commented
> The thing is that we can't actually mock those methods. We gotta make the class testable.

Let's to that then! Create a new subtask to implement arconnect tests

2023-02-21 19:34 UTC, matibat commented on lib/utils/html/implementations/html_web.dart
> +Future<void> whenTabIsUnhiddenFuture(FutureOr<Function> onShow) async {
Like this? a596e3cf80b230d20da1c3e3ae7b5db77bfe4754

2023-02-21 20:03 UTC, matibat commented on lib/utils/html/html_util.dart
>  bool isBrowserTabHidden() => implementation.isTabHidden();
Renamed and updated the logic of isTabFocused to match its name - 06308208ae2b9cfb7b218dfe0c890d6f34f73028

2023-02-21 20:13 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +
```suggestion
```

2023-02-21 20:20 UTC, matibat commented on lib/utils/html/implementations/html_web.dart
> +bool isTabFocused() {
**For the reviewer** I've double checked this many times, but please don't trust me: please be thoughtful when reviewing this change around the codebase as it changed both: the name and the logic to make the opposite. I.e. ensure everywhere where it was called, that it's negated (either by adding the `!` "not" or by removing it)

2023-02-21 20:26 UTC, matibat reviewed
Self-review checkpoint

2023-02-22 17:10 UTC, karlprieb commented on lib/utils/html/implementations/html_web.dart
> +Future<void> whenTabIsUnhiddenFuture(FutureOr<Function> onShow) async {
Yep 👍

2023-02-22 19:26 UTC, thiagocarvalhodev approved these changes
LGTM!

2023-02-22 19:26 UTC, thiagocarvalhodev commented on lib/utils/html/implementations/html_web.dart
> +bool isTabFocused() {
I checked and seems good, Mati!

2023-02-22 19:37 UTC, karlprieb approved these changes

2023-02-22 23:03 UTC, merged