PE-3048: unit test retry prepare/sign snapshot tx on tab focus when ArConnect
ardriveapp/ardrive-web pull request #907
Opened 2023-02-22 16:03 UTC by matibat

2023-02-22 16:07 UTC, matibat commented on test/blocs/create_snapshot_cubit_test.dart
> +          // FIXME: Before calling confirm, you have to set throwOnPrepareTxForTesting to false delayed by less than 10 ms
```suggestion
```

2023-02-22 16:08 UTC, matibat reviewed
Self-review checkpoint

2023-02-22 19:43 UTC, thiagocarvalhodev requested changes
@matibat , not sure I follow the variables to throw in the CreateSnapshotCubit. Can you verify if using the `thenThrow` at your mocked class satisfy your needs?

2023-02-22 19:43 UTC, thiagocarvalhodev commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +      if (throwOnPrepareTxForTesting) {
Instead of using this boolean to throw an exception, you can mock the `_arweave.prepareEntityTx` to throw an Exception on your test. See this example from the `ardrive_auth_test.dart` at new login flow:

```dart
  test('should return false when password is wrong', () async {
      // arrange
      when(() => mockArweaveService.getFirstPrivateDriveTxId(wallet,
              maxRetries: any(named: 'maxRetries')))
          .thenAnswer((_) async => 'some_id');
      // mock cripto derive drive key
      when(
        () => mockArDriveCrypto.deriveDriveKey(
          wallet,
          any(),
          any(),
        ),
      ).thenThrow(Exception('wrong password'));

      // assert
      expectLater(() => arDriveAuth.login(wallet, 'password', ProfileType.json),
          throwsA(isA<AuthenticationFailedException>()));
    });
  });

2023-02-22 19:43 UTC, thiagocarvalhodev commented on lib/utils/html/html_util.dart
> +class TabVisibilitySingleton {
Nice!

2023-02-22 20:58 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +      if (throwOnPrepareTxForTesting) {
Nice catch!

I was initially forcing it to throw with that custom code, but at some point I made it to throw with of the mock (as you just said). That being said: I will remove the custom throw for prepare, BUT I cannot mock Transaction::sign to force it throw SO I'll leave the code for forcing the sign stage to throw as it is if that's OK

2023-02-22 21:01 UTC, matibat commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +      if (throwOnPrepareTxForTesting) {
Cubit - 2c9871c9c4a64c74cfd973f3ea077d83d9f8263b
Test - 1a2389285a39271b8ea6d2924b747f87eb514207

2023-02-23 15:10 UTC, karlprieb commented on lib/utils/html/html_util.dart
> +class TabVisibilitySingleton {
We can name it to `TabVisibility` there's no reason to enforce it is a singleton.

2023-02-23 16:17 UTC, matibat commented on lib/utils/html/html_util.dart
> +class TabVisibilitySingleton {
It indeed is a singleton (if you take a look to the constructors):
```dart

  /// Here it is the SINGLE (static) private instance of it.
  static final TabVisibilitySingleton _singleton =
      TabVisibilitySingleton._internal();

  /// The factory will return the same instance of the singleton on every call.
  factory TabVisibilitySingleton() {
    return _singleton;
  }

  /// This is the private constructor which is called once from the static _singleton.
  TabVisibilitySingleton._internal();
```

BTW I chose it to be a singleton so we don't need to be passing multiple instances of this class which doesn't actually track a state. I also considered multiple instances with static methods, but that's not testable so the singleton approach fits well for this case.

2023-02-23 16:23 UTC, matibat commented on lib/utils/html/html_util.dart
> +class TabVisibilitySingleton {
I added a unit test to verify this behavior: 86391b2d71dcdb16cb8d9656e75ecf7510c99614

2023-02-23 16:38 UTC, karlprieb commented on lib/utils/html/html_util.dart
> +class TabVisibilitySingleton {
I know it’s a singleton, I’m just saying we don’t need to name it as singleton

2023-02-23 16:42 UTC, matibat commented on lib/utils/html/html_util.dart
> +class TabVisibilitySingleton {
Ohh got it. In that case, then that's something I've learned from Clean Code: to be really specific on the way we name stuff: "Am I following the composite pattern?" suffix it as so: "MyClassComposite", "Am I following the Singleton pattern?" then suffix the class as so: "MyClassSingleton". But we can take our own approach for naming objects, if we prefer not to mention "singleton" I can remove it

2023-02-23 16:45 UTC, karlprieb commented on lib/utils/html/html_util.dart
> +class TabVisibilitySingleton {
I’m good with that, it’s just something that we don’t do for singletons currently.
We can try to name things that way.

2023-02-23 18:09 UTC, thiagocarvalhodev commented on lib/blocs/create_snapshot/create_snapshot_cubit.dart
> +      if (throwOnPrepareTxForTesting) {
Sounds good! Thanks Mati!

2023-02-23 18:09 UTC, thiagocarvalhodev approved these changes

2023-02-23 18:16 UTC, merged