PE-3132: implement isTabFocused distinct from isTabVisible
ardriveapp/ardrive-web pull request #961
Opened 2023-03-20 21:15 UTC by matibat

2023-03-20 21:21 UTC, matibat commented
GH Actions failing because of a bad deppendency

2023-03-21 06:52 UTC, matibat reviewed
Self-review checkpoint

2023-03-21 06:52 UTC, matibat commented on lib/blocs/sync/utils/arconnect_connectivity.dart
Oops! Unintended file committed! - TODO: remove

2023-03-21 06:52 UTC, matibat commented on lib/utils/html/html_util.dart
> +  /// TODO: Cancel these subscriptions
TODO: create a tech debt "Correctly handle Stream Subscriptions"

2023-03-21 06:52 UTC, matibat commented on lib/utils/html/implementations/html_web.dart
TODO: Cleanup the newly introduced methods

2023-03-21 07:08 UTC, matibat commented on lib/blocs/sync/utils/arconnect_connectivity.dart
d5be4a470778e323e0f4edba193f363bf54c9f11

2023-03-21 07:08 UTC, matibat commented on lib/utils/html/implementations/html_web.dart
597779f404fdd15a23aa0f70b535fc05069d921d

2023-03-21 18:11 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +    late bool hasPermissions;
Using `late` leaves you responsible for making sure the assignment takes place before it's used and Dart will let you shoot yourself in the foot if you're so inclined. I tend to use the following syntax for type-safe conditional assignments (an anonymous closure declared and executed in place):
```
    bool hasPermissions = await (() async {
      try {
        return await arconnect.safelyCheckPermissions();
      } catch (e) {
        print(
          '[ProfileCubit] ArConnect permissions check failed - waiting for tab focus',
        );
        return await arconnect.safelyGetPermissionsWhenTabFocused();
      }
    })();
```

2023-03-21 18:18 UTC, arielmelendez commented on lib/blocs/profile/profile_cubit.dart
> +    try {
This pattern does not look so user-friendly. It implies that anyone who ever calls `safelyCheckPermissions` should wrap with `try` then call `safelyGetPermissionsWhenTabFocused` upon exception. Remember one of the golden rules of programming:
`Make interfaces easy to use correctly and hard to use incorrectly.`
The pattern you're using here does not seem to fit those criteria. If I were just reading the API names, I'd have a hard time choosing which to call. They both have `safely` in their name, so they appear "safe". Despite that appearance, at least one of them `safelyCheckPermissions` might actually THROW! That doesn't seem so `safe`. This needs work.

2023-03-21 18:24 UTC, arielmelendez commented on lib/blocs/sync/sync_cubit.dart
> +      if (await _profileCubit.logoutIfWalletMismatch()) {
To the point about making interfaces easy to use correctly and hard to use incorrectly, might there be arguments for or against simply doing the focus check inside of `checkIfWalletMismatch`?

2023-03-21 18:25 UTC, arielmelendez commented on lib/services/arconnect/arconnect.dart
> +      throw FocusError('Tab is not focused');
Not a great idea to throw from a function with `safe` in the name.

2023-03-21 18:26 UTC, arielmelendez commented on lib/utils/html/implementations/html_stub.dart
> +StreamSubscription onTabBlurred(Function onBlur) {
Do we still need these if we have access to `hasFocus` now? They're complementary approaches, but if we don't need the event based piece right now, then it's just less code to review, test, and support.

2023-03-21 18:33 UTC, arielmelendez commented on lib/utils/html/implementations/html_web.dart
> +void onTabGetsFocused(Function onFocus) {
What's the point of this function? It doesn't look like anyone is using it. Also it leaks StreamSubscriptions each time it's called subsequently....

2023-03-21 18:33 UTC, arielmelendez commented on web/index.html
> +</html>
Did the code formatter remove trailing whitespace?

2023-03-21 19:07 UTC, arielmelendez commented on lib/utils/html/implementations/html_web.dart
>  Future<void> onTabGetsFocusedFuture(FutureOr<Function> onFocus) async {
I'm not a fan of this function for a handful of reasons:
1) It's both a Future allowing you to await for it to complete if you wanted to AND it has a callback function. That's a strange mix of paradigms
2) It's not clear as a caller what it will do if I'm focused already... will it call the callback? Will it not fire the callback until I've gone blurred and then returned to focus? It's not clear in the function name. From my reading of the code, it appears like it will wait until the NEXT time we become focused. This seems like the kind of behavior that you might want to be configurable.
3) Since the passed closure is a `FutureOr<Function>`, it's not clear whether the stream handler function will (or should?) await on it or simply call it (i.e. fire and forget).
4) It's not clear what the error propagation pattern is or should be for the callback function.

2023-03-21 19:08 UTC, arielmelendez commented on lib/services/arconnect/arconnect.dart
> +    // FIXME: inject this value for testing purposes
Sure, and a new instance could be the default value if not provided.

2023-03-21 19:14 UTC, arielmelendez commented on lib/utils/html/implementations/html_stub.dart
> +bool isTabVisible() {
With this change I would have expected every caller around the app to have changed the called name to `isTabVisible` as well and for `isTabFocused` to only be used around the ArConnect stuff we are updating. Have you inadvertently caused all the callers of `isTabFocused` to have potentially changed their behavior?

2023-03-21 19:14 UTC, arielmelendez requested changes
Needs a handful of changes for clarity.

2023-03-22 14:12 UTC, karlprieb commented on lib/utils/html/implementations/html_web.dart
> +    (event) {
you don't need `event` here as it's not used

2023-03-22 14:21 UTC, karlprieb commented on lib/utils/html/implementations/html_web.dart
> +    (event) {
same thing for `onTabBlurred`

2023-03-22 16:16 UTC, matibat commented on lib/utils/html/html_util.dart
> +  /// TODO: Cancel these subscriptions
It is for the html_web.dart source file - https://ardrive.atlassian.net/browse/PE-3295

2023-03-22 16:22 UTC, matibat commented on lib/blocs/profile/profile_cubit.dart
> +    try {
Both methods throw, it is "safe" in the sense that it doesn't return a false negative (i.e. returning `false` when the race condition takes place). Anyway, your comment makes sense to me, so I'd make the `safelyGetPermissionsWhenTabFocused` method instantly return if we do have the permissions

2023-03-22 16:52 UTC, karlprieb commented on lib/utils/html/implementations/html_web.dart
>  Future<void> onTabGetsFocusedFuture(FutureOr<Function> onFocus) async {
1. Is there a place where you will not wait for the event? If so, we can have only a future that returns when you get focused and the caller can do whatever they need. If we still want to let a function handle the callback when it's ready, so the caller can move on with their code, the `onTabGetsFocused` can be used.
2. Agreed
3. I think it's clear that it will `await` on it or just call, depending on the callback that you pass.
4. 100% agreed

2023-03-22 17:06 UTC, karlprieb commented on lib/services/arconnect/arconnect.dart
> +      throw FocusError('Tab is not focused');
I really don't get the naming... why use safe? Does it mean that it's safe to call and it will work every time? Will it return something even when we get an error? I would just return a boolean and the caller decides what to do.

2023-03-22 17:20 UTC, karlprieb commented on lib/services/arconnect/arconnect.dart
> +  Future<bool> safelyGetPermissionsWhenTabFocused() async {
I understand that `safelyGetPermissionsWhenTabFocused` should be used when your willing to wait for the next on focus event to check permissions and `safelyCheckPermissions` is for when you just want to check permissions whenever the focus state is.
I don't see a clear usage for `safelyCheckPermissions`, every time we need to check for permissions is because is important to have reliable data, so why we just dont have a function that will abstract both of these functions?
It could check for focus, if we have focus it tries to get permissions, if not it will wait for the next on focus event and try to get the permissions returning a boolean.

2023-03-22 17:31 UTC, karlprieb commented on lib/blocs/profile_add/profile_add_cubit.dart
> +      if (!(await arconnect.safelyCheckPermissions())) {
Here we should just use that abstraction that I commented before where it will return the boolean if it's focused or wait until it gets focused to check the permissions.
Without that the caller will have to do that if it really wants to pick the wallet.

2023-03-23 00:53 UTC, closed without merging